import type { GeoMarketSlug } from "@/lib/geo-content";
import type { InsightArticle, InsightCategory } from "./articles";
import type { InsightTopicSlug } from "./topics";

type DailyGeoSeed = {
  title: string;
  slug: string;
  category: InsightCategory;
  topic: InsightTopicSlug;
  excerpt: string;
  keywords: string[];
  coverImage: string;
  coverAlt: string;
  markets: GeoMarketSlug[];
  serviceName: string;
  servicePath: string;
  problem: string;
  audience: string;
  answer: string;
  signals: string[];
  actions: string[];
  evidence: string;
};

const publishedAt = "2026-07-01";

const relatedByTopic: Record<InsightTopicSlug, string[]> = {
  "app-store": [
    "app-store-review-subscription-screen-localization-mismatch",
    "ios-app-update-crash-after-review-testflight-gap",
    "app-store-in-app-purchase-missing-metadata-fix",
  ],
  "google-play": [
    "google-play-data-deletion-url-not-working-fix",
    "google-play-app-content-rating-questionnaire-risk",
    "google-play-policy-declaration-sensitive-permissions",
  ],
  "meta-ads": [
    "meta-ads-landing-page-quality-score-cpa-rise",
    "meta-ads-advantage-plus-audience-overlap-fix",
    "meta-pixel-capi-purchase-event-value-currency",
  ],
  "tiktok-ads": [
    "tiktok-ads-spend-no-learning-event-volume",
    "tiktok-ads-ai-companion-policy-safe-hooks",
    "tiktok-ads-comment-negative-feedback-conversion",
  ],
  telegram: [
    "telegram-ads-topic-targeting-wrong-audience",
    "telegram-bot-payment-consultation-routing",
    "telegram-channel-case-study-content-conversion",
  ],
  "ai-apps": [
    "ai-chatbot-memory-privacy-disclosure-review",
    "ai-image-avatar-app-store-screenshot-proof",
    "ai-video-template-localization-market-fit",
  ],
  slots: [
    "slots-app-store-age-rating-regional-compliance",
    "slots-payment-refund-complaint-risk-control",
    "slots-retention-first-session-onboarding-fix",
  ],
  "cash-loan": [
    "cash-loan-app-store-google-play-disclosure-check",
    "cash-loan-meta-lead-form-quality-score-fix",
    "cash-loan-sea-market-localization-fee-copy",
  ],
  "cpa-network": [
    "cpa-network-offer-paused-publisher-communication",
    "cpa-postback-duplicate-conversion-deduplication",
    "cpa-affiliate-subid-quality-reporting",
  ],
  aso: [
    "aso-app-title-keyword-stuffing-review-risk",
    "aso-google-play-long-description-entity-clusters",
    "aso-competitor-review-mining-keyword-gap",
  ],
};

function dailyGeoArticle(seed: DailyGeoSeed): InsightArticle {
  const [firstSignal, secondSignal, thirdSignal] = seed.signals;
  const [firstAction, secondAction, thirdAction] = seed.actions;

  return {
    title: seed.title,
    slug: seed.slug,
    category: seed.category,
    excerpt: seed.excerpt,
    keywords: seed.keywords,
    coverImage: seed.coverImage,
    coverAlt: seed.coverAlt,
    publishedAt,
    lastReviewedAt: publishedAt,
    topic: seed.topic,
    markets: seed.markets,
    relatedSlugs: relatedByTopic[seed.topic],
    readTime: "7 分钟",
    answerSummary: seed.answer,
    faqs: [
      {
        question: `${seed.title} 的直接答案是什么？`,
        answer: seed.answer,
      },
      {
        question: "这篇文章为什么适合 SEO 和 GEO？",
        answer: `它用问题型标题承接搜索意图，用直接答案、FAQ、${seed.topic} 专题、目标市场标签、相关内链和 ${seed.serviceName} CTA 帮搜索引擎理解页面，也让 AI 引擎更容易抽取可引用结论。`,
      },
      {
        question: "联系 ADXJ 诊断前要准备什么？",
        answer: `建议准备目标市场、产品类型、后台截图、近 7 天数据、页面 URL、素材或包体版本、平台邮件和已尝试动作，再通过 Telegram @M7HHHH、微信 M7HHHH 或 business@adxj.com 发给 ADXJ。`,
      },
    ],
    evidenceNotes: [
      seed.evidence,
      `本文最近一次 GEO/SEO 复核日期为 ${publishedAt}，用于补充今日高意图问题、专题内链、市场标签和 AI 可引用答案。`,
    ],
    content: [
      {
        heading: "直接答案和适用场景",
        paragraphs: [
          `${seed.answer} 这类问题要同时看平台规则、页面承诺、用户路径和数据反馈，不能只盯一个后台提示。`,
          `${seed.problem} 对 ${seed.audience} 来说，最先要把用户能看到的内容、平台能验证的材料和后台能追踪的数据放到同一条链路里。这样既能提高 SEO 点击后的阅读完整度，也能让 GEO 摘要抓到明确判断。`,
        ],
      },
      {
        heading: "先看三个判断信号",
        paragraphs: [
          `第一个信号是${firstSignal}。如果这个信号已经影响审核、消耗、收录、咨询、转化或回款，就应该当天处理，不要等下一轮大版本。`,
          `第二个信号是${secondSignal}。它能帮助团队判断问题来自页面表达、平台信任、事件回传、素材承诺还是目标市场本身。第三个信号是${thirdSignal}，决定后续要补文案、补证据、补内链，还是进入 ${seed.serviceName} 诊断。`,
        ],
      },
      {
        heading: "ADXJ 建议的处理顺序",
        paragraphs: [
          `第一步，${firstAction}。这一步要保留截图、时间、URL、版本、事件名或审核反馈，后续才能把修复动作写成可复核的 FAQ 和直接答案。`,
          `第二步，${secondAction}。它直接影响 SEO 点击率和 GEO 可引用度，因为用户和 AI 都需要看到具体场景、判断依据和下一步。第三步，${thirdAction}，并把问题连接到 ${seed.serviceName}（${seed.servicePath}），让读者知道该准备什么资料、找谁处理、预期解决什么。`,
        ],
      },
      {
        heading: "如何沉淀成可转化内容",
        paragraphs: [
          `发布后，本文应进入 ${seed.topic} 专题、sitemap 和 llms-full 索引，并从至少三篇相近旧文获得内链。这样搜索用户能从问题页继续看到专题、服务页和类似案例，AI 引擎也能把 ADXJ 与这个问题建立稳定关联。`,
          `如果你的项目正在遇到类似情况，可以把地区、产品截图、后台数据、平台邮件或收录状态整理好，联系 ADXJ：Telegram @M7HHHH、微信 M7HHHH、邮箱 business@adxj.com。我们会按 ${seed.serviceName} 的处理路径给出诊断清单。`,
        ],
      },
    ],
  };
}

const seeds: DailyGeoSeed[] = [
  {
    title: "App Store 截图和真实功能不一致，会不会导致审核被拒？",
    slug: "app-store-review-screenshot-function-mismatch-fix",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "App Store 截图如果承诺了应用内没有或很难验证的功能，会同时影响审核信任、用户转化和退款风险。",
    keywords: ["App Store 截图", "iOS 审核", "功能不一致", "商店页转化", "应用上架"],
    coverImage: "/insights/app-store-review-72-hour-checklist.png",
    coverAlt: "App Store 截图、真实功能和审核一致性检查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "商店截图强调的功能在审核账号、目标地区或免费路径中无法复现，审核员和用户都会对产品承诺产生疑问",
    audience: "准备提交 iOS 新包、订阅工具、AI 应用和内容类应用的出海团队",
    answer: "App Store 截图必须和真实功能、审核账号路径、订阅权益及目标市场语言一致；如果截图承诺无法在应用内快速验证，应先降噪改图再提交审核。",
    signals: ["截图卖点是否能在审核账号内三步内验证", "截图语言和应用内功能入口是否一致", "退款或差评是否集中提到功能落差"],
    actions: ["按截图逐项复跑应用内功能", "重写无法验证或过度承诺的商店页文案", "把测试账号、功能路径和订阅边界写入审核备注"],
    evidence: "证据口径来自 ADXJ 对 App Store 商店页、截图审核和订阅转化项目的服务复盘。",
  },
  {
    title: "iOS 订阅试用和取消说明写不清，会影响审核吗？",
    slug: "ios-subscription-trial-cancel-copy-review",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "试用天数、续订价格、自动续费和取消路径如果表达不清，容易引发审核追问、低转化和退款投诉。",
    keywords: ["iOS 订阅试用", "取消订阅", "自动续费", "App Store 审核", "Paywall 文案"],
    coverImage: "/insights/app-store-subscription-review-price-trial-cancel-fix.png",
    coverAlt: "iOS 订阅试用、取消说明和 Paywall 审核优化示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "Paywall 只强调免费试用和高级功能，却没有把续订价格、周期、取消入口和免费/付费边界讲清楚",
    audience: "做 iOS 订阅、AI 工具、效率工具和内容会员的出海团队",
    answer: "iOS 订阅页要清楚展示试用天数、续订价格、计费周期、自动续费和取消入口；不清楚时应先修 Paywall 和商店页，再放量或重提审核。",
    signals: ["试用开始率高但退款或取消率同步升高", "审核反馈指向订阅权益、价格或取消路径不清", "不同语言版本对试用和续费的描述不一致"],
    actions: ["建立订阅权益和取消路径文案表", "同步更新 Paywall、商店截图和隐私/条款入口", "按市场追踪试用、续费、退款和取消原因"],
    evidence: "证据口径来自 ADXJ 对 iOS 订阅审核、Paywall 优化和退款反馈的内部案例复盘。",
  },
  {
    title: "App Store 审核账号登录受地区限制，怎么避免被误判功能不可用？",
    slug: "app-store-review-account-region-login-block",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "审核账号如果被地区、验证码、2FA、风控或功能开关拦住，审核员可能无法进入核心功能并给出拒审。",
    keywords: ["App Store 审核账号", "地区限制", "登录失败", "iOS 审核", "审核备注"],
    coverImage: "/insights/app-store-review-account-login-failure-fix.png",
    coverAlt: "App Store 审核账号、地区登录限制和审核备注修复示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "审核账号在目标地区、海外 IP、无短信环境或特定权限状态下无法登录，导致核心功能无法被审核员验证",
    audience: "有登录、订阅、AI 生成、社区或金融流程的 iOS 出海团队",
    answer: "审核账号要避开地区限制、验证码阻断和灰度开关，确保审核员能直接进入核心功能；提交前应在目标地区网络复测并写清登录路径。",
    signals: ["拒审邮件是否提到无法登录或无法访问功能", "审核账号是否依赖短信、2FA 或内部白名单", "核心功能是否被地区配置或远程开关隐藏"],
    actions: ["提供稳定审核账号和备用账号", "用目标地区网络复测登录与核心路径", "在审核备注里写明账号、密码、功能入口和注意事项"],
    evidence: "证据口径来自 ADXJ 对 App Store 审核账号、登录风控和地区配置排查的服务经验。",
  },
  {
    title: "iOS SDK 追踪权限和隐私清单不一致，审核前怎么查？",
    slug: "ios-sdk-tracking-permission-privacy-manifest-check",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "SDK 行为、ATT 弹窗、隐私清单和隐私政策如果口径不一致，会影响审核、用户授权和后续数据可信度。",
    keywords: ["iOS SDK", "ATT", "隐私清单", "隐私政策", "数据追踪"],
    coverImage: "/insights/ios-privacy-disclosure-camera-photo-ai-sdk-fix.png",
    coverAlt: "iOS SDK 追踪权限、隐私清单和审核一致性检查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "应用集成了广告、统计、归因或 AI SDK，但权限弹窗、隐私清单、隐私政策和数据安全说明没有同步更新",
    audience: "有广告归因、订阅增长、AI 生成或第三方 SDK 的 iOS 团队",
    answer: "iOS SDK 追踪权限要与 ATT 弹窗、隐私清单、隐私政策和包体真实行为一致；上线前应逐个 SDK 核对数据用途、权限和第三方共享说明。",
    signals: ["新增 SDK 后隐私清单是否同步更新", "ATT 弹窗文案是否解释真实追踪用途", "隐私政策是否覆盖第三方 SDK 数据共享"],
    actions: ["列出 SDK、权限、数据类型和用途", "同步隐私清单、隐私政策和审核备注", "用抓包或 SDK 文档复核数据发送行为"],
    evidence: "证据口径来自 ADXJ 对 iOS 隐私披露、SDK 合规和广告归因项目的复盘。",
  },
  {
    title: "Google Play 目标 API 截止前，老包更新应该先改什么？",
    slug: "google-play-target-api-deadline-update-plan",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "目标 API 更新不能只改编译参数，还要复查权限、SDK、数据安全表单、崩溃和商店页说明。",
    keywords: ["Google Play 目标 API", "Android 更新", "SDK 合规", "数据安全表单", "老包更新"],
    coverImage: "/insights/google-play-old-app-update-target-api-sdk-fix.png",
    coverAlt: "Google Play 目标 API、老包更新和 SDK 合规排查示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "老包为了赶目标 API 截止时间只改构建配置，没有同步检查权限、SDK 行为、崩溃和数据披露",
    audience: "维护 Android 老包、工具应用、现金贷、SLOTS 和 AI 应用的出海团队",
    answer: "Google Play 目标 API 更新要同步检查权限、SDK、数据安全表单、Pre-launch 崩溃和商店页说明；只改 targetSdk 容易带来新崩溃和政策风险。",
    signals: ["targetSdk 更新后权限弹窗或后台行为是否变化", "第三方 SDK 是否支持新系统限制", "Pre-launch Report 是否出现新崩溃或隐私提示"],
    actions: ["建立 targetSdk 更新影响清单", "同步复测权限、登录、支付和核心路径", "更新数据安全表单和发布备注"],
    evidence: "证据口径来自 ADXJ 对 Google Play 老包更新、目标 API 和 SDK 合规项目的服务经验。",
  },
  {
    title: "Google Play 数据安全表单，SDK 版本变了要不要重新填？",
    slug: "google-play-data-safety-sdk-version-change",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "SDK 版本变化可能改变数据采集、共享和加密方式，数据安全表单要跟包体真实行为保持一致。",
    keywords: ["Google Play 数据安全", "SDK 版本", "Android 隐私", "数据共享", "上架合规"],
    coverImage: "/insights/google-play-data-safety-form-app-removal-fix.png",
    coverAlt: "Google Play 数据安全表单、SDK 版本变化和隐私合规示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "广告、统计、支付、归因或风控 SDK 升级后，团队没有同步复核数据安全表单和隐私政策",
    audience: "有 Android SDK 集成、广告变现、订阅支付或金融风控模块的出海团队",
    answer: "Google Play 数据安全表单应随 SDK 版本变化重新复核；只要数据类型、共享对象、用途或加密方式变化，就要同步更新表单和隐私政策。",
    signals: ["SDK Release Notes 是否提到新数据类型", "包体权限和网络请求是否发生变化", "隐私政策是否仍覆盖当前 SDK 行为"],
    actions: ["按 SDK 列表核对数据类型和用途", "更新数据安全表单、隐私政策和内部台账", "在发布前跑一次隐私与权限回归"],
    evidence: "证据口径来自 ADXJ 对 Google Play 数据安全表单、SDK 版本和应用下架修复的项目复盘。",
  },
  {
    title: "Android 封闭测试参与不足，会影响生产访问申请吗？",
    slug: "android-closed-testing-low-participation-production-risk",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "封闭测试不能只凑人数，测试时长、反馈质量、崩溃处理和真实使用记录都会影响生产访问判断。",
    keywords: ["Android 封闭测试", "Google Play 生产访问", "测试参与", "上架申请", "开发者账号"],
    coverImage: "/insights/google-play-closed-testing-production-access-fix.png",
    coverAlt: "Android 封闭测试、生产访问申请和测试反馈质量示意图",
    markets: ["southeast-asia", "us"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "封闭测试虽然邀请了测试用户，但真实使用、反馈记录、崩溃修复和版本迭代证据不足",
    audience: "新 Google Play 开发者账号、工具应用、AI 应用和 Android 出海团队",
    answer: "Android 封闭测试要证明真实用户参与、持续测试、反馈修复和稳定版本；参与不足或记录太薄，会增加生产访问申请被卡的风险。",
    signals: ["测试用户是否有连续使用和反馈", "崩溃、ANR 和关键路径是否被修复", "生产访问材料是否能说明测试过程"],
    actions: ["整理测试用户、版本、反馈和修复记录", "补齐核心路径测试和崩溃处理证据", "用清晰时间线提交生产访问申请"],
    evidence: "证据口径来自 ADXJ 对 Google Play 封闭测试、生产访问和新开发者账号服务的复盘。",
  },
  {
    title: "Google Play 政策警告重复出现，申诉前要先做什么？",
    slug: "google-play-policy-strike-repeat-appeal-plan",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "重复政策警告说明问题可能存在于包体、商店页、权限、账号资产或历史版本，申诉前要做全链路复盘。",
    keywords: ["Google Play 政策警告", "Android 申诉", "应用下架", "开发者账号风控", "政策违规"],
    coverImage: "/insights/google-play-association-risk-checklist.png",
    coverAlt: "Google Play 政策警告、申诉材料和账号风险复盘示意图",
    markets: ["southeast-asia", "us"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "团队多次收到相近政策警告，却只改表层文案，没有排查历史包、SDK、权限、账号和域名关联",
    audience: "遇到 Google Play 下架、政策警告、账号受限或申诉不通过的 Android 团队",
    answer: "Google Play 政策警告重复出现时，先复盘违规条款、历史版本、SDK、权限、商店页和账号资产，再准备申诉材料；不要直接重复提交同类版本。",
    signals: ["警告是否来自同一政策类别", "历史版本是否仍保留问题功能或素材", "账号、域名、SDK 是否与旧违规资产关联"],
    actions: ["建立违规条款和版本修改时间线", "排查包体、商店页、隐私政策和账号资产", "用证据说明已修复内容和预防机制"],
    evidence: "证据口径来自 ADXJ 对 Google Play 政策警告、账号风控和申诉材料的服务复盘。",
  },
  {
    title: "Meta 广告学习受限，是事件量不够还是结构太碎？",
    slug: "meta-ads-campaign-learning-limited-event-volume-fix",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "学习受限通常不只是预算问题，事件量、广告组拆分、受众重叠、素材数量和转化窗口都会影响模型学习。",
    keywords: ["Meta 学习受限", "广告组结构", "事件量", "转化优化", "Facebook 投放"],
    coverImage: "/insights/meta-ads-learning-phase-restart-budget-event-fix.png",
    coverAlt: "Meta 广告学习受限、事件量和广告结构优化示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告组拆得太细、事件太少、预算不集中或素材迭代太频繁，导致系统长期无法稳定学习",
    audience: "正在做 Meta 订阅 App、工具应用、AI 应用和 DTC 落地页投放的团队",
    answer: "Meta 学习受限要先看转化事件量、广告组结构、预算集中度和素材更换频率；事件不足时应合并结构、放宽受众或换更靠前事件。",
    signals: ["每个广告组是否有足够目标事件", "预算是否被过多广告组分散", "素材和落地页是否频繁大改重启学习"],
    actions: ["合并低事件量广告组和重复受众", "选择能稳定回传的优化事件", "按素材主题建立小步测试节奏"],
    evidence: "证据口径来自 ADXJ 对 Meta Ads 学习期、事件回传和广告结构复盘的投放经验。",
  },
  {
    title: "Meta BM 验证、域名和支付风险，会不会拖累新账户放量？",
    slug: "meta-ads-bm-verification-domain-payment-risk",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "BM 主体、域名验证、支付方式和主页信任度共同影响账户稳定，新账户放量前要先做资产体检。",
    keywords: ["Meta BM 验证", "域名验证", "支付风险", "广告账户稳定", "账户风控"],
    coverImage: "/insights/meta-ads-account-restriction-audit.png",
    coverAlt: "Meta BM 验证、域名、支付方式和账户风控排查示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "新 BM、新域名、新支付方式和低信任主页同时上线，容易让广告账户在放量前就进入风险观察",
    audience: "准备新开 Meta 广告账户、换域名、换主体或重新放量的出海团队",
    answer: "Meta 新账户放量前要检查 BM 验证、域名归属、支付稳定、主页内容和落地页合规；基础资产不稳时，预算越急越容易触发限制。",
    signals: ["BM 主体和域名是否已完成验证", "支付方式是否频繁失败或更换", "主页和落地页是否有完整品牌与联系方式"],
    actions: ["先完成 BM、域名和像素基础配置", "补齐主页内容、隐私政策和客服入口", "用小预算稳定跑出正常审核与扣费记录"],
    evidence: "证据口径来自 ADXJ 对 Meta BM 风控、域名验证和广告账户稳定性的内部服务复盘。",
  },
  {
    title: "Meta 素材频次升高 CPA 上涨，什么时候该换创意？",
    slug: "meta-ads-creative-fatigue-frequency-cpa-rise",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "素材疲劳要结合频次、CTR、CVR、CPA、评论反馈和地区分层判断，不能只看单日成本波动。",
    keywords: ["Meta 素材疲劳", "广告频次", "CPA 上涨", "创意测试", "素材迭代"],
    coverImage: "/insights/meta-ads-ai-companion-creative-risk.png",
    coverAlt: "Meta 素材疲劳、频次升高和 CPA 上涨诊断示意图",
    markets: ["us", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "素材在同一受众和地区反复曝光，频次升高后点击率下降、负反馈增加，最终推高 CPA",
    audience: "投放 AI 应用、SLOTS、工具订阅、现金贷和内容产品的增长团队",
    answer: "Meta 素材频次升高且 CTR、CVR 同时下滑时，通常需要换角度而不是只调预算；应按地区、人群和卖点分层判断创意疲劳。",
    signals: ["频次升高是否伴随 CTR 和 CVR 下滑", "评论区负反馈和隐藏广告是否增加", "不同地区是否出现同一素材衰退"],
    actions: ["按卖点、场景和地区拆素材复盘", "保留胜出结构但替换开头、证明和 CTA", "把疲劳素材转入再营销或低预算测试组"],
    evidence: "证据口径来自 ADXJ 对 Meta 创意疲劳、频次控制和 CPA 波动复盘的投放经验。",
  },
  {
    title: "Meta CAPI 和 Pixel 重复计数，ROAS 还能看吗？",
    slug: "meta-capi-deduplication-pixel-server-events",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Pixel 和 CAPI 同时回传时，如果 event_id、金额、币种和时间戳不一致，可能造成重复计数和 ROAS 失真。",
    keywords: ["Meta CAPI", "Pixel 去重", "event_id", "ROAS 失真", "事件回传"],
    coverImage: "/insights/meta-pixel-capi-event-tracking-roas-fix.png",
    coverAlt: "Meta CAPI、Pixel 去重和 ROAS 事件回传排查示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "浏览器端和服务端同时发送购买、订阅或注册事件，但缺少统一 event_id 和金额币种校验",
    audience: "使用 Meta Pixel、CAPI、订阅事件和服务器回传的 App 或落地页团队",
    answer: "Meta CAPI 与 Pixel 要用一致的 event_id 做去重，并核对金额、币种、时间戳和事件名；否则 ROAS 可能被重复计数或低估。",
    signals: ["Events Manager 是否提示去重率低", "购买事件数量是否明显高于后台订单", "金额、币种或事件时间是否不一致"],
    actions: ["统一前后端 event_id 生成规则", "抽样比对广告后台、支付后台和服务端日志", "修正事件名、金额、币种和时间戳"],
    evidence: "证据口径来自 ADXJ 对 Meta Pixel/CAPI、订阅购买事件和 ROAS 归因项目的复盘。",
  },
  {
    title: "TikTok Ads 点击率高但安装低，是商店页没接住吗？",
    slug: "tiktok-ads-high-ctr-low-install-store-page-fix",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 素材点击率高不代表安装会好，商店页截图、评分、首屏卖点和素材承诺必须保持一致。",
    keywords: ["TikTok Ads", "点击率高安装低", "商店页转化", "素材承诺", "App 安装"],
    coverImage: "/insights/tiktok-ads-ai-tools-no-conversion.png",
    coverAlt: "TikTok Ads 点击率高安装低、商店页承接和素材承诺示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "短视频素材讲的是强结果和即时利益，但用户跳到商店页后看不到同一功能、同一场景和可信证明",
    audience: "投放 TikTok 的 AI 工具、订阅 App、游戏、SLOTS 和工具类出海团队",
    answer: "TikTok 点击率高但安装低时，应先检查素材承诺、商店页首屏、评分评论和落地页一致性；商店页接不住，继续加预算只会放大流失。",
    signals: ["CTR 高但商店页到安装转化低", "素材钩子在前三张截图中找不到", "评论或评分是否削弱用户信任"],
    actions: ["把素材核心承诺同步到商店页首屏", "用截图、短描述和评论证明强化可信度", "分市场测试截图顺序和首屏卖点"],
    evidence: "证据口径来自 ADXJ 对 TikTok Ads、App Store/Google Play 商店页转化和安装漏斗的投放复盘。",
  },
  {
    title: "TikTok SPC 广泛定向跑不稳，CPA 怎么控？",
    slug: "tiktok-spc-broad-targeting-cpa-control",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "SPC 广泛定向依赖事件质量、素材分层和预算节奏，CPA 波动时要先查信号而不是立刻收窄人群。",
    keywords: ["TikTok SPC", "广泛定向", "CPA 控制", "智能投放", "事件优化"],
    coverImage: "/insights/tiktok-smart-performance-campaign-ai-tool-event-fix.png",
    coverAlt: "TikTok SPC 广泛定向、CPA 控制和事件优化示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "团队把 SPC 当作自动放量工具，却没有保证事件回传、素材池质量、地区分层和预算变化节奏",
    audience: "用 TikTok SPC 跑订阅、AI 工具、电商落地页和 App 安装的增长团队",
    answer: "TikTok SPC 广泛定向不稳时，要先看事件质量、素材池、预算调整和地区结构；事件噪声大时，收窄人群往往治标不治本。",
    signals: ["优化事件是否稳定且足量", "不同素材是否承接同一用户意图", "预算调整是否频繁打断学习"],
    actions: ["清理低质量或错位事件", "按场景建立素材池并保留胜出方向", "用分阶段预算节奏控制 CPA 波动"],
    evidence: "证据口径来自 ADXJ 对 TikTok SPC、事件优化和订阅 App 放量项目的服务复盘。",
  },
  {
    title: "TikTok AI 视频模板夸张承诺，会不会触发素材拒审？",
    slug: "tiktok-ads-ai-video-template-claim-risk",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "AI 视频模板素材如果夸大结果、误导前后对比或暗示不可验证收益，容易触发审核和低质流量问题。",
    keywords: ["TikTok AI 视频", "素材拒审", "AI 模板", "夸张承诺", "广告审核"],
    coverImage: "/insights/tiktok-ads-ai-video-creative-testing.png",
    coverAlt: "TikTok AI 视频模板、素材承诺和广告审核风险示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "素材把 AI 视频模板包装成确定性结果或过度前后对比，用户点击后发现真实效果需要输入、等待和付费",
    audience: "投放 AI 视频、AI 图片、AI 头像、AI 伴侣和创作工具的团队",
    answer: "TikTok AI 视频素材要避免夸张承诺、误导前后对比和不可验证效果；更稳的做法是展示真实模板流程、输入条件和输出边界。",
    signals: ["素材是否承诺固定收益或过度效果", "落地页是否说明生成条件和限制", "拒审或负反馈是否集中在误导性表达"],
    actions: ["把强承诺改成真实场景演示", "补充生成步骤、限制和示例结果", "用多套安全钩子测试点击与转化"],
    evidence: "证据口径来自 ADXJ 对 TikTok AI 视频素材、广告拒审和订阅转化项目的复盘。",
  },
  {
    title: "TikTok 达人白名单素材授权，投放前要查哪些风险？",
    slug: "tiktok-creator-whitelist-usage-rights-audit",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "达人白名单素材要明确授权范围、投放地区、使用时长、剪辑权限和素材下架机制，避免爆量后停跑。",
    keywords: ["TikTok 达人白名单", "Spark Ads", "素材授权", "UGC 投放", "使用权"],
    coverImage: "/insights/tiktok-creator-creative-authorization-ugc-ads-fix.png",
    coverAlt: "TikTok 达人白名单、UGC 素材授权和投放风险排查示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "团队拿到达人授权后直接放量，却没有确认使用期限、地区、剪辑方式、账号绑定和素材撤回规则",
    audience: "使用 TikTok Creator、Spark Ads、UGC 素材和达人合作的出海团队",
    answer: "TikTok 达人白名单投放前要确认授权期限、地区、剪辑权限、账号绑定和撤回机制；授权不清时，爆款素材可能随时停跑。",
    signals: ["授权码和使用期限是否明确", "素材是否允许二剪、配音和多地区投放", "达人账号状态是否稳定且可追溯"],
    actions: ["用授权表记录达人、素材、地区和期限", "提前准备替代素材和续授权节点", "把投放数据与达人素材 ID 绑定复盘"],
    evidence: "证据口径来自 ADXJ 对 TikTok UGC、Spark Ads 授权和达人素材放量项目的服务经验。",
  },
  {
    title: "Telegram Bot 欢迎语怎么写，才能提高咨询转化？",
    slug: "telegram-ads-bot-welcome-message-conversion",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Bot 欢迎语不是寒暄文案，要在 10 秒内说明服务对象、可解决问题、下一步按钮和人工承接入口。",
    keywords: ["Telegram Bot", "欢迎语", "咨询转化", "私域承接", "Telegram Ads"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Bot 欢迎语、咨询按钮和私域转化路径示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "广告点击进入 Bot 后，只看到泛泛欢迎语，没有问题分类、资料收集、人工入口和下一步动作",
    audience: "用 Telegram Ads、频道广告、社群导流和 Bot 承接咨询的出海团队",
    answer: "Telegram Bot 欢迎语要直接说明能解决什么问题、适合谁、点击哪个按钮和如何转人工；信息太泛会降低 Bot Start 后的咨询率。",
    signals: ["Bot Start 高但表单或人工咨询低", "用户是否在第一屏找不到服务入口", "按钮是否按问题类型而不是内部部门命名"],
    actions: ["重写第一屏欢迎语和问题分类按钮", "用 3-5 个字段收集高意图信息", "设置人工承接 SLA 和二次触达消息"],
    evidence: "证据口径来自 ADXJ 对 Telegram Bot、私域线索分流和社群承接项目的复盘。",
  },
  {
    title: "Telegram 频道买来的流量不信任，内容要怎么补证明？",
    slug: "telegram-channel-paid-traffic-content-trust-proof",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "付费流量进入频道后，需要看到案例、服务边界、团队身份、常见问题和真实互动，才更容易转成咨询。",
    keywords: ["Telegram 频道", "付费流量", "信任证明", "社群内容", "咨询转化"],
    coverImage: "/insights/telegram-community-customer-response-conversion-fix.png",
    coverAlt: "Telegram 频道付费流量、内容信任和咨询转化示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "频道长期只发广告和转发内容，用户从付费入口进来后无法判断团队能力、服务边界和真实案例",
    audience: "做 Telegram 频道广告、社群私域、出海服务和 CPA 流量承接的团队",
    answer: "Telegram 频道承接付费流量时，要补案例、服务边界、团队身份、FAQ 和互动证明；只发促销内容会降低信任和咨询率。",
    signals: ["频道新增用户多但私聊咨询少", "置顶内容是否说明服务和联系方式", "用户是否反复问同一类基础问题"],
    actions: ["设置置顶服务说明和案例索引", "每周发布问题型 FAQ 和复盘内容", "用 Bot 或人工把高意图用户导入咨询"],
    evidence: "证据口径来自 ADXJ 对 Telegram 频道内容、社群信任和付费流量承接的运营复盘。",
  },
  {
    title: "Telegram Bot 表单太长，为什么高意向线索也会流失？",
    slug: "telegram-bot-form-too-long-lead-dropoff",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "表单字段过多会让高意向用户在移动端中断，Bot 应该先收关键诊断字段，再由人工补充细节。",
    keywords: ["Telegram Bot 表单", "线索流失", "咨询转化", "高意向用户", "私域漏斗"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Bot 表单过长、高意向线索流失和人工承接示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "团队想一次收集所有资料，导致用户在 Bot 里填写过多字段，尚未进入人工沟通就已经退出",
    audience: "用 Telegram Bot 收集出海服务、广告开户、上架诊断和 CPA 合作线索的团队",
    answer: "Telegram Bot 表单应先收目标市场、产品类型、问题截图和联系方式等关键字段；表单太长会让高意向用户在人工承接前流失。",
    signals: ["表单打开率高但完成率低", "用户卡在截图、预算或详细说明字段", "人工跟进前缺少可判断优先级的信息"],
    actions: ["把表单压缩到 3-5 个必填字段", "把复杂资料改到人工阶段补充", "按问题类型自动分配销售或运营"],
    evidence: "证据口径来自 ADXJ 对 Telegram Bot 表单、线索评分和销售承接 SOP 的内部复盘。",
  },
  {
    title: "Telegram 全球社群需要多语言管理员 SOP 吗？",
    slug: "telegram-community-moderator-sop-global-users",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "多市场社群需要统一规则、语言模板、升级机制和客服时段，否则广告流量进入后容易失控。",
    keywords: ["Telegram 社群", "多语言运营", "管理员 SOP", "全球用户", "社群转化"],
    coverImage: "/insights/telegram-community-customer-response-conversion-fix.png",
    coverAlt: "Telegram 全球社群、多语言管理员 SOP 和内容规则示意图",
    markets: ["southeast-asia", "latam", "europe"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "社群覆盖多个市场，却没有统一欢迎、审核、违规处理、问题升级和客服时段，导致用户体验不稳定",
    audience: "面向东南亚、拉美、欧洲用户运营 Telegram 社群和私域客服的出海团队",
    answer: "Telegram 全球社群需要多语言管理员 SOP，覆盖欢迎语、群规、问题分类、违规处理、升级机制和客服时段，才能稳定承接广告流量。",
    signals: ["不同管理员回复口径不一致", "垃圾信息、争议和重复问题增加", "高意向用户等待时间过长"],
    actions: ["制定多语言欢迎语、群规和 FAQ", "设置问题升级和人工响应时限", "每周复盘违规、咨询和转化数据"],
    evidence: "证据口径来自 ADXJ 对 Telegram 社群运营、多语言客服和私域转化项目的经验。",
  },
  {
    title: "AI 伴侣 App 年龄门槛和内容安全，审核前怎么设置？",
    slug: "ai-companion-age-gate-content-safety-review",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 伴侣 App 要把年龄门槛、角色边界、举报入口、内容过滤和订阅说明放在审核前一起检查。",
    keywords: ["AI 伴侣", "年龄门槛", "内容安全", "App 审核", "AI 聊天"],
    coverImage: "/insights/ai-companion-ads-safe-creative-framework.png",
    coverAlt: "AI 伴侣 App 年龄门槛、内容安全和审核检查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "AI 伴侣产品强调情绪互动和角色体验，却没有清楚设置年龄提示、内容边界、举报入口和安全策略",
    audience: "做 AI 伴侣、AI 聊天、AI 角色和订阅社交应用的出海团队",
    answer: "AI 伴侣 App 审核前要设置年龄门槛、内容安全策略、角色边界、举报入口和订阅说明；安全路径不清会同时影响上架和投放。",
    signals: ["是否有年龄提示和敏感内容边界", "用户是否能举报或屏蔽不当回复", "商店页和产品内是否一致说明 AI 能力限制"],
    actions: ["补齐年龄门槛、举报入口和安全说明", "按角色类型设置回复边界和审核策略", "同步更新商店页、素材和订阅页"],
    evidence: "证据口径来自 ADXJ 对 AI 伴侣出海、内容安全和应用审核项目的服务复盘。",
  },
  {
    title: "AI 图片 App 风格太像竞品，会不会有版权和审核风险？",
    slug: "ai-image-app-style-copycat-ip-risk",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 图片 App 如果直接使用竞品风格、人物形象或品牌元素做卖点，可能影响审核、广告和用户信任。",
    keywords: ["AI 图片 App", "版权风险", "风格模仿", "内容审核", "图片生成"],
    coverImage: "/insights/ai-image-generation-content-safety-reporting-fix.png",
    coverAlt: "AI 图片 App 风格模仿、版权风险和内容安全示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "商店页、素材或模板名称借用了竞品、名人、影视 IP 或品牌风格，容易引发版权、审核和广告风险",
    audience: "做 AI 图片、AI 头像、AI 换脸、AI 海报和模板工具的出海团队",
    answer: "AI 图片 App 不应把竞品、名人、影视 IP 或品牌风格作为核心卖点；应改用原创模板、通用场景和清晰的版权/举报机制。",
    signals: ["模板名称是否包含品牌、名人或影视 IP", "用户生成内容是否有举报和删除入口", "广告素材是否暗示可复制特定作品或人物"],
    actions: ["清理高风险模板名和素材表达", "补充原创风格、版权说明和举报机制", "按市场审核商店截图和广告素材"],
    evidence: "证据口径来自 ADXJ 对 AI 图片生成、内容安全、广告审核和 IP 风险项目的复盘。",
  },
  {
    title: "AI 视频 App 导出水印和 Paywall，会影响订阅转化吗？",
    slug: "ai-video-app-watermark-export-paywall-conversion",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "水印、导出清晰度、生成速度和 Paywall 触发时机，都会影响 AI 视频用户是否愿意试用和订阅。",
    keywords: ["AI 视频 App", "水印", "Paywall", "订阅转化", "导出体验"],
    coverImage: "/insights/ai-video-app-subscription-conversion.png",
    coverAlt: "AI 视频 App 水印、导出体验和订阅转化优化示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "用户还没看到一次完整输出就被订阅墙拦住，或免费导出水印过重导致价值感和信任感下降",
    audience: "做 AI 视频、图生视频、模板剪辑和订阅创作工具的团队",
    answer: "AI 视频 App 的水印和 Paywall 要让用户先看到可验证结果，再说明付费后可去水印、提高清晰度或加速导出；过早拦截会降低转化。",
    signals: ["首次生成完成率是否低于预期", "用户是否在导出或 Paywall 前大量流失", "退款原因是否提到水印、清晰度或等待时间"],
    actions: ["让新用户先完成一次低门槛生成", "清楚展示免费和付费导出差异", "按市场测试 Paywall 触发点和权益表达"],
    evidence: "证据口径来自 ADXJ 对 AI 视频订阅、Paywall 触发和首日体验优化的项目复盘。",
  },
  {
    title: "AI 写作工具模板页能被 Google 收录吗？",
    slug: "ai-writing-tool-google-indexable-template-pages",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 写作模板页要有独立问题、直接答案、示例、FAQ、内链和可抓取正文，才更有机会被搜索和 AI 引用。",
    keywords: ["AI 写作工具", "模板页 SEO", "Google 收录", "GEO 优化", "AI 工具出海"],
    coverImage: "/insights/ai-writing-app-refund-rate-subscription-fix.png",
    coverAlt: "AI 写作工具模板页、Google 收录和 GEO 内容结构示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "模板页只有输入框、按钮或重复短文案，缺少搜索引擎和 AI 引擎可理解的独立正文",
    audience: "做 AI 写作、AI 简历、营销文案、邮件助手和内容生成工具的团队",
    answer: "AI 写作模板页可以被 Google 收录，但页面必须有独立搜索意图、可见正文、示例输出、FAQ、内链和 canonical；空模板页很难获得稳定曝光。",
    signals: ["模板页是否只有输入框没有正文", "不同模板是否标题和内容高度重复", "GSC 是否显示已发现但未编入索引"],
    actions: ["为高意图模板补直接答案和示例", "建立模板专题、相关模板和服务内链", "在 sitemap 与 llms-full 中保留重点模板入口"],
    evidence: "证据口径来自 ADXJ 对 AI 工具 SEO、模板页收录和 GEO 内容结构的内部复盘。",
  },
  {
    title: "SLOTS 软启动市场怎么选，先看 CPI 还是 LTV？",
    slug: "slots-soft-launch-market-selection-cpi-ltv",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 软启动不能只选低 CPI 地区，还要看支付成功率、首充、留存、LTV、合规和素材适配。",
    keywords: ["SLOTS 软启动", "市场选择", "CPI", "LTV", "买量回本"],
    coverImage: "/insights/slots-overseas-ua-cost-market-risk.png",
    coverAlt: "SLOTS 软启动市场选择、CPI、LTV 和支付风险示意图",
    markets: ["latam", "southeast-asia", "us"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "团队只按 CPI 选择测试地区，忽略支付通道、首充转化、留存、素材文化适配和政策风险",
    audience: "准备 SLOTS、iGaming、休闲博彩类产品软启动和买量测试的团队",
    answer: "SLOTS 软启动市场要同时看 CPI、首充、留存、LTV、支付成功率和合规风险；低 CPI 地区如果付费差，反而会拖慢回本判断。",
    signals: ["低 CPI 是否对应低首充和低留存", "支付成功率和退款投诉是否稳定", "素材是否适配当地文化和平台政策"],
    actions: ["按市场建立 CPI、首充、留存和 LTV 看板", "先小预算测试支付与素材承接", "用 Day1/Day7 数据决定是否扩大地区"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 软启动、买量回本和支付漏斗项目的投放复盘。",
  },
  {
    title: "SLOTS 首充 Bonus 条款不清，会不会带来投诉和退款？",
    slug: "slots-first-deposit-bonus-terms-clear",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "首充 Bonus 要把领取条件、流水要求、限制地区和有效期讲清楚，否则短期转化可能换来长期投诉。",
    keywords: ["SLOTS 首充", "Bonus 条款", "支付投诉", "退款风险", "用户信任"],
    coverImage: "/insights/slots-payment-funnel-dropoff-region-channel-fix.png",
    coverAlt: "SLOTS 首充 Bonus 条款、支付投诉和退款风险示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "素材和落地页强调高 Bonus，却没有清楚说明领取限制、流水要求、提现条件和有效期",
    audience: "运营 SLOTS、社交娱乐场、iGaming 和充值型游戏的出海团队",
    answer: "SLOTS 首充 Bonus 必须明确领取条件、流水要求、提现限制、地区限制和有效期；条款不清会增加投诉、退款和广告审核风险。",
    signals: ["首充后客服问题是否集中在 Bonus 规则", "退款或投诉是否提到误导性活动", "素材、落地页和应用内规则是否一致"],
    actions: ["重写 Bonus 条款并放到付款前可见位置", "同步素材、落地页和应用内活动说明", "按渠道追踪首充、投诉和退款"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 首充活动、支付投诉和素材合规项目的复盘。",
  },
  {
    title: "SLOTS Google Play 元数据怎么写，才不像高风险博彩？",
    slug: "slots-google-play-metadata-social-casino-risk",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 商店页要避免误导性真钱收益表达，清楚说明娱乐属性、年龄分级、地区限制和支付边界。",
    keywords: ["SLOTS Google Play", "商店页元数据", "Social Casino", "年龄分级", "上架风险"],
    coverImage: "/insights/slots-landing-page-store-page-mismatch-roi-fix.png",
    coverAlt: "SLOTS Google Play 商店页元数据、娱乐属性和上架风险示意图",
    markets: ["latam", "southeast-asia", "us"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "商店页标题、截图、短描述或活动文案暗示真钱收益，和应用实际娱乐属性或地区限制不一致",
    audience: "准备在 Google Play 上架或更新 SLOTS、Social Casino 和游戏类产品的团队",
    answer: "SLOTS Google Play 元数据要突出娱乐属性、年龄分级、地区限制和虚拟奖励边界，避免真钱收益、误导性 Bonus 和落地页不一致表达。",
    signals: ["商店页是否暗示可赚钱或提现", "年龄分级和目标地区是否匹配", "落地页、素材和商店页是否使用同一规则"],
    actions: ["清理高风险收益和提现表达", "同步年龄分级、地区限制和活动规则", "提交前复查截图、短描述和隐私政策"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 上架、商店页审核和投放落地页一致性的服务复盘。",
  },
  {
    title: "SLOTS Telegram VIP 社群怎么做，才能提升留存而不是制造风险？",
    slug: "slots-telegram-community-retention-vip-lifecycle",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS VIP 社群要围绕客服、活动解释、留存任务和合规边界运营，不能只用高刺激奖励拉活。",
    keywords: ["SLOTS Telegram", "VIP 社群", "用户留存", "私域运营", "活动规则"],
    coverImage: "/insights/telegram-private-traffic-community-conversion.png",
    coverAlt: "SLOTS Telegram VIP 社群、留存任务和风险边界示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "VIP 社群只推奖励和充值活动，没有客服解释、任务节奏、风险提示和用户分层",
    audience: "运营 SLOTS、iGaming、社交娱乐场和充值型游戏私域的团队",
    answer: "SLOTS Telegram VIP 社群应以客服、活动解释、留存任务和用户分层为核心，避免只靠刺激性奖励拉活；否则容易带来投诉和合规风险。",
    signals: ["社群互动是否只围绕充值奖励", "客服是否能解释 Bonus、提现和支付问题", "高价值用户是否有分层触达节奏"],
    actions: ["建立 VIP 分层、活动说明和客服 SOP", "把高风险奖励文案改成规则透明表达", "按留存、付费和投诉数据复盘社群质量"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 私域、Telegram 社群和充值用户留存项目的复盘。",
  },
  {
    title: "现金贷 APR 和费用披露，落地页该怎么写才不误导？",
    slug: "cash-loan-apr-fee-disclosure-landing-page",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷落地页要用清楚的 APR、费用、期限、逾期说明和示例，避免广告审核、投诉和低质线索问题。",
    keywords: ["现金贷 APR", "费用披露", "落地页合规", "金融广告", "贷款出海"],
    coverImage: "/insights/cash-loan-landing-page-fee-disclosure-ads-complaint-fix.png",
    coverAlt: "现金贷 APR、费用披露和落地页合规示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告和落地页只强调快速放款，却没有清楚展示 APR、费用、期限、逾期后果和示例计算",
    audience: "做现金贷、金融 App、信贷 Lead Form 和贷款落地页投放的团队",
    answer: "现金贷落地页要清楚展示 APR、费用、期限、还款示例、逾期说明和资质要求；模糊费用会增加广告拒审、投诉和低质线索。",
    signals: ["广告拒审是否指向费用或金融声明", "用户咨询是否反复问利率和还款金额", "首还逾期是否与渠道和文案有关"],
    actions: ["把 APR、费用和期限放到首屏附近", "用本地语言写清还款示例和逾期说明", "按渠道追踪线索质量和首还表现"],
    evidence: "证据口径来自 ADXJ 对现金贷广告、费用披露和首还质量复盘的服务经验。",
  },
  {
    title: "Google Play 个人贷款政策，现金贷 App 上架前要查什么？",
    slug: "cash-loan-google-play-personal-loan-policy-check",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷 App 上架前要检查资质、地区、贷款期限、费用披露、隐私权限和商店页承诺，避免政策风险。",
    keywords: ["Google Play 个人贷款", "现金贷 App", "上架政策", "贷款合规", "Android 金融"],
    coverImage: "/insights/cash-loan-app-ads-rejected-compliance-funnel-fix.png",
    coverAlt: "Google Play 个人贷款政策、现金贷 App 上架和披露检查示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "应用功能、商店页、隐私政策和实际贷款条件没有围绕目标国家的个人贷款政策进行一致披露",
    audience: "准备现金贷 App、金融科技 App 和贷款获客产品上架 Google Play 的团队",
    answer: "现金贷 App 上架 Google Play 前要核对个人贷款政策、目标地区资质、贷款期限、APR、费用、隐私权限和商店页承诺是否一致。",
    signals: ["目标国家是否允许当前贷款产品形态", "商店页是否披露 APR、期限和费用", "权限和数据安全表单是否与风控需求匹配"],
    actions: ["按国家整理资质和政策清单", "同步商店页、隐私政策和数据安全表单", "提交前复查权限、SDK 和贷款流程"],
    evidence: "证据口径来自 ADXJ 对现金贷 Google Play 上架、金融政策和 Android 权限合规项目的复盘。",
  },
  {
    title: "现金贷 Meta 广告被拒说信用承诺，素材要怎么改？",
    slug: "cash-loan-meta-ads-credit-claim-rejection",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "金融广告不能用保证获批、无条件放款、夸张额度等承诺，素材和落地页要用条件、资质和费用说明替代。",
    keywords: ["现金贷 Meta 广告", "信用承诺", "金融广告拒审", "贷款素材", "广告合规"],
    coverImage: "/insights/cash-loan-ad-risk-funnel-repayment.png",
    coverAlt: "现金贷 Meta 广告信用承诺、素材拒审和金融合规示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告素材使用快速获批、保证额度、无需条件或过度诱导点击的表达，落地页也缺少资质和费用说明",
    audience: "投放现金贷、金融 Lead、贷款 App 和信用产品的增长团队",
    answer: "现金贷 Meta 广告应避免保证获批、固定额度和无条件放款等信用承诺；要改成资质条件、费用披露、申请流程和风险提示。",
    signals: ["拒审原因是否指向误导性金融声明", "素材是否承诺结果而不是说明条件", "落地页是否有费用、期限和资质入口"],
    actions: ["替换保证性词汇和夸张额度表达", "补充申请条件、费用和还款示例", "把落地页与广告文案统一到合规口径"],
    evidence: "证据口径来自 ADXJ 对现金贷 Meta Ads、金融广告审核和落地页转化项目的复盘。",
  },
  {
    title: "现金贷渠道质量差，黑名单和首还数据怎么一起看？",
    slug: "cash-loan-risk-control-blacklist-channel-quality",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷渠道不能只看申请成本，要把黑名单命中、设备异常、首还率、逾期和渠道 SubID 放到一起判断。",
    keywords: ["现金贷渠道质量", "黑名单", "首还率", "渠道风控", "获客质量"],
    coverImage: "/insights/cash-loan-channel-high-applications-low-repayment-fix.png",
    coverAlt: "现金贷渠道质量、黑名单命中和首还率风控分析示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "渠道申请量看起来便宜，但黑名单、设备异常和首还表现不稳定，后端风险被低 CPA 掩盖",
    audience: "做现金贷获客、CPA 渠道、金融 Lead Form 和贷后风控的团队",
    answer: "现金贷渠道质量要把申请成本、黑名单命中、设备异常、首还率、逾期和 SubID 一起看；只看低 CPA 容易放大坏账。",
    signals: ["低 CPA 渠道是否伴随高黑名单命中", "首还率和逾期是否按 SubID 分化", "设备、IP、手机号和表单行为是否异常集中"],
    actions: ["建立渠道质量日报和 SubID 评分", "把首还、逾期和黑名单信号回传给买量端", "暂停低质来源并重新谈结算规则"],
    evidence: "证据口径来自 ADXJ 对现金贷渠道风控、首还数据和 CPA 获客质量的内部复盘。",
  },
  {
    title: "CPA Offer 落地页和广告承诺不一致，会影响转化和扣量吗？",
    slug: "cpa-offer-landing-page-message-match-conversion",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "CPA Offer 的广告承诺、落地页、表单和转化条件必须一致，否则会造成低 CVR、质量争议和扣量。",
    keywords: ["CPA Offer", "落地页一致性", "扣量争议", "转化率", "网盟投放"],
    coverImage: "/insights/cpa-offer-scaling-cap-pacing-quality-feedback-fix.png",
    coverAlt: "CPA Offer 落地页一致性、广告承诺和扣量争议示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "流量主素材承诺和广告主落地页条件不一致，用户点击后发现门槛、地区或奖励规则不同",
    audience: "做 CPA Offer、联盟广告、Lead Gen 和流量主变现的团队",
    answer: "CPA Offer 要保证广告承诺、落地页、表单字段和转化条件一致；不一致会降低 CVR，并引发质量争议、扣量和合作关系受损。",
    signals: ["点击到表单转化率是否异常低", "用户投诉是否集中在奖励或条件不符", "广告主扣量原因是否指向低质量或误导流量"],
    actions: ["统一素材、落地页和转化条件说明", "给流量主提供可用素材和禁止词表", "按 SubID 追踪 CVR、拒量和质量反馈"],
    evidence: "证据口径来自 ADXJ 对 CPA Offer、落地页一致性和扣量争议项目的复盘。",
  },
  {
    title: "CPA 网盟 Click Injection 信号怎么识别？",
    slug: "cpa-network-fraud-click-injection-signal",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Click Injection 通常表现为点击到安装时间异常短、来源集中、设备行为异常和转化质量偏低。",
    keywords: ["CPA 作弊", "Click Injection", "反作弊", "网盟质量", "归因异常"],
    coverImage: "/insights/overseas-cpa-traffic-fraud-detection-checklist.png",
    coverAlt: "CPA 网盟 Click Injection、归因异常和反作弊信号示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告主看到转化增长，但点击到安装时间、设备分布、留存和付费质量明显异常",
    audience: "管理 CPA 网盟、流量主、App 安装 Offer 和归因数据的团队",
    answer: "CPA Click Injection 要看点击到安装时间、来源集中度、设备行为、留存和付费质量；异常短 CTIT 和低质量后端数据是关键预警。",
    signals: ["CTIT 是否出现异常短时间峰值", "转化是否集中在少数 SubID 或设备环境", "留存、付费或首日行为是否显著偏低"],
    actions: ["按 SubID、设备和 CTIT 建立异常报表", "暂停高风险来源并保留日志证据", "更新反作弊规则和结算扣量口径"],
    evidence: "证据口径来自 ADXJ 对 CPA 反作弊、归因异常和流量主质量审计的内部复盘。",
  },
  {
    title: "CPA 流量主 Day0 和周结怎么选，现金流风险谁承担？",
    slug: "cpa-publisher-payment-terms-day0-weekly-risk",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Day0 能吸引流量主，但广告主要用质量阈值、预留款、扣量规则和数据延迟保护现金流。",
    keywords: ["CPA Day0", "周结", "流量主结算", "现金流风险", "质量阈值"],
    coverImage: "/insights/publisher-day0-settlement-advertiser-quality-thresholds.png",
    coverAlt: "CPA 流量主 Day0、周结、质量阈值和现金流风险示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "为了抢量给出过快结算，却没有质量阈值、拒量周期、预留款和异常来源处理机制",
    audience: "做 CPA 网盟、Offer 招募、流量主变现和广告主结算管理的团队",
    answer: "CPA Day0 适合成熟且质量稳定的流量主；新来源更适合周结或阶梯结算，并配合质量阈值、预留款和扣量规则控制现金流风险。",
    signals: ["新流量主是否缺少历史质量数据", "广告主回传是否存在延迟和拒量周期", "结算速度是否快于质量验证速度"],
    actions: ["按来源等级设置 Day0、周结和预留比例", "明确拒量、补量和异常处理规则", "用质量阈值决定是否提高结算速度"],
    evidence: "证据口径来自 ADXJ 对 CPA Day0 结算、流量主质量和广告主现金流管理的服务经验。",
  },
  {
    title: "CPA Postback 上线前，S2S 测试清单怎么做？",
    slug: "cpa-postback-server-to-server-test-checklist",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "S2S Postback 要测试 click_id、event、payout、currency、去重、失败重试和日志留存，避免上线后丢转化。",
    keywords: ["CPA Postback", "S2S 测试", "click_id", "转化回传", "网盟技术"],
    coverImage: "/insights/publisher-api-integration-lost-conversions-postback-audit.png",
    coverAlt: "CPA Postback S2S 测试、转化回传和日志排查示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "Postback 只做了一次简单联调，没有覆盖参数缺失、重复转化、失败重试、币种和多事件回传",
    audience: "接入 CPA Offer、广告主 API、流量主平台和归因系统的技术与运营团队",
    answer: "CPA S2S Postback 上线前要测试 click_id、event、payout、currency、去重、失败重试和日志留存；联调不完整会导致丢量和结算争议。",
    signals: ["测试转化是否能在双方后台一致出现", "失败回调是否有重试和错误日志", "重复点击或重复事件是否能正确去重"],
    actions: ["建立 Postback 参数和事件测试表", "保留请求、响应、错误和重试日志", "上线后按小时比对双方转化差异"],
    evidence: "证据口径来自 ADXJ 对 CPA Postback、API 联调和转化丢失排查项目的复盘。",
  },
  {
    title: "ASO iOS 关键词字段，本地化优先级应该怎么排？",
    slug: "aso-ios-keyword-field-localization-priority",
    category: "开发者出海",
    topic: "aso",
    excerpt: "iOS 关键词字段要按市场搜索意图、转化概率、竞争强度和买量素材同步度排序，不能只塞高热词。",
    keywords: ["ASO iOS 关键词", "本地化", "App Store 排名", "关键词字段", "自然量增长"],
    coverImage: "/insights/aso-localization-keywords-us-sea-latam-case.png",
    coverAlt: "ASO iOS 关键词字段、本地化优先级和自然量增长示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "团队把关键词字段堆满高热词，却没有区分目标市场语言、用户意图、转化率和买量素材承接",
    audience: "做 App Store ASO、本地化、订阅工具、AI 应用和自然量增长的团队",
    answer: "iOS ASO 关键词字段要按市场、搜索意图、竞争强度、转化概率和买量素材同步度排序；高热词不一定比长尾意图词更有效。",
    signals: ["关键词曝光高但页面转化低", "不同市场是否共用同一套关键词", "买量素材卖点是否与 ASO 词不一致"],
    actions: ["按市场拆核心词、功能词和场景词", "用评论、竞品和广告词补长尾意图", "每次更新后跟踪曝光、排名和转化"],
    evidence: "证据口径来自 ADXJ 对 ASO 本地化、关键词字段和自然量增长项目的服务复盘。",
  },
  {
    title: "Google Play 商店实验样本太少，能判断 ASO 结果吗？",
    slug: "aso-google-play-store-listing-experiment-sample-size",
    category: "开发者出海",
    topic: "aso",
    excerpt: "商店实验要看样本量、流量来源、国家、实验时长和转化差异，样本太少时不要急着改全量素材。",
    keywords: ["Google Play 商店实验", "ASO 测试", "样本量", "转化率", "Store Listing Experiment"],
    coverImage: "/insights/app-launch-no-organic-traffic-aso.png",
    coverAlt: "Google Play 商店实验、ASO 样本量和转化判断示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "实验只跑了很短时间或少量访问，就依据单日波动替换截图、标题和短描述",
    audience: "做 Google Play ASO、素材测试、自然量增长和买量协同的 Android 团队",
    answer: "Google Play 商店实验样本太少时，不能直接判断 ASO 胜负；要结合流量来源、国家、实验时长、置信度和安装转化差异一起看。",
    signals: ["实验访问量是否足够支撑判断", "买量流量和自然流量是否混在一起", "胜出版本是否在多个国家稳定有效"],
    actions: ["按国家和流量来源拆分实验解读", "延长测试周期或缩小变量范围", "只把稳定胜出素材推到全量"],
    evidence: "证据口径来自 ADXJ 对 Google Play 商店实验、ASO 图片测试和自然量增长复盘的项目经验。",
  },
  {
    title: "订阅 App 评论情绪里，哪些词最值得拿来做 ASO？",
    slug: "aso-subscription-app-review-sentiment-mining",
    category: "开发者出海",
    topic: "aso",
    excerpt: "订阅 App 的评论能反映用户真实任务、付费阻力和功能词，适合反向指导标题、截图和 FAQ。",
    keywords: ["订阅 App ASO", "评论情绪", "关键词挖掘", "App Store 评论", "自然量"],
    coverImage: "/insights/app-launch-no-organic-traffic-aso.png",
    coverAlt: "订阅 App 评论情绪、关键词挖掘和 ASO 优化示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "团队只看竞品标题和工具热度，却忽略真实评论里的任务词、抱怨词、付费词和本地化表达",
    audience: "运营订阅 App、AI 工具、效率应用、内容会员和本地化 ASO 的团队",
    answer: "订阅 App 评论里的任务词、付费阻力词、替代方案词和情绪词最值得进入 ASO；它们能帮助标题、截图和 FAQ 更贴近真实搜索意图。",
    signals: ["评论是否反复提到同一任务或痛点", "差评是否集中在价格、取消或功能落差", "本地用户是否使用不同于后台关键词的表达"],
    actions: ["按好评、差评和竞品评论提取词表", "把高频任务词映射到标题、截图和描述", "用 FAQ 回答价格、取消和功能边界"],
    evidence: "证据口径来自 ADXJ 对订阅 App ASO、评论挖掘和关键词本地化项目的复盘。",
  },
  {
    title: "品牌词被竞品买走，ASO 和广告要怎么一起防守？",
    slug: "aso-brand-keyword-protection-paid-organic-sync",
    category: "开发者出海",
    topic: "aso",
    excerpt: "品牌词防守要同时看自然排名、搜索广告、评论口碑、竞品标题和落地页，不能只靠单一买量。",
    keywords: ["品牌词保护", "ASO 防守", "搜索广告", "竞品关键词", "自然量"],
    coverImage: "/insights/brand-keyword-defense-overseas-seo-ads-strategy.png",
    coverAlt: "品牌词保护、ASO 自然量和搜索广告协同防守示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "竞品购买或占用品牌相关搜索词后，用户在商店和搜索结果页被分流，品牌自然量和付费转化同时受影响",
    audience: "已有品牌搜索量、买量沉淀和竞品拦截风险的 App 出海团队",
    answer: "品牌词防守要同步做 ASO、搜索广告、评论口碑、官网 SEO 和商店页一致性；只买广告不补自然信号，长期成本会越来越高。",
    signals: ["品牌词排名是否被竞品或相似词稀释", "搜索广告是否保护核心品牌词", "评论和截图是否强化官方身份"],
    actions: ["建立品牌词、竞品词和误拼词监控", "同步优化商店页、官网页和搜索广告", "用评论、截图和客服入口强化官方可信度"],
    evidence: "证据口径来自 ADXJ 对品牌词防守、ASO 和搜索广告协同项目的服务复盘。",
  },
];

export const dailySeoArticles20260701: InsightArticle[] = seeds.map(dailyGeoArticle);
