import type { GeoMarketSlug } from "@/lib/geo-content";
import type { InsightArticle, InsightCategory } from "./articles";
import type { InsightTopicSlug } from "./topics";

type DailyGeoSeed = {
  title: string;
  slug: string;
  category: InsightCategory;
  topic: InsightTopicSlug;
  excerpt: string;
  keywords: string[];
  coverImage: string;
  coverAlt: string;
  markets: GeoMarketSlug[];
  serviceName: string;
  servicePath: string;
  problem: string;
  audience: string;
  answer: string;
  signals: string[];
  actions: string[];
  evidence: string;
};

const publishedAt = "2026-06-30";

const relatedByTopic: Record<InsightTopicSlug, string[]> = {
  "app-store": [
    "app-store-subscription-price-increase-review-risk",
    "ios-review-demo-account-2fa-login-fix",
    "ios-app-privacy-nutrition-label-sdk-mismatch",
  ],
  "google-play": [
    "google-play-policy-declaration-sensitive-permissions",
    "android-app-update-rejected-sdk-data-sharing",
    "google-play-pre-launch-report-crash-fix",
  ],
  "meta-ads": [
    "meta-ads-low-quality-ranking-creative-fix",
    "meta-advantage-plus-budget-scaling-after-learning",
    "meta-capi-event-match-quality-improvement",
  ],
  "tiktok-ads": [
    "tiktok-ads-low-cvr-creative-hook-offer-fix",
    "tiktok-spc-value-optimization-subscription-app",
    "tiktok-ads-policy-rejected-ai-before-after",
  ],
  telegram: [
    "telegram-channel-ad-clicks-low-bot-start-rate",
    "telegram-bot-lead-scoring-sales-handoff",
    "telegram-private-domain-retention-after-first-contact",
  ],
  "ai-apps": [
    "ai-companion-user-safety-review-checklist",
    "ai-image-app-prompt-abuse-content-moderation",
    "ai-video-subscription-paywall-conversion-fix",
  ],
  slots: [
    "slots-new-region-soft-launch-kpi-checklist",
    "slots-payment-success-rate-channel-routing",
    "slots-roas-drop-after-scale-region-segmentation",
  ],
  "cash-loan": [
    "cash-loan-privacy-policy-permission-fee-alignment",
    "cash-loan-google-meta-ads-compliance-proof",
    "cash-loan-channel-fraud-signal-first-repayment",
  ],
  "cpa-network": [
    "cpa-offer-postback-delay-quality-dispute",
    "cpa-network-publisher-onboarding-risk-check",
    "affiliate-traffic-source-reporting-template",
  ],
  aso: [
    "aso-screenshot-message-match-subscription-keyword",
    "google-play-keyword-ranking-after-update-drop",
    "aso-review-keyword-sentiment-localization",
  ],
};

function dailyGeoArticle(seed: DailyGeoSeed): InsightArticle {
  const [firstSignal, secondSignal, thirdSignal] = seed.signals;
  const [firstAction, secondAction, thirdAction] = seed.actions;

  return {
    title: seed.title,
    slug: seed.slug,
    category: seed.category,
    excerpt: seed.excerpt,
    keywords: seed.keywords,
    coverImage: seed.coverImage,
    coverAlt: seed.coverAlt,
    publishedAt,
    lastReviewedAt: publishedAt,
    topic: seed.topic,
    markets: seed.markets,
    relatedSlugs: relatedByTopic[seed.topic],
    readTime: "7 分钟",
    answerSummary: seed.answer,
    faqs: [
      {
        question: `${seed.title} 的直接答案是什么？`,
        answer: seed.answer,
      },
      {
        question: "这篇内容为什么同时符合 SEO 和 GEO？",
        answer: `它用问题型标题承接搜索意图，用 80-120 字直接答案、FAQ、${seed.topic} 专题、市场标签、相关内链和 ${seed.serviceName} CTA 帮助搜索引擎理解页面，也让 AI 引擎更容易抽取可引用结论。`,
      },
      {
        question: "咨询 ADXJ 前应该准备哪些信息？",
        answer: `建议准备目标市场、产品类型、平台反馈截图、近 7 天数据、当前 URL、素材或包体版本和已尝试动作，再通过 Telegram @M7HHHH、微信 M7HHHH 或 business@adxj.com 发给 ADXJ。`,
      },
    ],
    evidenceNotes: [
      seed.evidence,
      `本文最近一次 GEO/SEO 复核日期为 ${publishedAt}，用于补充今日高意图问题、专题内链、市场标签和 AI 可引用答案。`,
    ],
    content: [
      {
        heading: "直接答案和适用场景",
        paragraphs: [
          `${seed.answer} 这类问题不能只看一个后台提示，因为平台判断、用户信任、页面承诺和数据回传通常会一起影响结果。`,
          `${seed.problem} 对 ${seed.audience} 来说，最先要做的是把用户能看到的页面、平台能验证的材料、后台能追踪的数据放在同一条链路里排查。这样既能提高 SEO 页面点击后的阅读完整度，也能让 GEO 摘要抓到明确判断。`,
        ],
      },
      {
        heading: "先看三个判断信号",
        paragraphs: [
          `第一个信号是${firstSignal}。如果这个信号已经影响上架、消耗、收录、咨询、转化或回款，就应该当天处理，而不是等下一轮大版本。`,
          `第二个信号是${secondSignal}。它能帮助团队判断问题来自页面表达、平台信任、事件回传、素材承诺还是目标市场本身。第三个信号是${thirdSignal}，决定后续要补文案、补证据、补内链，还是进入 ${seed.serviceName} 诊断。`,
        ],
      },
      {
        heading: "ADXJ 建议的处理顺序",
        paragraphs: [
          `第一步，${firstAction}。这一步要保留截图、时间、URL、版本、事件名或审核反馈，后续才能把修复动作写成可复核的 FAQ 和直接答案。`,
          `第二步，${secondAction}。它直接影响 SEO 点击率和 GEO 可引用度，因为用户和 AI 都需要看到具体场景、判断依据和下一步。第三步，${thirdAction}，并把问题连接到 ${seed.serviceName}（${seed.servicePath}），让读者知道该准备什么资料、找谁处理、预期解决什么。`,
        ],
      },
      {
        heading: "如何沉淀成可转化内容",
        paragraphs: [
          `发布后，本文应进入 ${seed.topic} 专题、sitemap 和 llms-full 索引，并从至少三篇相近旧文获得内链。这样搜索用户能从问题页继续看到专题、服务页和类似案例，AI 引擎也能把 ADXJ 与这个问题建立稳定关联。`,
          `如果你的项目正在遇到类似情况，可以把地区、产品截图、后台数据、平台邮件或收录状态整理好，联系 ADXJ：Telegram @M7HHHH、微信 M7HHHH、邮箱 business@adxj.com。我们会按 ${seed.serviceName} 的处理路径给出诊断清单。`,
        ],
      },
    ],
  };
}

const seeds: DailyGeoSeed[] = [
  {
    title: "App Store 订阅页本地化没同步，会不会影响审核和转化？",
    slug: "app-store-review-subscription-screen-localization-mismatch",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "订阅页本地化如果价格、权益、试用和取消路径没有同步，会同时影响审核理解、用户信任和不同市场的付费转化。",
    keywords: ["App Store 订阅页", "本地化", "iOS 审核", "订阅转化", "取消路径"],
    coverImage: "/insights/app-store-subscription-review-price-trial-cancel-fix.png",
    coverAlt: "App Store 订阅页本地化、价格权益和审核转化排查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "订阅页中文、英文和目标市场语言没有同步，用户看到的权益、价格周期和取消说明可能互相矛盾",
    audience: "正在做 iOS 订阅、AI 工具、效率工具和内容类应用的出海团队",
    answer: "App Store 订阅页本地化要同步价格、周期、试用权益、自动续订和取消路径；如果不同语言版本口径不一致，应先修订商店页和订阅页再提交审核或放量。",
    signals: ["不同语言订阅页是否使用同一价格和权益口径", "商店截图与应用内 Paywall 是否表达一致", "目标市场退款和取消是否在本地化改版后上升"],
    actions: ["建立订阅页多语言口径对照表", "同步更新商店截图、Paywall 和审核备注", "按市场追踪试用、付费、取消和退款"],
    evidence: "证据口径来自 ADXJ 对 iOS 订阅本地化、Paywall 审核和退款反馈的服务复盘。",
  },
  {
    title: "iOS 更新后崩溃，TestFlight 没发现，审核前该怎么补测？",
    slug: "ios-app-update-crash-after-review-testflight-gap",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "TestFlight 没暴露的问题，可能在审核设备、地区配置、权限状态和远程开关里出现，更新前要补核心路径回归。",
    keywords: ["iOS 更新崩溃", "TestFlight", "App Store 审核", "核心路径测试", "iOS 回归测试"],
    coverImage: "/insights/app-store-review-72-hour-checklist.png",
    coverAlt: "iOS 更新后崩溃、TestFlight 和审核前回归测试示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "测试包覆盖了内部设备，却没有覆盖审核地区、低版本系统、权限拒绝和远程配置，导致更新审核或上线后崩溃",
    audience: "准备提交 App Store 更新包、AI 应用、订阅工具或敏感品类应用的团队",
    answer: "iOS 更新前要用审核路径做回归测试，覆盖登录、权限、订阅、核心功能、低系统版本和目标地区配置；TestFlight 通过不等于审核与线上路径安全。",
    signals: ["崩溃是否只在特定系统、地区或权限状态出现", "远程配置和审核账号是否与 TestFlight 一致", "核心功能是否依赖网络、订阅或第三方 SDK"],
    actions: ["建立审核前 72 小时核心路径测试表", "用目标市场设备和新账号复跑关键流程", "把已知风险和测试账号写入审核备注"],
    evidence: "证据口径来自 ADXJ 对 App Store 更新审核、TestFlight 回归和线上崩溃复盘的项目经验。",
  },
  {
    title: "App Store 内购元数据缺失，会不会导致订阅审核反复卡住？",
    slug: "app-store-in-app-purchase-missing-metadata-fix",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "内购名称、描述、截图和应用内展示如果缺失或不一致，审核员可能无法理解付费权益，订阅审核会反复卡住。",
    keywords: ["App Store 内购", "IAP 元数据", "订阅审核", "付费权益", "苹果审核"],
    coverImage: "/insights/app-store-subscription-review-price-trial-cancel-fix.png",
    coverAlt: "App Store 内购元数据、订阅权益和审核卡点示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "IAP 元数据和应用内 Paywall 没有说明同一组权益，审核员很难验证价格和功能边界",
    audience: "有订阅、消耗型内购或高级功能解锁的 iOS 出海团队",
    answer: "App Store 内购元数据要和应用内订阅页、商店截图、价格周期和权益说明一致；缺少截图或描述不清时，应先补全元数据再重新提交。",
    signals: ["审核反馈是否指向内购、订阅或付费权益不清", "IAP 名称描述是否和应用内 Paywall 一致", "付费前后功能边界是否能被审核员快速验证"],
    actions: ["逐项核对 IAP 名称、描述、截图和价格", "重写 Paywall 权益和取消路径说明", "用审核账号验证购买前后的功能边界"],
    evidence: "证据口径来自 ADXJ 对 App Store IAP 元数据、订阅审核和 Paywall 一致性的内部案例复盘。",
  },
  {
    title: "iOS 隐私政策链接打不开，审核会直接拒吗？",
    slug: "ios-app-review-guideline-privacy-policy-broken-link",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "隐私政策链接打不开或内容与包体不一致，可能直接影响审核和用户信任，提交前要检查可访问性、语言和数据口径。",
    keywords: ["iOS 隐私政策", "App Store 审核", "隐私链接", "数据披露", "苹果上架"],
    coverImage: "/insights/ios-privacy-disclosure-camera-photo-ai-sdk-fix.png",
    coverAlt: "iOS 隐私政策链接、数据披露和审核风险示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "隐私政策链接在海外网络、移动端或审核地区无法打开，或者没有覆盖当前 SDK 和权限行为",
    audience: "涉及用户数据、相机相册、定位、广告归因或 AI 上传处理的 iOS 应用团队",
    answer: "iOS 隐私政策链接必须稳定可访问，并覆盖数据收集、用途、第三方 SDK、用户删除和联系方式；提交前应从海外网络、移动端和审核账号路径逐项检查。",
    signals: ["隐私链接是否在海外网络和移动端可打开", "页面是否覆盖当前 SDK、权限和数据删除方式", "App Privacy 标签是否和隐私政策口径一致"],
    actions: ["检查隐私政策 URL、状态码和移动端展示", "同步更新数据收集、共享和删除说明", "把关键隐私入口写入审核备注和应用内设置"],
    evidence: "证据口径来自 ADXJ 对 iOS 隐私政策、App Privacy 标签和审核拒审反馈的服务经验。",
  },
  {
    title: "Google Play 数据删除链接无效，会影响账号信任吗？",
    slug: "google-play-data-deletion-url-not-working-fix",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "数据删除链接是 Google Play 数据安全和用户信任的重要入口，打不开或说明不清会影响审核、投诉和账号长期稳定。",
    keywords: ["Google Play 数据删除", "Data deletion", "数据安全表单", "Android 隐私", "账号信任"],
    coverImage: "/insights/google-play-data-safety-form-app-removal-fix.png",
    coverAlt: "Google Play 数据删除链接、数据安全表单和账号信任示意图",
    markets: ["southeast-asia", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "数据删除链接无法打开、没有说明删除范围，或和数据安全表单不一致，会让用户和平台无法验证隐私承诺",
    audience: "需要账号注册、用户数据、金融资料或 AI 上传内容的 Android 应用团队",
    answer: "Google Play 数据删除链接要稳定可访问，并清楚说明删除入口、处理范围、处理时效和联系方式；如果链接失效，应先修复页面再更新数据安全表单。",
    signals: ["数据删除 URL 是否返回 200 且移动端可读", "页面是否说明账号、内容、日志和第三方数据处理范围", "数据安全表单是否和删除页面口径一致"],
    actions: ["检查数据删除页面状态码和表单可用性", "补齐删除范围、时效和联系方式", "同步更新 Google Play 数据安全表单"],
    evidence: "证据口径来自 ADXJ 对 Google Play 数据安全、用户数据删除和隐私合规审核的项目复盘。",
  },
  {
    title: "Google Play 内容分级问卷填错，老包更新会被卡吗？",
    slug: "google-play-app-content-rating-questionnaire-risk",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "内容分级问卷要和真实功能、UGC、AI 输出、金融或游戏元素一致，老包更新时也可能被重新检查。",
    keywords: ["Google Play 内容分级", "Content Rating", "Android 更新", "AI 内容", "应用审核"],
    coverImage: "/insights/google-play-old-app-update-target-api-sdk-fix.png",
    coverAlt: "Google Play 内容分级问卷、老包更新和审核风险示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "产品增加 UGC、AI 生成、聊天、金融或游戏化功能后，内容分级仍沿用旧答案，可能造成审核和地区展示风险",
    audience: "准备更新 Google Play 老应用、AI 应用、游戏化工具和金融 App 的团队",
    answer: "Google Play 内容分级问卷要随产品功能更新，特别是 UGC、AI 输出、聊天、金融和游戏元素；老包更新前应重新核对问卷和商店页说明。",
    signals: ["新版本是否增加用户生成、聊天或敏感内容", "商店页截图是否展示与分级相关的新功能", "目标市场是否对金融、游戏或内容安全更敏感"],
    actions: ["按新功能重新填写内容分级问卷", "同步调整商店页、隐私政策和审核备注", "用目标市场设备检查分级展示和可用性"],
    evidence: "证据口径来自 ADXJ 对 Google Play 内容分级、老应用更新和敏感功能审核的服务经验。",
  },
  {
    title: "Android 通知权限弹窗转化低，会影响留存和审核吗？",
    slug: "android-notification-permission-opt-in-review",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "通知权限既影响留存，也影响用户信任；弹窗触发时机、文案和功能价值要解释清楚，避免被用户和平台误解。",
    keywords: ["Android 通知权限", "权限弹窗", "用户留存", "Google Play 权限", "通知 opt-in"],
    coverImage: "/insights/android-app-permission-review-camera-location-notification-fix.png",
    coverAlt: "Android 通知权限弹窗、留存和审核说明示意图",
    markets: ["southeast-asia", "us"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "应用一打开就索要通知权限，用户还没理解价值，授权率低且容易引发隐私和骚扰感知",
    audience: "依赖通知召回、订阅续费、金融还款提醒或社群消息的 Android 应用团队",
    answer: "Android 通知权限应在用户理解功能价值后触发，并说明提醒类型、频率和关闭方式；如果授权率低，要先改时机和文案，而不是继续加弹窗。",
    signals: ["通知授权率是否低于核心用户预期", "权限是否在用户完成关键动作前被请求", "通知内容是否和用户利益、还款或订阅提醒相关"],
    actions: ["把通知权限触发点移到价值确认后", "重写通知用途、频率和关闭方式说明", "用留存、打开率和投诉反馈评估效果"],
    evidence: "证据口径来自 ADXJ 对 Android 权限弹窗、通知留存和 Google Play 用户体验审核的内部复盘。",
  },
  {
    title: "Google Play 商店页用 AI 生成图，会不会影响信任和转化？",
    slug: "google-play-store-listing-ai-generated-assets-risk",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "AI 生成商店图可以提高产能，但如果和真实产品界面不一致，会影响审核判断、用户信任和下载后转化。",
    keywords: ["Google Play 商店页", "AI 生成素材", "商店转化", "应用截图", "Android ASO"],
    coverImage: "/insights/google-play-data-safety-form-app-removal-fix.png",
    coverAlt: "Google Play 商店页 AI 生成素材、截图一致性和转化风险示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "商店图过度美化或展示不存在的界面，会让用户安装后产生落差，也可能被平台理解为误导展示",
    audience: "用 AI 生成截图、视觉图和本地化素材的 Android 应用团队",
    answer: "Google Play 商店页可以使用 AI 生成辅助素材，但核心截图和功能承诺必须与真实应用一致；如果素材展示不存在的功能，应先替换为真实界面或明确说明。",
    signals: ["截图是否展示真实可访问功能", "下载后首屏是否能兑现商店页承诺", "用户评论是否出现被骗、功能不符或截图不实"],
    actions: ["区分真实界面截图和营销辅助图", "把前三张图改成可验证功能路径", "用下载到激活转化和差评内容验证素材质量"],
    evidence: "证据口径来自 ADXJ 对 Google Play 商店页、AI 生成素材和 ASO 转化复盘的服务经验。",
  },
  {
    title: "Meta 落地页质量差导致 CPA 上升，先查哪些页面信号？",
    slug: "meta-ads-landing-page-quality-score-cpa-rise",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta CPA 上升不一定是素材疲劳，落地页速度、首屏承诺、跳转链路和事件回传都会影响系统学习和用户转化。",
    keywords: ["Meta 落地页", "CPA 上升", "Facebook 广告", "落地页质量", "转化优化"],
    coverImage: "/insights/meta-ads-account-restriction-audit.png",
    coverAlt: "Meta 落地页质量、CPA 上升和页面信号排查示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告点击正常但 CPA 持续上升，说明落地页首屏、加载速度、跳转和事件质量可能没有承接住素材承诺",
    audience: "投放 Meta Ads、AI 工具、金融产品和订阅落地页的增长团队",
    answer: "Meta 落地页质量差导致 CPA 上升时，要先查加载速度、首屏承诺、CTA、跳转链路和 Pixel/CAPI 事件；页面信号未修复前不宜单纯加预算。",
    signals: ["点击率稳定但 CVR 和 CPA 变差", "首屏是否兑现广告素材里的利益点", "关键事件是否正确回传并能区分高意图用户"],
    actions: ["检查落地页速度、首屏和 CTA 一致性", "修复跳转、表单和事件回传断点", "用 A/B 页面对照 CPA、CVR 和线索质量"],
    evidence: "证据口径来自 ADXJ 对 Meta Ads 落地页、事件回传和 CPA 波动的投放复盘。",
  },
  {
    title: "Meta Advantage+ 人群重叠，怎么判断是不是自己抢自己？",
    slug: "meta-ads-advantage-plus-audience-overlap-fix",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "多个 Advantage+ 或自动化广告组同时跑相似素材和目标地区，可能出现预算互相竞争、频次上升和 CPA 变差。",
    keywords: ["Meta Advantage+", "人群重叠", "预算竞争", "CPA 优化", "广告组结构"],
    coverImage: "/insights/meta-advantage-plus-performance-drop-event-creative-fix.png",
    coverAlt: "Meta Advantage+ 人群重叠、预算竞争和广告组结构示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "同一产品同时开启多个相似自动化广告组，系统可能在同一地区和相似人群中互相抬价",
    audience: "使用 Meta Advantage+、自动化受众和多地区素材测试的投放团队",
    answer: "Meta Advantage+ 人群重叠要看地区、素材、事件、频次和 CPA 是否同步冲突；如果多个广告组互相竞争，应合并预算或明确分工测试变量。",
    signals: ["多个广告组在同一地区同时频次上升", "素材和落地页高度相似但 CPA 互相波动", "预算增加后总量没涨只是成本上升"],
    actions: ["梳理广告组目标、地区、素材和事件差异", "合并重复广告组或拆清测试变量", "按总账户 CPA 和增量转化判断结构是否有效"],
    evidence: "证据口径来自 ADXJ 对 Meta Advantage+ 账户结构、人群重叠和预算效率的投放复盘。",
  },
  {
    title: "Meta 金融广告被拒说收益承诺，素材要怎么改？",
    slug: "meta-ads-rejected-financial-claims-compliance",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "金融广告素材不能只强调快、稳、低门槛，要把费用、资格、风险提示和产品边界讲清楚，避免被判定误导承诺。",
    keywords: ["Meta 金融广告", "收益承诺", "金融广告拒审", "现金贷投放", "素材合规"],
    coverImage: "/insights/meta-ads-account-restricted-bm-landing-page-fix.png",
    coverAlt: "Meta 金融广告收益承诺、素材合规和拒审修复示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "素材强调快速放款、低成本或确定结果，却没有同步资格条件、费用和风险提示，会触发金融广告政策风险",
    audience: "投放现金贷、金融工具、分期和本地信贷产品的 Meta 团队",
    answer: "Meta 金融广告被拒涉及收益或放款承诺时，应把绝对化表达改成条件说明，并在素材和落地页补齐费用、资格、期限和风险提示。",
    signals: ["素材是否使用保证、最快、最低或无条件表达", "落地页是否清楚展示费用、期限和资格条件", "账户历史是否已有金融政策拒审记录"],
    actions: ["替换绝对化承诺和夸张利益点", "补齐费用、期限、资格和风险提示", "建立金融素材审核清单和申诉证据库"],
    evidence: "证据口径来自 ADXJ 对 Meta 金融广告、现金贷素材合规和账户拒审修复的服务经验。",
  },
  {
    title: "Meta Purchase 事件金额和币种错了，ROAS 会失真吗？",
    slug: "meta-pixel-capi-purchase-event-value-currency",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Purchase 事件 value 和 currency 配置错误，会让 ROAS、价值优化和预算决策都失真，尤其是多市场订阅和游戏充值。",
    keywords: ["Meta Purchase 事件", "value currency", "ROAS 失真", "Pixel CAPI", "价值优化"],
    coverImage: "/insights/meta-pixel-capi-event-tracking-roas-fix.png",
    coverAlt: "Meta Purchase 事件金额币种、ROAS 和价值优化排查示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "多币种、多价格档或订阅续费场景下，Purchase 事件金额和币种如果回传错误，系统会学习错误价值",
    audience: "用 Meta Pixel/CAPI 优化订阅、充值、SLOTS 或电商购买事件的投放团队",
    answer: "Meta Purchase 事件必须正确回传 value、currency、event_id 和订单状态；金额或币种错误时，ROAS 和价值优化都不可信，应先修事件再放量。",
    signals: ["后台收入和 Meta ROAS 是否差异异常", "不同市场币种是否被统一写成同一币种", "Pixel 和 CAPI 是否存在重复或漏传 Purchase"],
    actions: ["核对订单金额、币种和事件参数", "修复 Pixel/CAPI 去重和订单状态回传", "用小预算验证 ROAS 与后台收入一致性"],
    evidence: "证据口径来自 ADXJ 对 Meta Pixel/CAPI、Purchase 事件和多币种 ROAS 校准的技术复盘。",
  },
  {
    title: "TikTok Ads 花钱但学习不动，是事件量不够还是目标错了？",
    slug: "tiktok-ads-spend-no-learning-event-volume",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 广告有消耗但学习不动时，要先看事件量、事件质量、转化窗口、预算和素材是否足够支撑系统探索。",
    keywords: ["TikTok Ads 学习", "事件量", "TikTok 投放", "转化事件", "广告消耗"],
    coverImage: "/insights/tiktok-smart-performance-campaign-ai-tool-event-fix.png",
    coverAlt: "TikTok Ads 有消耗但学习不动、事件量和目标排查示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "广告持续花钱但转化事件不足，系统无法判断哪些用户值得继续探索，CPA 会越来越不稳定",
    audience: "投放 TikTok Ads、SPC、AI 工具、订阅 App 和 SLOTS 的增长团队",
    answer: "TikTok Ads 花钱但学习不动时，要先确认优化事件是否有足够样本；如果事件量不足，应下沉到注册、试用或关键行为，再逐步切回付费事件。",
    signals: ["近 7 天目标事件数量是否低于学习需求", "预算是否分散到过多广告组和素材", "转化窗口是否和产品真实决策周期匹配"],
    actions: ["检查安装、注册、试用和付费事件漏斗", "合并预算并减少低样本广告组", "用更稳定的中间事件重新启动学习"],
    evidence: "证据口径来自 ADXJ 对 TikTok Ads 事件学习、SPC 和订阅应用投放的账户复盘。",
  },
  {
    title: "TikTok Spark Ads 授权码过期，爆款素材还能继续跑吗？",
    slug: "tiktok-creator-spark-ads-code-expired-fix",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "Spark Ads 授权码过期会影响爆款素材续投、白名单管理和达人合作节奏，放量前要把授权和备份素材准备好。",
    keywords: ["TikTok Spark Ads", "授权码过期", "达人素材", "UGC 授权", "短视频投放"],
    coverImage: "/insights/tiktok-creator-creative-authorization-ugc-ads-fix.png",
    coverAlt: "TikTok Spark Ads 授权码过期、达人素材和续投管理示意图",
    markets: ["us", "southeast-asia", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "爆款素材依赖单个达人授权，授权码到期或权限变化后，广告组会突然失去关键素材承接",
    audience: "用 TikTok Spark Ads、达人 UGC 和白名单素材跑量的投放团队",
    answer: "TikTok Spark Ads 授权码过期前应提前续期，并准备备份素材、授权合同和白名单记录；爆款素材不能只依赖单个授权码继续放量。",
    signals: ["核心广告组是否依赖少数 Spark Ads 素材", "授权码、合同和投放地区是否快到期", "达人账号是否存在删除、限流或内容调整风险"],
    actions: ["建立达人素材授权到期表", "提前续期授权码并保存合同证据", "准备同角度备份素材和普通广告版本"],
    evidence: "证据口径来自 ADXJ 对 TikTok Spark Ads、达人授权和爆款素材续投风险的投放复盘。",
  },
  {
    title: "TikTok 投 AI 伴侣，哪些钩子更安全也更能转化？",
    slug: "tiktok-ads-ai-companion-policy-safe-hooks",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "AI 伴侣素材要避开擦边、敏感属性和不真实承诺，用陪伴场景、功能演示和用户控制感来表达价值。",
    keywords: ["TikTok AI 伴侣", "素材钩子", "AI 广告合规", "订阅转化", "内容安全"],
    coverImage: "/insights/tiktok-ads-ai-video-creative-testing.png",
    coverAlt: "TikTok AI 伴侣素材安全钩子、功能展示和订阅转化示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "AI 伴侣素材如果只靠暧昧、夸张陪伴或敏感人群表达，容易被审核卡住，也会吸引低质量点击",
    audience: "投放 AI 伴侣、AI 聊天、角色互动和订阅应用的 TikTok 团队",
    answer: "TikTok AI 伴侣素材应优先使用安全场景、功能演示、角色记忆和用户控制感作为钩子，避免擦边承诺和敏感属性表达。",
    signals: ["素材是否暗示不适当关系或敏感身份", "落地页是否能证明角色记忆和聊天功能真实存在", "高点击素材是否带来低订阅和高退款"],
    actions: ["建立安全钩子和禁用表达清单", "用功能演示替代擦边结果承诺", "按订阅率和退款率筛选素材方向"],
    evidence: "证据口径来自 ADXJ 对 TikTok AI 伴侣素材、政策拒审和订阅转化的项目复盘。",
  },
  {
    title: "TikTok 评论区负反馈变多，会不会拖累转化？",
    slug: "tiktok-ads-comment-negative-feedback-conversion",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "评论区负反馈不仅影响用户信任，也会暴露素材承诺、价格、功能和客服承接问题，放量前要纳入优化。",
    keywords: ["TikTok 评论区", "负反馈", "广告转化", "评论管理", "素材优化"],
    coverImage: "/insights/tiktok-creative-fatigue-ai-video-signals.png",
    coverAlt: "TikTok 评论区负反馈、素材承诺和转化影响示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "素材下方集中出现价格、功能不符、无法取消或体验差的评论，会让新用户在点击前就降低信任",
    audience: "用 TikTok 做订阅 App、AI 工具、SLOTS 和现金贷投放的团队",
    answer: "TikTok 评论区负反馈变多时，要把评论按价格、功能、信任和客服问题分类；如果负反馈集中，应先修素材和落地页承诺再继续放量。",
    signals: ["负面评论是否集中在少数素材或地区", "评论问题是否和落地页首屏、价格或取消路径有关", "评论变化是否早于 CVR 和 CPA 变差"],
    actions: ["按主题标注评论区负反馈", "重写素材承诺和落地页 FAQ", "设置客服回复、隐藏规则和素材暂停阈值"],
    evidence: "证据口径来自 ADXJ 对 TikTok 评论管理、素材优化和广告转化反馈的运营经验。",
  },
  {
    title: "Telegram Ads Topic 定向跑偏，怎么找回高意向用户？",
    slug: "telegram-ads-topic-targeting-wrong-audience",
    category: "出海企业洞察",
    topic: "telegram",
    excerpt: "Telegram Ads Topic 定向跑偏时，要检查频道语境、广告承诺、Bot 分流和咨询质量，而不是只看点击价格。",
    keywords: ["Telegram Ads", "Topic 定向", "高意向用户", "Telegram 私域", "广告承接"],
    coverImage: "/insights/telegram-ads-overseas-conversion-path.png",
    coverAlt: "Telegram Ads Topic 定向、高意向用户和私域承接示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "定向看似相关，但频道用户语境、预算阶段和真实需求不匹配，点击会变多而咨询质量不升",
    audience: "用 Telegram Ads 获取广告主、开发者、流量主或社群用户的团队",
    answer: "Telegram Ads Topic 定向跑偏时，要按频道语境、点击后行为、Bot Start 和人工咨询质量复盘；如果低质点击多，应重写广告承诺和分流入口。",
    signals: ["点击便宜但 Bot Start、咨询和留资低", "频道语境是否和广告服务高度相关", "用户问题是否偏离目标预算和品类"],
    actions: ["按 Topic 和频道语境归类点击质量", "重写广告文案和 Bot 欢迎语", "用高意向问题筛掉低质咨询"],
    evidence: "证据口径来自 ADXJ 对 Telegram Ads、社群定向和 Bot 承接质量的运营复盘。",
  },
  {
    title: "Telegram Bot 该先收款还是先咨询？服务型业务怎么分流？",
    slug: "telegram-bot-payment-consultation-routing",
    category: "出海企业洞察",
    topic: "telegram",
    excerpt: "服务型业务不能把所有用户都推向支付，Bot 要根据预算、紧急程度和问题复杂度决定先咨询还是先收款。",
    keywords: ["Telegram Bot", "服务咨询", "支付分流", "私域转化", "Bot 设计"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Bot 支付咨询分流、服务转化和线索质量示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "高复杂度服务如果一开始就推支付，用户可能因为不确定方案和价格而流失；低复杂度需求又会占用人工客服",
    audience: "用 Telegram Bot 承接开发者服务、投放诊断、网盟合作和社群服务的团队",
    answer: "Telegram Bot 服务分流应按预算、问题复杂度、紧急程度和资料完整度决定路径；高复杂问题先进人工咨询，标准需求再引导支付或预约。",
    signals: ["用户是否在价格问题前就中断对话", "客服是否被重复基础问题占用", "支付入口是否出现在用户理解服务价值之前"],
    actions: ["设计预算、品类和紧急程度分流问题", "为标准需求配置支付或预约入口", "把高复杂线索交给人工并记录跟进结果"],
    evidence: "证据口径来自 ADXJ 对 Telegram Bot、服务咨询和私域转化路径的内部项目复盘。",
  },
  {
    title: "Telegram 群垃圾信息变多，规则和审核怎么做才不伤转化？",
    slug: "telegram-community-anti-spam-moderation-rules",
    category: "出海企业洞察",
    topic: "telegram",
    excerpt: "群内垃圾信息会伤害信任，但审核太重也会压低活跃度，规则、关键词、人工复核和服务入口要平衡。",
    keywords: ["Telegram 群管理", "反垃圾", "社群审核", "私域运营", "社群转化"],
    coverImage: "/insights/telegram-private-traffic-community-conversion.png",
    coverAlt: "Telegram 群垃圾信息、审核规则和私域转化平衡示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "垃圾广告和低质量外链会让高意向用户减少发言，但过度封禁又可能误伤真实咨询",
    audience: "运营 Telegram 出海群组、行业社群和广告主流量主社区的团队",
    answer: "Telegram 群反垃圾要结合关键词、链接规则、人工复核和白名单机制；规则应保护高质量讨论，同时保留明确咨询和服务入口。",
    signals: ["垃圾链接、重复广告和无关招聘是否增加", "真实用户提问和私聊咨询是否下降", "规则是否误删案例、资源和服务咨询"],
    actions: ["建立关键词、链接和账号年龄审核规则", "设置人工复核和可信成员白名单", "把服务菜单和群规固定到欢迎入口"],
    evidence: "证据口径来自 ADXJ 对 Telegram 社群治理、反垃圾规则和行业社群转化的运营经验。",
  },
  {
    title: "Telegram 频道案例内容怎么写，才能带来咨询而不是只被围观？",
    slug: "telegram-channel-case-study-content-conversion",
    category: "出海企业洞察",
    topic: "telegram",
    excerpt: "案例内容要有问题、数据、处理动作和下一步 CTA，不能只发结果截图，否则用户看完不知道如何咨询。",
    keywords: ["Telegram 频道", "案例内容", "咨询转化", "私域内容", "社群运营"],
    coverImage: "/insights/telegram-community-customer-response-conversion-fix.png",
    coverAlt: "Telegram 频道案例内容、咨询 CTA 和私域转化示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群",
    servicePath: "/community",
    problem: "频道案例只展示结果，不说明适用条件、处理步骤和咨询入口，会让用户围观但不行动",
    audience: "用 Telegram 频道做出海服务、投放案例、开发者服务和网盟合作的团队",
    answer: "Telegram 频道案例内容应包含问题背景、判断信号、处理动作、结果口径和咨询 CTA，让用户能判断自己是否适用并知道下一步怎么联系。",
    signals: ["案例阅读或浏览高但私聊咨询低", "内容是否缺少问题背景和适用条件", "CTA 是否只写联系我而没有说明需要准备什么"],
    actions: ["把案例改成问题、动作、结果、CTA 四段式", "补充适用市场、品类和准备资料", "用私聊率和高意向线索数评估内容质量"],
    evidence: "证据口径来自 ADXJ 对 Telegram 频道案例内容、私域咨询和服务 CTA 的运营复盘。",
  },
  {
    title: "AI 聊天机器人记忆功能，隐私披露怎么写才不冒险？",
    slug: "ai-chatbot-memory-privacy-disclosure-review",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 记忆功能会涉及用户偏好、聊天内容和个性化推荐，隐私政策、删除入口和用户控制必须讲清楚。",
    keywords: ["AI 聊天机器人", "记忆功能", "隐私披露", "AI App 审核", "用户控制"],
    coverImage: "/insights/ai-companion-app-overseas-review-ads-subscription.png",
    coverAlt: "AI 聊天机器人记忆功能、隐私披露和用户控制示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "AI 记忆功能如果默认保存聊天偏好，却没有明确用户控制、删除和关闭方式，会引发隐私和审核风险",
    audience: "做 AI 伴侣、AI 聊天、角色记忆和个性化推荐功能的应用团队",
    answer: "AI 聊天机器人记忆功能要清楚说明保存哪些信息、用途、保留时间、关闭和删除方式；用户应能控制记忆开关，隐私政策也要同步更新。",
    signals: ["是否保存聊天内容、偏好或角色关系", "用户是否能查看、关闭和删除记忆", "隐私政策是否覆盖 AI 个性化和数据保留"],
    actions: ["梳理记忆字段、用途和保留周期", "补齐记忆开关、删除入口和隐私说明", "在商店页和审核备注里解释用户控制方式"],
    evidence: "证据口径来自 ADXJ 对 AI 伴侣、聊天记忆和隐私合规审核的服务经验。",
  },
  {
    title: "AI 头像 App 截图太漂亮，审核和转化会不会反噬？",
    slug: "ai-image-avatar-app-store-screenshot-proof",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 头像截图如果展示无法稳定生成的效果，会造成审核误导、用户落差和退款投诉，截图要有真实样例支撑。",
    keywords: ["AI 头像 App", "商店截图", "AI 图片生成", "退款投诉", "App Store 审核"],
    coverImage: "/insights/ai-image-generation-content-safety-reporting-fix.png",
    coverAlt: "AI 头像 App 商店截图、真实样例和审核转化风险示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "截图效果过度理想化，用户下载后发现生成质量、等待时间或免费额度不同，容易产生退款和差评",
    audience: "做 AI 头像、写真、图片生成和订阅类视觉工具的出海团队",
    answer: "AI 头像 App 商店截图应展示真实可复现效果，并说明模板、等待时间和付费边界；不能用无法稳定生成的样例承诺结果。",
    signals: ["用户差评是否集中在效果不符或等待太久", "截图样例是否来自真实产品流程", "订阅页是否说明生成次数、速度和模板限制"],
    actions: ["用真实生成样例替换夸张展示图", "补充模板、等待时间和付费边界说明", "把退款原因反馈到截图和 Paywall 改版"],
    evidence: "证据口径来自 ADXJ 对 AI 图片 App、商店截图和订阅退款复盘的项目经验。",
  },
  {
    title: "AI 视频模板要不要按市场本地化？美国、东南亚、拉美差在哪？",
    slug: "ai-video-template-localization-market-fit",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 视频模板的题材、字幕、音乐、人物和 CTA 如果不本地化，下载后转化和订阅会明显受限。",
    keywords: ["AI 视频模板", "本地化", "AI 视频 App", "订阅转化", "市场适配"],
    coverImage: "/insights/ai-video-app-subscription-conversion.png",
    coverAlt: "AI 视频模板本地化、市场适配和订阅转化示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "同一套 AI 视频模板跨市场投放，用户文化语境、音乐偏好、字幕语言和付费动机会不匹配",
    audience: "AI 视频、图生视频、模板工具和短视频创意 App 的出海团队",
    answer: "AI 视频模板应按美国、东南亚和拉美分别本地化题材、字幕、音乐、人物风格和 CTA；模板本地化会直接影响下载后的生成完成率和订阅率。",
    signals: ["不同市场下载量高但生成完成率差异明显", "模板点击和订阅是否集中在少数地区", "用户评论是否提到语言、风格或素材不适合本地"],
    actions: ["按市场拆分模板、字幕和音乐包", "用生成完成率和订阅率验证模板质量", "把高转化模板同步到商店截图和投放素材"],
    evidence: "证据口径来自 ADXJ 对 AI 视频模板、本地化素材和订阅转化的增长复盘。",
  },
  {
    title: "AI 工具取消订阅路径不清，会不会影响退款和审核？",
    slug: "ai-tool-subscription-cancel-flow-trust",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 工具订阅路径如果容易付费但难以取消，会引发退款、投诉和审核信任问题，取消方式要前置说明。",
    keywords: ["AI 工具订阅", "取消订阅", "退款风险", "订阅审核", "用户信任"],
    coverImage: "/insights/ai-writing-app-refund-rate-subscription-fix.png",
    coverAlt: "AI 工具取消订阅路径、退款风险和用户信任示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "用户不知道如何取消、试用后自动续订或权益说明不清，会把产品体验问题转化为退款和投诉",
    audience: "AI 写作、AI 图片、AI 视频和效率工具订阅团队",
    answer: "AI 工具订阅页要清楚展示价格、周期、试用、续订和取消方式；如果退款升高，应先优化取消路径和权益说明，而不是继续加素材投放。",
    signals: ["退款和取消是否集中在试用后首个计费周期", "Paywall 是否清楚说明续订和取消方式", "客服咨询是否反复询问如何取消"],
    actions: ["重写订阅权益、续订和取消说明", "在设置页和 FAQ 中补取消路径", "按渠道分析退款原因和素材承诺"],
    evidence: "证据口径来自 ADXJ 对 AI 工具订阅、退款投诉和 Paywall 信任建设的项目复盘。",
  },
  {
    title: "SLOTS 上架年龄分级和地区限制，放量前要怎么检查？",
    slug: "slots-app-store-age-rating-regional-compliance",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 出海要同时检查年龄分级、地区限制、商店页承诺和广告素材，避免上架、投放和支付风控互相冲突。",
    keywords: ["SLOTS 上架", "年龄分级", "地区限制", "iGaming 合规", "游戏投放"],
    coverImage: "/insights/slots-app-launch-risk-control.png",
    coverAlt: "SLOTS 上架年龄分级、地区限制和投放合规示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "SLOTS 产品在不同地区的年龄、支付、广告表达和商店可见性要求不同，统一配置可能带来合规和转化风险",
    audience: "准备上架或放量 SLOTS、iGaming 和充值游戏的团队",
    answer: "SLOTS 放量前要核对年龄分级、地区限制、商店页、落地页、广告素材和支付配置；任何一处口径不一致，都可能影响审核、投放和首充。",
    signals: ["目标市场年龄分级和商店可见性是否正确", "广告素材是否和商店页地区限制一致", "支付入口是否只对允许地区开放"],
    actions: ["建立地区、年龄、支付和素材合规矩阵", "同步商店页和落地页地区说明", "放量前用目标市场账号复测安装到首充路径"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 上架、地区限制和 iGaming 买量合规的项目经验。",
  },
  {
    title: "SLOTS Meta 和 TikTok 素材疲劳，Bonus 角度还能继续用吗？",
    slug: "slots-meta-tiktok-creative-fatigue-bonus-angle",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "Bonus 角度前期容易带点击，但长期会出现疲劳、低质首充和审核风险，需要按地区和用户阶段拆新素材。",
    keywords: ["SLOTS 素材疲劳", "Bonus 素材", "Meta TikTok", "iGaming 投放", "首充转化"],
    coverImage: "/insights/slots-landing-page-store-page-mismatch-roi-fix.png",
    coverAlt: "SLOTS Bonus 素材疲劳、Meta TikTok 投放和首充转化示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "长期使用 Bonus 钩子会吸引薅奖励用户，点击成本可能好看，但首充质量和 Day7 ROI 下降",
    audience: "在 Meta、TikTok 和本地渠道投放 SLOTS 的素材与买量团队",
    answer: "SLOTS Bonus 素材可以继续测试，但不能成为唯一角度；应按地区、首充、玩法和社交证明拆素材，用首充质量和 Day7 ROI 判断是否疲劳。",
    signals: ["CTR 稳定但首充率和 Day7 ROI 下滑", "评论区是否只关注奖励而不是玩法", "Bonus 素材是否触发平台审核或用户投诉"],
    actions: ["把 Bonus、玩法、社交证明和本地化角度分组", "按地区看首充质量和留存", "暂停高点击低质量素材并补新钩子"],
    evidence: "证据口径来自 ADXJ 对 SLOTS Meta/TikTok 素材疲劳、Bonus 表达和回本周期的投放复盘。",
  },
  {
    title: "SLOTS 退款和支付投诉变多，是活动规则还是风控问题？",
    slug: "slots-payment-refund-complaint-risk-control",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 退款和支付投诉上升时，要一起看活动规则、支付成功率、客服响应、风控拦截和商店页承诺。",
    keywords: ["SLOTS 退款", "支付投诉", "风控", "iGaming 支付", "活动规则"],
    coverImage: "/insights/slots-payment-funnel-dropoff-region-channel-fix.png",
    coverAlt: "SLOTS 退款投诉、支付风控和活动规则排查示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "用户充值后无法理解奖励规则、提现边界或支付状态，会把体验问题转成退款和投诉",
    audience: "运营 SLOTS 支付、客服、活动和买量回本的团队",
    answer: "SLOTS 退款和支付投诉变多时，要先检查活动规则、支付状态提示、客服响应和风控拦截；如果承诺不清，应先修规则说明再继续放量。",
    signals: ["投诉是否集中在首充、奖励或提现环节", "支付失败后是否有清晰状态和客服入口", "风控拦截是否误伤高价值用户"],
    actions: ["按支付、活动和客服原因归类投诉", "重写奖励规则和支付状态提示", "把退款率纳入渠道和素材质量评估"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 支付漏斗、活动规则和用户投诉治理的服务经验。",
  },
  {
    title: "SLOTS 首局体验太慢，会不会拖低留存和付费？",
    slug: "slots-retention-first-session-onboarding-fix",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 首局体验决定用户是否愿意注册、领取奖励和首充，加载、教程、奖励展示和支付入口都要足够短。",
    keywords: ["SLOTS 留存", "首局体验", "新手引导", "首充转化", "游戏增长"],
    coverImage: "/insights/slots-payback-cycle-region-creative-roi.png",
    coverAlt: "SLOTS 首局体验、新手引导和留存付费优化示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "用户从广告进入后等待太久、教程过长或奖励价值不清，会在首局前流失，买量成本很难回收",
    audience: "关注 SLOTS Day1 留存、首充和买量 ROI 的产品增长团队",
    answer: "SLOTS 首局体验要缩短加载、教程和奖励领取路径，让用户快速看到玩法和首充价值；如果首局流失高，应先优化 onboarding 再加预算。",
    signals: ["安装到首局开始的转化是否偏低", "新手教程是否过长或不可跳过", "奖励和首充入口是否在首局后及时出现"],
    actions: ["拆分安装、注册、首局和首充漏斗", "缩短教程并强化奖励展示", "按地区和素材来源比较首局留存"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 首局体验、留存和首充漏斗优化的增长复盘。",
  },
  {
    title: "现金贷 App Store 和 Google Play 披露要求怎么同时满足？",
    slug: "cash-loan-app-store-google-play-disclosure-check",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷同时上 iOS 和 Android 时，费用、期限、隐私、权限和资质披露要按平台要求分别准备，同时保持核心口径一致。",
    keywords: ["现金贷上架", "App Store Google Play", "费用披露", "金融 App 审核", "贷款合规"],
    coverImage: "/insights/cash-loan-overseas-growth-compliance.png",
    coverAlt: "现金贷 App Store Google Play 披露要求和合规审核示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "iOS 和 Android 对金融产品展示、权限、隐私和费用披露的要求不同，但用户看到的核心承诺又必须一致",
    audience: "准备双端上架现金贷、分期和金融科技产品的出海团队",
    answer: "现金贷双端上架要分别满足 App Store 和 Google Play 的费用、期限、隐私、权限和资质披露要求，同时让广告、商店页和应用内口径一致。",
    signals: ["两端商店页是否展示同一费用和期限口径", "权限和隐私政策是否覆盖贷款申请数据", "资质证明是否符合目标市场和平台要求"],
    actions: ["建立 iOS/Android 披露清单和差异表", "同步费用、隐私、权限和资质材料", "用双端审核账号复测申请到还款路径"],
    evidence: "证据口径来自 ADXJ 对现金贷双端上架、金融披露和平台审核要求的项目复盘。",
  },
  {
    title: "现金贷 Meta Lead Form 线索多但质量差，怎么优化？",
    slug: "cash-loan-meta-lead-form-quality-score-fix",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "Lead Form 能降低填写门槛，但现金贷要加入资格、地区、收入和意向问题，否则线索多但首还质量差。",
    keywords: ["现金贷 Lead Form", "Meta 线索质量", "获客质量", "金融投放", "首还率"],
    coverImage: "/insights/cash-loan-channel-high-applications-low-repayment-fix.png",
    coverAlt: "现金贷 Meta Lead Form 线索质量、资格筛选和首还优化示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "表单太短会吸引大量低意向用户，客服和风控后端才发现资料不匹配、地区不合规或还款能力弱",
    audience: "用 Meta Lead Ads、表单和本地渠道做现金贷获客的团队",
    answer: "现金贷 Meta Lead Form 要加入地区、资格、金额、收入或紧急程度筛选，并把线索质量和首还率回传给投放，不应只追求表单量。",
    signals: ["线索量上升但通过率、放款率和首还率下降", "低质用户是否集中在某些素材或地区", "表单问题是否足够判断基本资格"],
    actions: ["增加资格、地区和金额筛选问题", "把线索质量回传到广告组和素材", "按首还率调整素材、地区和预算"],
    evidence: "证据口径来自 ADXJ 对现金贷 Lead Form、Meta 获客质量和首还率联动优化的投放经验。",
  },
  {
    title: "现金贷催收短信文案不合规，会影响投放和品牌词吗？",
    slug: "cash-loan-collection-message-compliance-risk",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "催收短信、WhatsApp 和站内信如果语气、频次或隐私边界不合规，会引发投诉、品牌词负面和广告账户风险。",
    keywords: ["现金贷催收", "催收短信", "合规风险", "品牌词负面", "金融客服"],
    coverImage: "/insights/cash-loan-ad-risk-funnel-repayment.png",
    coverAlt: "现金贷催收短信、合规边界和品牌风险示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "催收触达如果过度频繁、措辞强硬或涉及第三方隐私，会让用户投诉从客服问题扩散到广告和品牌层面",
    audience: "运营现金贷还款提醒、催收触达和金融广告投放的团队",
    answer: "现金贷催收文案要控制语气、频次、隐私边界和退订方式；如果投诉变多，应先修催收触达和客服流程，再继续扩大获客预算。",
    signals: ["投诉是否集中在还款提醒或催收触达", "短信、WhatsApp 和站内信是否出现威胁或隐私泄露表达", "品牌词搜索和评论区是否出现负面反馈"],
    actions: ["审核催收文案、频次和触达渠道", "补充客服解释、退订和申诉路径", "把投诉率纳入渠道质量和预算决策"],
    evidence: "证据口径来自 ADXJ 对现金贷催收触达、用户投诉和金融广告品牌风险的服务复盘。",
  },
  {
    title: "东南亚现金贷费用文案怎么本地化，才不误导用户？",
    slug: "cash-loan-sea-market-localization-fee-copy",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "东南亚市场语言、费用习惯和还款表达差异明显，现金贷费用文案要让用户能理解真实成本和还款责任。",
    keywords: ["东南亚现金贷", "费用文案", "本地化", "贷款广告", "还款说明"],
    coverImage: "/insights/cash-loan-landing-page-fee-disclosure-ads-complaint-fix.png",
    coverAlt: "东南亚现金贷费用文案、本地化和用户理解示意图",
    markets: ["southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "直译费用、利率和还款期限会让用户误解真实成本，后续投诉、逾期和广告拒审都会增加",
    audience: "面向东南亚投放现金贷、分期和本地金融产品的团队",
    answer: "东南亚现金贷费用文案要按当地语言和用户理解方式展示金额、期限、费用、逾期后果和还款方式，避免只翻译中文模板。",
    signals: ["用户是否反复咨询费用、期限和还款方式", "投诉是否提到广告或页面误导", "不同语言落地页是否使用同一费用口径"],
    actions: ["按市场重写费用、期限和还款说明", "用本地客服话术验证用户理解", "把费用披露同步到广告、落地页和商店页"],
    evidence: "证据口径来自 ADXJ 对东南亚现金贷本地化、费用披露和广告转化的项目经验。",
  },
  {
    title: "CPA Offer 暂停了，怎么通知流量主才不伤合作？",
    slug: "cpa-network-offer-paused-publisher-communication",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Offer 暂停要清楚说明暂停时间、原因、已产生转化、结算口径和替代 Offer，避免流量主误判为扣量。",
    keywords: ["CPA Offer 暂停", "流量主通知", "网盟合作", "结算沟通", "Offer 管理"],
    coverImage: "/insights/overseas-affiliate-cpa-settlement-risk.png",
    coverAlt: "CPA Offer 暂停、流量主通知和结算沟通示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "Offer 突然暂停但通知不清，流量主会继续送量或质疑结算，广告主也会承受额外争议成本",
    audience: "管理 CPA Offer、网盟合作和流量主关系的运营团队",
    answer: "CPA Offer 暂停时要同步暂停时间、原因、已产生转化处理、结算口径和替代 Offer；通知越清楚，越能降低扣量争议和合作损耗。",
    signals: ["Offer 是否因预算、质量、政策或技术原因暂停", "暂停前转化和回传是否已经锁定", "流量主是否有替代 Offer 和迁移时间"],
    actions: ["发布标准暂停通知和结算说明", "锁定暂停前转化、回传和争议窗口", "提供替代 Offer、Cap 和迁移建议"],
    evidence: "证据口径来自 ADXJ 对 CPA Offer 管理、流量主沟通和结算争议处理的运营复盘。",
  },
  {
    title: "CPA Postback 重复转化，去重规则怎么定才公平？",
    slug: "cpa-postback-duplicate-conversion-deduplication",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "重复转化会影响广告主成本和流量主结算，去重规则要基于 click id、用户标识、事件窗口和订单状态提前约定。",
    keywords: ["CPA Postback 去重", "重复转化", "网盟结算", "click id", "转化回传"],
    coverImage: "/insights/publisher-api-integration-lost-conversions-postback-audit.png",
    coverAlt: "CPA Postback 重复转化、去重规则和结算公平性示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "同一用户、同一订单或重复回传被多次计费，会造成广告主拒付和流量主对账争议",
    audience: "接入 CPA API、Postback、MMP 和网盟结算系统的广告主与流量主团队",
    answer: "CPA Postback 去重要提前约定 click id、用户标识、事件窗口、订单状态和重复回传处理规则，并在报表中保留去重原因。",
    signals: ["同一 click id 或用户是否出现多次转化", "重复是否集中在某些流量主或事件", "订单取消、退款和反作弊结果是否同步回传"],
    actions: ["定义 click id、用户和订单级去重优先级", "记录重复、取消和反作弊原因", "把去重规则写入 Offer 与结算说明"],
    evidence: "证据口径来自 ADXJ 对 CPA Postback、API 接入和网盟结算公平性的技术复盘。",
  },
  {
    title: "CPA SubID 报告怎么做，才能定位低质量来源？",
    slug: "cpa-affiliate-subid-quality-reporting",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "SubID 不只是追踪参数，还要和国家、素材、转化、留存、退款和反作弊结果绑定，才能真正指导预算。",
    keywords: ["CPA SubID", "质量报告", "流量来源", "网盟报表", "反作弊"],
    coverImage: "/insights/overseas-cpa-traffic-fraud-detection-checklist.png",
    coverAlt: "CPA SubID 质量报告、低质量来源和预算优化示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "只有总转化报表无法定位低质量来源，广告主和流量主都不知道该停哪个子渠道或素材",
    audience: "需要做 CPA 流量质量分层、预算分配和反作弊的网盟运营团队",
    answer: "CPA SubID 报告应绑定国家、子渠道、素材、转化、质量回传、退款和作弊命中；只有这样才能定位低质量来源并保留可扩量组合。",
    signals: ["低质量转化是否集中在少数 SubID", "SubID 是否能映射到渠道、素材和国家", "广告主质量反馈是否能回写到报表"],
    actions: ["规范 SubID 命名和维度映射", "把质量、退款和反作弊结果接入报表", "按 SubID 调整 Cap、Pacing 和结算条件"],
    evidence: "证据口径来自 ADXJ 对 CPA SubID 报表、流量主质量回传和反作弊治理的服务经验。",
  },
  {
    title: "CPA Day0 结算现金流压力大，风控线怎么设？",
    slug: "cpa-day0-settlement-cashflow-risk-control",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Day0 结算能吸引流量主，但广告主质量回传和反作弊窗口不足时，现金流和扣量争议都会放大。",
    keywords: ["CPA Day0 结算", "现金流风险", "反作弊", "网盟结算", "质量阈值"],
    coverImage: "/insights/publisher-day0-settlement-advertiser-quality-thresholds.png",
    coverAlt: "CPA Day0 结算、现金流压力和风控阈值示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量",
    servicePath: "/media",
    problem: "过早给高 Cap 和 Day0 结算，会在质量未确认前支付成本，后续扣量和追回都很困难",
    audience: "设计 CPA 结算周期、流量主激励和广告主质量阈值的网盟团队",
    answer: "CPA Day0 结算要设置流量主准入、低 Cap 试跑、质量回传、反作弊阈值和保证金规则；质量未稳定前不应直接开放大额 Day0。",
    signals: ["Day0 流量是否缺少后端质量确认", "退款、拒付或反作弊命中是否晚于结算", "流量主是否能接受质量阈值和回款规则"],
    actions: ["设置 Day0 准入评分和试跑 Cap", "把质量回传和反作弊结果纳入结算规则", "按流量主等级分配结算周期和额度"],
    evidence: "证据口径来自 ADXJ 对 CPA Day0 结算、现金流风控和流量主质量分层的业务复盘。",
  },
  {
    title: "ASO 标题堆关键词，会不会影响审核和转化？",
    slug: "aso-app-title-keyword-stuffing-review-risk",
    category: "开发者出海",
    topic: "aso",
    excerpt: "标题堆关键词可能短期覆盖更多词，但会削弱品牌识别、降低点击信任，也可能触发平台对误导元数据的检查。",
    keywords: ["ASO 标题", "关键词堆砌", "App Store 审核", "标题优化", "关键词转化"],
    coverImage: "/insights/app-launch-no-organic-traffic-aso.png",
    coverAlt: "ASO 标题关键词堆砌、审核风险和转化影响示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "标题塞入太多泛词后，用户无法快速理解产品定位，平台也可能认为元数据和实际功能不匹配",
    audience: "做 App Store ASO、Google Play ASO 和新应用冷启动的团队",
    answer: "ASO 标题不应只追求关键词数量，而要保留品牌、核心功能和高意图词；关键词堆砌会降低点击信任，并可能带来元数据审核风险。",
    signals: ["标题是否难以自然阅读或和截图卖点不一致", "排名上升但页面转化率没有改善", "用户评论或搜索词是否说明定位不清"],
    actions: ["把标题拆成品牌、核心功能和高意图词", "用副标题、短描述和截图承接长尾词", "按排名、点击率和转化率评估改版"],
    evidence: "证据口径来自 ADXJ 对 ASO 标题、本地化关键词和商店页转化的项目复盘。",
  },
  {
    title: "Google Play 长描述怎么写，才能让 AI 和搜索都理解实体？",
    slug: "aso-google-play-long-description-entity-clusters",
    category: "开发者出海",
    topic: "aso",
    excerpt: "Google Play 长描述不只是堆词，要围绕核心功能、场景、市场、用户问题和实体关系建立关键词集群。",
    keywords: ["Google Play 长描述", "ASO 关键词集群", "实体 SEO", "AI 搜索", "应用描述"],
    coverImage: "/insights/google-play-old-app-update-target-api-sdk-fix.png",
    coverAlt: "Google Play 长描述、实体关键词集群和 AI 搜索理解示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "长描述只堆关键词但缺少功能、场景和用户问题，会让搜索和 AI 难以判断应用到底解决什么需求",
    audience: "希望提升 Google Play 自然量、AI 可理解度和多市场 ASO 表现的应用团队",
    answer: "Google Play 长描述应围绕核心功能、使用场景、目标市场、用户问题和相关实体组织关键词集群，而不是机械重复单个关键词。",
    signals: ["长描述是否覆盖功能、场景、用户痛点和市场词", "关键词排名是否只覆盖泛词但转化低", "描述是否能回答用户为什么下载和如何使用"],
    actions: ["建立功能、场景、市场和问题词集群", "重写长描述结构和前三段重点", "用关键词排名、转化率和 GSC 查询复盘效果"],
    evidence: "证据口径来自 ADXJ 对 Google Play ASO、长描述实体集群和自然量增长的服务经验。",
  },
  {
    title: "ASO 活动季关键词什么时候更新，才不会错过流量？",
    slug: "aso-seasonal-keyword-update-before-campaign",
    category: "开发者出海",
    topic: "aso",
    excerpt: "活动季关键词不能等投放开始才改，标题、副标题、截图、评论运营和买量素材要提前形成同一组信号。",
    keywords: ["ASO 活动季", "季节关键词", "关键词更新", "自然量增长", "活动投放"],
    coverImage: "/insights/new-app-no-organic-traffic-aso-paid-signal-case.png",
    coverAlt: "ASO 活动季关键词、截图和买量信号协同示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "活动季到来后才改关键词，搜索排名和商店转化信号来不及积累，买量也难以带动自然量",
    audience: "准备做节日、返校、黑五、年末或地区活动投放的应用团队",
    answer: "ASO 活动季关键词应在活动前 2-4 周完成规划，并同步标题、副标题、截图、描述和买量素材，让搜索和转化信号提前积累。",
    signals: ["目标活动词是否已有搜索趋势上升", "截图和素材是否同步活动利益点", "买量词和自然词是否互相支持"],
    actions: ["提前建立活动词和地区词清单", "同步更新截图、短描述和素材承诺", "用排名、点击率和安装转化监控活动窗口"],
    evidence: "证据口径来自 ADXJ 对 ASO 活动季、本地化关键词和买量自然量协同的增长复盘。",
  },
  {
    title: "竞品评论里藏着哪些 ASO 关键词机会？怎么挖才有效？",
    slug: "aso-competitor-review-mining-keyword-gap",
    category: "开发者出海",
    topic: "aso",
    excerpt: "竞品评论能暴露真实需求、差评痛点和本地化表达，把这些词映射到标题、截图和内容页可以补关键词缺口。",
    keywords: ["竞品评论", "ASO 关键词", "关键词缺口", "评论挖掘", "本地化 ASO"],
    coverImage: "/insights/aso-localization-keywords-us-sea-latam-case.png",
    coverAlt: "竞品评论挖掘、ASO 关键词缺口和本地化机会示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "只看关键词工具会错过用户在评论中真实表达的功能需求、抱怨和本地说法，竞品差评往往就是内容机会",
    audience: "做多市场 ASO、竞品分析和自然量增长的应用团队",
    answer: "竞品评论挖词要提取高频功能词、差评痛点、本地表达和用户场景，再映射到标题、副标题、截图、长描述和官网文章。",
    signals: ["竞品评论是否反复提到未满足功能", "本地用户是否使用和工具词库不同的说法", "自己商店页是否缺少这些场景词"],
    actions: ["按国家和情绪提取竞品评论词", "把关键词映射到商店页和内容页", "用排名、转化和评论反馈验证关键词机会"],
    evidence: "证据口径来自 ADXJ 对竞品评论挖掘、ASO 关键词缺口和本地化自然量增长的服务复盘。",
  },
];

export const dailySeoArticles20260630: InsightArticle[] = seeds.map(dailyGeoArticle);
