import type { GeoMarketSlug } from "@/lib/geo-content";
import type { InsightArticle, InsightCategory } from "./articles";
import type { InsightTopicSlug } from "./topics";

type DailyGeoSeed = {
  title: string;
  slug: string;
  category: InsightCategory;
  topic: InsightTopicSlug;
  excerpt: string;
  keywords: string[];
  coverImage: string;
  coverAlt: string;
  markets: GeoMarketSlug[];
  serviceName: string;
  servicePath: string;
  problem: string;
  audience: string;
  answer: string;
  signals: string[];
  actions: string[];
  evidence: string;
};

const publishedAt = "2026-06-28";

const relatedByTopic: Record<InsightTopicSlug, string[]> = {
  "app-store": [
    "app-store-review-rejected-four-times-ios-fix",
    "app-store-subscription-page-review-geo-signal",
    "app-store-review-72-hour-checklist",
  ],
  "google-play": [
    "google-play-data-safety-form-six-data-types",
    "google-play-old-app-update-target-api-sdk-fix",
    "google-play-account-association-assets-audit",
  ],
  "meta-ads": [
    "meta-ads-account-restricted-bm-landing-page-fix",
    "meta-pixel-capi-event-tracking-roas-fix",
    "meta-advantage-plus-performance-drop-event-creative-fix",
  ],
  "tiktok-ads": [
    "tiktok-smart-performance-campaign-ai-tool-event-fix",
    "tiktok-creator-creative-authorization-ugc-ads-fix",
    "tiktok-ads-clicks-no-payment-ai-tool-funnel",
  ],
  telegram: [
    "telegram-bot-lead-qualification-dropoff-fix",
    "telegram-private-traffic-community-conversion",
    "telegram-community-customer-response-conversion-fix",
  ],
  "ai-apps": [
    "ai-companion-app-overseas-review-ads-subscription",
    "ai-face-swap-ads-rejected-consent-landing-page-fix",
    "ai-writing-app-refund-rate-subscription-fix",
  ],
  slots: [
    "slots-overseas-payback-slow-day7-roi-review",
    "slots-payment-funnel-dropoff-region-channel-fix",
    "slots-landing-page-store-page-mismatch-roi-fix",
  ],
  "cash-loan": [
    "cash-loan-landing-page-fee-disclosure-ads-complaint-fix",
    "cash-loan-channel-high-applications-low-repayment-fix",
    "cash-loan-app-ads-rejected-compliance-funnel-fix",
  ],
  "cpa-network": [
    "cpa-offer-scaling-cap-pacing-quality-feedback-fix",
    "publisher-api-integration-lost-conversions-postback-audit",
    "publisher-day0-settlement-advertiser-quality-thresholds",
  ],
  aso: [
    "aso-localization-keywords-us-sea-latam-case",
    "app-launch-no-organic-traffic-aso",
    "brand-keyword-defense-overseas-seo-ads-strategy",
  ],
};

function dailyGeoArticle(seed: DailyGeoSeed): InsightArticle {
  const [firstSignal, secondSignal, thirdSignal] = seed.signals;
  const [firstAction, secondAction, thirdAction] = seed.actions;

  return {
    title: seed.title,
    slug: seed.slug,
    category: seed.category,
    excerpt: seed.excerpt,
    keywords: seed.keywords,
    coverImage: seed.coverImage,
    coverAlt: seed.coverAlt,
    publishedAt,
    lastReviewedAt: publishedAt,
    topic: seed.topic,
    markets: seed.markets,
    relatedSlugs: relatedByTopic[seed.topic],
    readTime: "7 分钟",
    answerSummary: seed.answer,
    faqs: [
      {
        question: `${seed.title} 的直接答案是什么？`,
        answer: seed.answer,
      },
      {
        question: "这篇内容为什么同时符合 SEO 和 GEO？",
        answer: `它用问题型标题承接搜索意图，用直接答案、FAQ、${seed.topic} 专题归属、市场标签和相关文章内链帮助 AI 引擎抽取结论，也给用户留下继续咨询 ${seed.serviceName} 的明确路径。`,
      },
      {
        question: "咨询 ADXJ 前应该准备哪些信息？",
        answer: `建议准备目标市场、产品品类、平台反馈截图、近 7 天数据、当前操作记录和已尝试修复动作，再通过 Telegram @M7HHHH、微信 M7HHHH 或 business@adxj.com 发给 ADXJ。`,
      },
    ],
    evidenceNotes: [
      seed.evidence,
      `本文最近一次 GEO/SEO 复核日期为 ${publishedAt}，用于补充今日高意图问题、专题内链、市场标签和 AI 可引用答案。`,
    ],
    content: [
      {
        heading: "为什么今天要优先看这个问题",
        paragraphs: [
          `${seed.problem} 对 ${seed.audience} 来说，通常不是一个孤立的页面或账户问题，而是平台信任、用户路径、数据证据和业务承接共同作用的结果。如果只改表层文案，短期可能能继续提交，但后续审核、投放或转化仍会反复波动。`,
          `${seed.answer} 这类问题适合做成 GEO/SEO 内容，因为用户搜索时已经带着明确痛点，AI 问答也需要页面先给出直接结论，再解释适用场景、判断信号和下一步动作。`,
        ],
      },
      {
        heading: "先看三个关键判断信号",
        paragraphs: [
          `第一个信号是${firstSignal}。它能帮助团队判断问题是否已经影响上架、投放、收录、转化或回款，而不是停留在主观感觉。`,
          `第二个信号是${secondSignal}。如果这个信号和页面承诺、广告素材、商店截图或后台事件不一致，搜索用户会很快流失，AI 摘要也难以给出可信答案。第三个信号是${thirdSignal}，它决定问题要走内容刷新、技术修复、服务诊断还是账户风控路径。`,
        ],
      },
      {
        heading: "ADXJ 建议的三步处理路径",
        paragraphs: [
          `第一步，${firstAction}。这一步要留下可复核记录，包括截图、URL、事件名、审核反馈、状态码或用户路径，方便后续把问题写进 FAQ 和直接答案。`,
          `第二步，${secondAction}。这一步决定 SEO 页面是否能吸引用户继续阅读，也决定 GEO 内容是否能被 AI 引擎提炼成“可执行建议”。第三步，${thirdAction}，把处理动作连接到 ${seed.serviceName}，让用户知道下一步该交给谁、准备什么资料、预期解决什么问题。`,
        ],
      },
      {
        heading: "如何把文章变成线索入口",
        paragraphs: [
          `页面发布后，应把本文加入 ${seed.topic} 专题、相关旧文和 llms-full 索引，并用至少三条内链连接相近案例。这样用户能从搜索问题进入文章，再继续看到服务页、专题页和相似问题，降低跳出率。`,
          `如果你的项目正在遇到类似情况，可以把地区、产品截图、平台后台、投放数据或收录状态整理好，联系 ADXJ：Telegram @M7HHHH、微信 M7HHHH、邮箱 business@adxj.com。我们会按 ${seed.serviceName} 视角给出诊断清单。`,
        ],
      },
    ],
  };
}

const seeds: DailyGeoSeed[] = [
  {
    title: "App Store 订阅退款变多，会影响审核和投放放量吗？",
    slug: "app-store-subscription-refund-dispute-review-fix",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "App Store 订阅退款升高时，不只影响收入，还可能暴露价格说明、试用权益、取消路径和广告承诺不一致的问题。",
    keywords: ["App Store 退款", "iOS 订阅", "订阅审核", "退款率", "苹果上架"],
    coverImage: "/insights/app-store-subscription-review-price-trial-cancel-fix.png",
    coverAlt: "App Store 订阅退款、试用权益和取消路径排查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "订阅退款突然变多，往往说明用户看到的广告承诺、商店页描述和应用内付费权益之间存在落差",
    audience: "正在做 iOS 订阅、AI 工具、效率工具或内容类应用的出海团队",
    answer: "App Store 订阅退款变多要先查价格、试用、取消入口和素材承诺是否一致，再看退款用户来自哪个渠道；若问题持续，应同步修订商店页、订阅页和投放素材。",
    signals: ["退款用户来源和首日行为", "订阅页价格、周期、试用和取消入口的一致性", "投放素材或商店截图是否放大了付费权益"],
    actions: ["导出退款、试用开始、首购和取消数据", "重写订阅页权益说明并同步商店截图", "把高退款素材暂停或改成更真实的产品场景"],
    evidence: "证据口径来自 ADXJ 对 iOS 订阅应用退款、审核反馈和投放素材复盘的服务经验。",
  },
  {
    title: "AI 图片 App 要相机和相册权限，iOS 审核备注怎么写才稳？",
    slug: "ios-ai-photo-permission-review-note",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "AI 图片 App 申请相机、相册和云端生成权限时，审核备注要说明触发场景、数据用途、保存方式和删除路径。",
    keywords: ["iOS 权限审核", "AI 图片 App", "相册权限", "相机权限", "审核备注"],
    coverImage: "/insights/ios-privacy-disclosure-camera-photo-ai-sdk-fix.png",
    coverAlt: "AI 图片 App 相机相册权限与 iOS 审核备注示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "AI 图片 App 权限说明写得太泛，容易让审核员无法确认上传图片、生成结果和用户删除之间的关系",
    audience: "正在提交 AI 图片、AI 头像、AI 换脸或图生视频功能的 iOS 团队",
    answer: "AI 图片 App 的 iOS 审核备注要把相机、相册、云端处理、生成结果保存和删除入口写成一条可复现路径；不要只写模板化隐私声明。",
    signals: ["权限弹窗是否在用户主动操作后出现", "隐私政策是否解释云端处理和第三方 SDK", "审核账号是否能完整体验上传到删除的流程"],
    actions: ["按权限重写审核备注和应用内说明", "把隐私政策、权限弹窗和商店隐私披露对齐", "准备测试账号和示例素材供审核员复现"],
    evidence: "证据口径来自 ADXJ 对 AI 图片、AI 换脸和 iOS 权限审核案例的综合整理。",
  },
  {
    title: "App Store 截图和实际功能不一致，为什么会连续被拒？",
    slug: "app-store-review-metadata-screenshot-mismatch-audit",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "App Store 截图、标题、副标题和实际功能不一致，会被理解为误导用户，敏感品类尤其容易连续触发拒审。",
    keywords: ["App Store 截图", "元数据审核", "iOS 被拒", "商店页优化", "审核申诉"],
    coverImage: "/insights/app-store-review-rejected-four-times-ios-fix.png",
    coverAlt: "App Store 截图和实际功能不一致导致拒审排查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "商店截图展示的卖点和审核账号进入后的实际功能不同，会让审核员判断产品承诺不可验证",
    audience: "已经多次被拒、准备改元数据或准备上线敏感品类的 iOS 团队",
    answer: "App Store 截图不一致要先统一标题、截图、功能入口、订阅页和审核账号路径；如果截图承诺审核员无法复现，应先改截图和备注，再提交新包。",
    signals: ["前三张截图是否能在产品内快速复现", "标题副标题是否夸大核心功能", "审核账号是否进入同一套功能和数据环境"],
    actions: ["逐张核对截图和包体真实路径", "删除无法复现或过度承诺的素材表达", "在审核备注中列出功能入口和测试步骤"],
    evidence: "证据口径来自 ADXJ 对 App Store 元数据、截图审核和敏感品类上架复盘的服务经验。",
  },
  {
    title: "iOS 应用转让账号后更新被卡，团队要先查哪些资产？",
    slug: "ios-account-transfer-update-risk-checklist",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "iOS 应用转让或团队接手后更新被卡，要检查主体、证书、Bundle ID、隐私政策、订阅和后台域名是否仍然一致。",
    keywords: ["iOS 应用转让", "Apple Developer", "Bundle ID", "证书", "应用更新被拒"],
    coverImage: "/insights/developer-account-team-permission-2fa-audit-trail-fix.png",
    coverAlt: "iOS 应用转让后账号资产和更新风险排查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "应用转让后只改代码不查账号资产，容易在证书、主体、订阅和隐私政策上出现解释断层",
    audience: "接手旧 iOS 应用、收购 App 或更换开发团队的出海公司",
    answer: "iOS 应用转让后更新被卡，应先审计开发者主体、证书、Bundle ID、订阅配置、隐私政策域名和后台接口，再决定是否提交解释或重构更新计划。",
    signals: ["App Store Connect 权限和证书是否完整", "订阅和隐私政策主体是否仍匹配", "后台域名、SDK 和客服入口是否已迁移"],
    actions: ["建立转让资产清单和责任人记录", "同步更新隐私政策、客服和订阅说明", "用小版本先验证审核路径再做大功能更新"],
    evidence: "证据口径来自 ADXJ 对开发者账号、应用资产迁移和 iOS 更新审核案例的整理。",
  },
  {
    title: "Google Play 数据安全表单和 SDK 对不上，下架前怎么补救？",
    slug: "google-play-data-safety-sdk-audit-before-removal",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 数据安全表单和 SDK 实际采集不一致时，要先列出广告、统计、登录、支付和推送 SDK 的数据行为。",
    keywords: ["Google Play 数据安全", "Android SDK", "数据安全表单", "应用下架", "隐私政策"],
    coverImage: "/insights/google-play-data-safety-form-app-removal-fix.png",
    coverAlt: "Google Play 数据安全表单和 SDK 行为不一致排查示意图",
    markets: ["southeast-asia", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "数据安全表单写得过于乐观，但 SDK 实际采集了广告标识、设备信息或行为数据",
    audience: "使用多个第三方 SDK、准备更新或收到 Google Play 隐私提醒的 Android 团队",
    answer: "Google Play 数据安全表单和 SDK 对不上，要先盘点所有 SDK 的采集、共享、加密和删除能力，再同步更新表单、隐私政策和应用内说明。",
    signals: ["SDK 清单和版本是否最新", "表单里的数据类型是否覆盖广告标识和设备信息", "隐私政策是否写清第三方共享和删除方式"],
    actions: ["导出 SDK、权限和数据类型清单", "逐项修正数据安全表单和隐私政策", "移除不必要 SDK 或替换无法解释的数据采集"],
    evidence: "证据口径来自 ADXJ 对 Google Play 数据安全表单、SDK 合规和 Android 上架案例的综合整理。",
  },
  {
    title: "Android 目标 API 截止前还没升级，老应用更新怎么排雷？",
    slug: "android-target-api-deadline-update-review-fix",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Android 老应用目标 API 升级前，要同步检查权限、SDK、数据安全表单、通知适配和隐私政策，否则更新容易被卡。",
    keywords: ["Android 目标 API", "Google Play 更新", "老应用升级", "SDK 升级", "权限适配"],
    coverImage: "/insights/google-play-old-app-update-target-api-sdk-fix.png",
    coverAlt: "Android 目标 API 截止前老应用更新排雷示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "老应用只升级 targetSdk，却没有同步处理历史权限、旧 SDK 和隐私披露",
    audience: "准备在 Google Play 截止前更新老应用或工具矩阵的 Android 团队",
    answer: "Android 目标 API 升级不能只改构建参数；要把权限、SDK、通知、后台接口和数据安全表单一起复核，先小范围测试再提交更新。",
    signals: ["目标 API 和依赖 SDK 是否兼容", "敏感权限是否仍有真实使用场景", "崩溃率、ANR 和核心路径是否在测试中稳定"],
    actions: ["建立 targetSdk 升级兼容清单", "删除历史遗留权限并更新数据安全表单", "用封闭测试记录核心路径和崩溃修复"],
    evidence: "证据口径来自 ADXJ 对 Google Play 老应用更新、目标 API 升级和 SDK 合规案例的整理。",
  },
  {
    title: "Google Play 生产访问没过，封闭测试反馈怎么写才像真的？",
    slug: "google-play-production-access-feedback-quality-plan",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 生产访问审核看的是测试质量，不是人数截图；反馈要覆盖核心任务、崩溃、留存和修复记录。",
    keywords: ["Google Play 生产访问", "封闭测试反馈", "Android 新账号", "测试质量", "上架审核"],
    coverImage: "/insights/google-play-closed-testing-production-access-fix.png",
    coverAlt: "Google Play 生产访问封闭测试反馈质量计划示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "封闭测试只凑人数和截图，没有证明真实用户完成过核心任务",
    audience: "新 Google Play 开发者账号、首个 Android 应用和封闭测试卡住的团队",
    answer: "Google Play 生产访问没过时，要把封闭测试改成真实任务反馈：测试目标、用户路径、问题修复、崩溃数据和版本迭代都要能被解释。",
    signals: ["测试用户是否完成核心功能", "反馈是否包含具体设备、地区和路径", "版本更新是否对应真实修复记录"],
    actions: ["设计 5 到 8 个核心测试任务", "整理反馈、崩溃和修复时间线", "在生产访问申请中说明测试结论和改进动作"],
    evidence: "证据口径来自 ADXJ 对 Google Play 新账号生产访问和封闭测试质量案例的复盘。",
  },
  {
    title: "Google Play 团队权限混乱，会不会放大账号关联风险？",
    slug: "google-play-account-permission-team-risk-audit",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 团队权限混乱会让包体、后台、财务和账号操作难以追踪，多个应用矩阵更容易放大关联风险。",
    keywords: ["Google Play 权限", "开发者账号", "团队权限", "账号关联", "Android 风控"],
    coverImage: "/insights/google-play-association-risk-checklist.png",
    coverAlt: "Google Play 团队权限混乱和账号关联风险审计示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "团队成员共享登录、权限不分级、应用资产和操作记录缺少审计",
    audience: "运营多个 Android 应用、多个开发者账号或多地区包体的出海团队",
    answer: "Google Play 团队权限混乱会增加账号关联和误操作风险，应按角色拆分权限、固定登录环境、记录发布操作，并把高风险应用单独隔离管理。",
    signals: ["谁能上传包体和修改商店信息", "登录设备和网络环境是否混用", "隐私政策域名、SDK 配置和签名是否跨账号复用"],
    actions: ["按开发、运营、财务和审核角色重设权限", "建立发布操作日志和资产归属表", "把敏感品类账号与普通工具账号隔离"],
    evidence: "证据口径来自 ADXJ 对 Google Play 账号关联、团队权限和应用资产隔离案例的整理。",
  },
  {
    title: "Meta Ads 学习受限但 CPA 很高，是事件质量还是预算问题？",
    slug: "meta-ads-learning-limited-high-cpa-event-quality",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta Ads 学习受限且 CPA 高，常见原因是事件量不足、事件质量弱、预算拆太散或素材承诺和落地页不一致。",
    keywords: ["Meta Ads 学习受限", "CPA 高", "事件质量", "Pixel CAPI", "广告优化"],
    coverImage: "/insights/meta-advantage-plus-performance-drop-event-creative-fix.png",
    coverAlt: "Meta Ads 学习受限、CPA 高和事件质量排查示意图",
    markets: ["us", "europe"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告组长期学习受限，团队频繁调预算和素材，却没有判断事件质量是否足够",
    audience: "跑订阅、工具、AI 应用和跨境服务广告的 Meta 投放团队",
    answer: "Meta Ads 学习受限且 CPA 高时，先看转化事件数量和质量，再看预算是否过散；不要只靠换素材，应把 Pixel/CAPI、落地页和后端收入一起校准。",
    signals: ["每个广告组的有效转化量", "Pixel 与 CAPI 是否重复或漏记", "落地页和商店页是否承接素材承诺"],
    actions: ["合并过散预算并稳定观察周期", "校准 Pixel/CAPI 事件和后端订单", "保留能带来真实付费的素材并暂停低质点击素材"],
    evidence: "证据口径来自 ADXJ 对 Meta Ads 学习期、CAPI 事件和订阅应用投放复盘的服务经验。",
  },
  {
    title: "Meta CAPI 和 Pixel 重复记事件，ROAS 虚高怎么查？",
    slug: "meta-capi-pixel-duplicate-events-roas-audit",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta CAPI 与 Pixel 重复记事件会让 ROAS 看起来好看，但实际付款、退款和续费对不上，放量后风险更大。",
    keywords: ["Meta CAPI", "Pixel 重复事件", "ROAS 虚高", "事件去重", "广告归因"],
    coverImage: "/insights/meta-pixel-capi-event-tracking-roas-fix.png",
    coverAlt: "Meta CAPI 和 Pixel 重复事件导致 ROAS 虚高审计示意图",
    markets: ["us", "europe"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "前端 Pixel 和服务端 CAPI 同时回传购买事件，但缺少 event_id 去重或订单对账",
    audience: "已经接 CAPI、准备放量或发现广告后台和收入后台不一致的团队",
    answer: "Meta CAPI 和 Pixel ROAS 虚高要先查 event_id 去重、订单状态、退款和重复触发路径；只有广告后台与后端收入一致，才能继续放量。",
    signals: ["同一订单是否出现多次 purchase", "event_id 是否在 Pixel 与 CAPI 间一致", "退款、取消和续费是否进入对账表"],
    actions: ["抽样核对广告事件与订单数据库", "补齐去重字段和服务器回传规则", "用真实收入重算素材和广告组优先级"],
    evidence: "证据口径来自 ADXJ 对 Meta Pixel/CAPI、订阅收入和 ROAS 对账案例的整理。",
  },
  {
    title: "Meta 素材审核反复不过，放量前要查哪 7 个风险点？",
    slug: "meta-ads-creative-rejected-before-scale-checklist",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta 素材审核反复不过，可能是承诺过强、落地页不一致、品牌页信任弱、敏感词和素材授权证据不足。",
    keywords: ["Meta 素材审核", "广告拒审", "素材风控", "落地页一致性", "Meta Ads"],
    coverImage: "/insights/meta-ads-account-restricted-bm-landing-page-fix.png",
    coverAlt: "Meta 素材审核反复不过和放量前风险点清单示意图",
    markets: ["us", "europe"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "团队只改视频字幕或封面，没有同步检查落地页、主页、隐私政策和素材授权",
    audience: "准备在 Meta 放量、素材审核反复失败或账户稳定性差的出海团队",
    answer: "Meta 素材审核反复不过，要同时查素材承诺、敏感词、授权证明、落地页、主页内容、隐私入口和商店页一致性，而不是只换封面。",
    signals: ["素材是否承诺无法验证的结果", "落地页和商店页是否解释同一功能", "主页、域名和隐私政策是否有基础信任"],
    actions: ["按风险等级重做素材库标签", "把落地页补成产品、隐私和客服完整结构", "准备素材授权和业务说明用于申诉"],
    evidence: "证据口径来自 ADXJ 对 Meta 广告素材审核、BM 风控和落地页修复案例的整理。",
  },
  {
    title: "Meta BM、域名和主页信任度低，账户还能稳定跑吗？",
    slug: "meta-ads-bm-domain-page-trust-rebuild",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta 账户不稳定时，BM、主页、域名、支付方式、隐私政策和落地页信任度要一起看，不能只盯广告组。",
    keywords: ["Meta BM", "广告账户风控", "域名信任", "主页质量", "账户稳定"],
    coverImage: "/insights/meta-ads-account-restriction-audit.png",
    coverAlt: "Meta BM 域名主页信任度和账户稳定性重建示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告账户频繁受限，背后可能是主页内容空、域名新、支付异常或落地页信任不足",
    audience: "Meta Ads 账户经常审核慢、预算烧不动或一加预算就受限的团队",
    answer: "Meta 账户稳定性要从 BM、主页、域名、支付、落地页和素材共同修复；信任度没建立前，不建议频繁换素材或大幅加预算。",
    signals: ["主页是否有持续内容和客服入口", "域名、隐私政策和落地页是否稳定", "支付、账户角色和历史拒审是否异常"],
    actions: ["补齐主页内容、品牌信息和客服入口", "统一域名、隐私政策和落地页结构", "降低异常操作频率后分阶段恢复预算"],
    evidence: "证据口径来自 ADXJ 对 Meta BM、域名信任和广告账户受限案例的复盘。",
  },
  {
    title: "TikTok SPC 安装便宜但订阅低，首日事件怎么改？",
    slug: "tiktok-spc-install-cheap-subscription-low-fix",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok SPC 安装便宜但订阅低，多数是优化事件停在安装或注册，没有把首次价值行为和订阅意图喂给系统。",
    keywords: ["TikTok SPC", "安装便宜", "订阅转化", "事件回传", "AI 工具投放"],
    coverImage: "/insights/tiktok-smart-performance-campaign-ai-tool-event-fix.png",
    coverAlt: "TikTok SPC 安装便宜但订阅低和首日事件修复示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告系统找到大量便宜安装用户，但这些用户没有完成首次生成、保存、试用或购买",
    audience: "用 TikTok SPC 跑 AI 工具、订阅工具和移动应用冷启动的团队",
    answer: "TikTok SPC 安装便宜但订阅低，要把优化目标从安装推进到首次关键行为、试用和购买，并用首日漏斗判断素材是否带来真实意图。",
    signals: ["安装到首次关键行为的转化率", "素材对应的保存、试用和购买表现", "商店页与产品首屏是否接住素材承诺"],
    actions: ["补齐首日关键事件和订阅事件", "按素材维度复盘低价安装质量", "把预算转向能带来试用和购买的素材组"],
    evidence: "证据口径来自 ADXJ 对 TikTok SPC、AI 工具事件回传和订阅转化案例的整理。",
  },
  {
    title: "TikTok UGC 达人授权不清，Spark Ads 会不会被拒？",
    slug: "tiktok-ugc-authorization-spark-ads-risk-check",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok UGC 达人授权不清时，Spark Ads、二剪素材、白名单投放和跨地区复用都可能触发审核或版权风险。",
    keywords: ["TikTok UGC", "Spark Ads", "达人授权", "素材版权", "白名单投放"],
    coverImage: "/insights/tiktok-creator-creative-authorization-ugc-ads-fix.png",
    coverAlt: "TikTok UGC 达人授权和 Spark Ads 风险排查示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "团队拿到达人视频后直接剪辑投放，却没有明确使用范围、期限、地区和二次剪辑权限",
    audience: "依赖 UGC 素材、达人白名单和 Spark Ads 放量的 TikTok 投放团队",
    answer: "TikTok UGC 投放前要确认授权范围、使用期限、投放地区、二剪权限和账号白名单；授权不清的素材不建议进入放量池。",
    signals: ["授权文件是否写明广告用途和地区", "素材是否包含第三方音乐、人物或品牌", "Spark Ads 账号和投放主体是否一致"],
    actions: ["建立达人授权和素材来源台账", "把无授权或二剪不清素材移出放量池", "为高表现素材补齐白名单和续授权流程"],
    evidence: "证据口径来自 ADXJ 对 TikTok UGC、达人素材授权和广告审核案例的复盘。",
  },
  {
    title: "TikTok AI 视频素材疲劳太快，多久该换钩子和模板？",
    slug: "tiktok-ai-video-creative-fatigue-refresh-plan",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok AI 视频素材疲劳快，要按钩子、模板、首屏、旁白和落地页承诺分层刷新，而不是整条素材全部推倒重做。",
    keywords: ["TikTok 素材疲劳", "AI 视频素材", "创意刷新", "短视频投放", "素材测试"],
    coverImage: "/insights/tiktok-creative-fatigue-ai-video-signals.png",
    coverAlt: "TikTok AI 视频素材疲劳和创意刷新计划示意图",
    markets: ["us", "latam", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "素材前几天点击很好，随后 CTR、CVR 和订阅同时下滑，团队却不知道该改哪里",
    audience: "高频投放 AI 视频、AI 工具、SLOTS 或订阅应用的 TikTok 团队",
    answer: "TikTok AI 视频素材疲劳要按首屏钩子、演示模板、旁白承诺和落地页一致性拆开刷新，优先保留能带来付费的结构。",
    signals: ["CTR 下滑是否早于 CVR 下滑", "同模板不同钩子的留存和付费差异", "素材承诺是否仍与产品首日体验一致"],
    actions: ["建立素材组件拆分表", "每轮只改钩子、模板或旁白中的一类变量", "用订阅和退款数据淘汰虚高点击素材"],
    evidence: "证据口径来自 ADXJ 对 TikTok 素材疲劳、AI 视频创意和订阅应用投放复盘的服务经验。",
  },
  {
    title: "TikTok 落地页和商店页说法不一致，为什么点击不转安装？",
    slug: "tiktok-landing-store-message-match-audit",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 点击不转安装时，要检查短视频承诺、落地页文案、商店截图和应用首屏是否讲的是同一个用户任务。",
    keywords: ["TikTok 落地页", "商店页一致性", "点击不安装", "转化率", "广告漏斗"],
    coverImage: "/insights/tiktok-ads-clicks-no-payment-ai-tool-funnel.png",
    coverAlt: "TikTok 落地页和商店页信息不一致转化排查示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "素材吸引的是一个需求，落地页和商店页却展示另一个功能，用户到安装前就失去信任",
    audience: "TikTok 点击率高但安装率、注册率或付费率持续偏低的应用团队",
    answer: "TikTok 点击不转安装时，要把素材钩子、落地页标题、商店前三张截图和应用首屏统一到同一个任务，不一致会直接拉低转化。",
    signals: ["点击到商店访问的跳失率", "商店截图是否承接素材里的核心结果", "安装后首屏是否让用户立刻完成同一任务"],
    actions: ["按素材主题重写落地页首屏", "调整商店截图顺序和关键词", "在产品新手路径里优先展示广告承诺的功能"],
    evidence: "证据口径来自 ADXJ 对 TikTok 落地页、商店页一致性和应用漏斗转化案例的整理。",
  },
  {
    title: "Telegram Ads 有点击没咨询，Bot 分流是不是挡住高意向用户？",
    slug: "telegram-ads-clicks-no-consultation-bot-routing",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram Ads 有点击没咨询，常见原因是 Bot 问题太多、人工入口太深、群欢迎语和服务承诺不一致。",
    keywords: ["Telegram Ads", "Telegram Bot", "有点击没咨询", "私域转化", "线索分流"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Ads 有点击没咨询和 Bot 分流排查示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "社群与私域服务",
    servicePath: "/community",
    problem: "广告把用户带到 Telegram，但 Bot 和群入口没有快速识别高意向需求",
    audience: "用 Telegram 承接出海服务、网盟、SLOTS、现金贷或 B2B 咨询的团队",
    answer: "Telegram Ads 有点击没咨询，要先看 Bot 分流问题数量、人工入口位置和欢迎语承诺；高意向用户应该在三步内进入人工。",
    signals: ["点击到进群和私聊的比例", "Bot 第几个问题开始明显流失", "人工客服首次响应时间和话术质量"],
    actions: ["把 Bot 首轮问题缩短到 3 个以内", "为高风险需求设置人工优先入口", "同步广告文案、欢迎语和案例链接"],
    evidence: "证据口径来自 ADXJ 对 Telegram Ads、Bot 承接和私域咨询转化案例的复盘。",
  },
  {
    title: "Telegram 社群冷启动没人说话，内容节奏怎么排才有信任？",
    slug: "telegram-community-cold-start-content-trust-plan",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram 社群冷启动时，不能只发广告，要用案例、FAQ、风险提醒、服务边界和人工互动建立信任。",
    keywords: ["Telegram 社群", "社群冷启动", "私域运营", "内容节奏", "信任转化"],
    coverImage: "/insights/telegram-private-traffic-community-conversion.png",
    coverAlt: "Telegram 社群冷启动内容节奏和信任建设示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "社群与私域服务",
    servicePath: "/community",
    problem: "群里只有广告、报价和转发内容，用户看不到真实案例和服务边界，自然不会开口咨询",
    audience: "刚启动 Telegram 私域、频道或社群承接的出海服务团队",
    answer: "Telegram 社群冷启动要先排 7 天内容节奏：案例、FAQ、避坑、服务边界、用户问题和人工回应穿插发布，不能只发广告。",
    signals: ["新用户进群后 24 小时是否有互动", "FAQ 和案例是否覆盖主要需求", "管理员是否及时回应高意向问题"],
    actions: ["建立 7 天固定内容栏目", "把热门问题沉淀成置顶 FAQ 和文章链接", "设置人工值班和线索标签"],
    evidence: "证据口径来自 ADXJ 对 Telegram 社群运营、私域内容和咨询转化路径的服务经验。",
  },
  {
    title: "Telegram Bot 表单太长，线索为什么会在预算问题前流失？",
    slug: "telegram-bot-form-dropoff-high-intent-leads",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram Bot 表单太长会让高意向线索流失，预算、地区和当前问题要优先问，资料收集应放到人工后。",
    keywords: ["Telegram Bot 表单", "线索流失", "高意向用户", "私域客服", "咨询转化"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Bot 表单过长导致高意向线索流失示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "社群与私域服务",
    servicePath: "/community",
    problem: "Bot 先问公司、邮箱、预算、地区、品类和备注，用户还没看到人工入口就离开",
    audience: "用 Bot 做线索筛选、客服分流和 Telegram 私域咨询的团队",
    answer: "Telegram Bot 表单太长时，应把首轮问题缩到当前问题、目标地区和是否需要人工三项；预算和资料可在人工确认后再补。",
    signals: ["每个问题后的回复率", "高意向关键词是否被及时识别", "人工接入前用户等待时间"],
    actions: ["删除首轮非必要字段", "为封号、拒审、放量失败等需求设置直达人工", "用标签记录预算和地区而不是一开始强制填写"],
    evidence: "证据口径来自 ADXJ 对 Telegram Bot、客服分流和高意向线索承接案例的整理。",
  },
  {
    title: "Telegram 私域客服回复慢，会怎样影响广告投放 ROI？",
    slug: "telegram-private-domain-customer-response-sla",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram 私域客服回复慢会拉低咨询转化和广告 ROI，尤其是账号封禁、审核被拒、投放异常等高紧急需求。",
    keywords: ["Telegram 私域", "客服响应", "广告 ROI", "咨询转化", "SLA"],
    coverImage: "/insights/telegram-community-customer-response-conversion-fix.png",
    coverAlt: "Telegram 私域客服响应慢影响广告 ROI 排查示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "社群与私域服务",
    servicePath: "/community",
    problem: "广告带来的线索进入 Telegram 后没人及时接，用户转向其他服务商或不再回复",
    audience: "依赖 Telegram 私域承接广告咨询、账号服务和网盟合作的团队",
    answer: "Telegram 私域客服响应要按需求紧急度设置 SLA；账号、审核、投放和结算类高意向线索应在 10 分钟内被人工接住。",
    signals: ["首次响应时间和二次回复率", "广告点击到人工咨询的转化率", "不同需求标签的成交和流失数据"],
    actions: ["设置高意向关键词提醒和人工值班表", "把常见问题做成快捷回复和案例链接", "按来源渠道复盘客服响应对 ROI 的影响"],
    evidence: "证据口径来自 ADXJ 对 Telegram 私域客服、广告线索和出海咨询成交路径的复盘。",
  },
  {
    title: "AI 伴侣 App 上架和订阅都要过，内容安全怎么前置？",
    slug: "ai-companion-store-review-safety-subscription",
    category: "出海企业洞察",
    topic: "ai-apps",
    excerpt: "AI 伴侣 App 既要过商店审核，又要做订阅增长，内容安全、角色设定、举报入口和付费边界必须前置设计。",
    keywords: ["AI 伴侣", "AI App 上架", "内容安全", "订阅增长", "审核合规"],
    coverImage: "/insights/ai-companion-app-overseas-review-ads-subscription.png",
    coverAlt: "AI 伴侣 App 上架内容安全和订阅边界设计示意图",
    markets: ["us", "europe"],
    serviceName: "AI 应用出海服务",
    servicePath: "/developer",
    problem: "AI 伴侣产品把增长和合规分开做，容易出现素材能点、审核不稳、订阅投诉增加的情况",
    audience: "正在做 AI 伴侣、AI 聊天、虚拟角色和情绪陪伴应用的团队",
    answer: "AI 伴侣 App 要把内容安全、角色边界、举报入口、年龄分级和订阅说明前置到上架与投放前，否则审核和退款会反复影响增长。",
    signals: ["角色设定是否存在高风险表达", "举报、拉黑和内容过滤入口是否清楚", "订阅页是否解释免费和付费能力差异"],
    actions: ["重写角色介绍和商店截图表达", "补齐举报、内容过滤和年龄分级说明", "把订阅权益与安全边界一起展示"],
    evidence: "证据口径来自 ADXJ 对 AI 伴侣、内容安全、商店审核和订阅转化案例的整理。",
  },
  {
    title: "AI 视频 App 模板等待太久，为什么下载高但订阅低？",
    slug: "ai-video-app-template-waiting-time-conversion",
    category: "出海企业洞察",
    topic: "ai-apps",
    excerpt: "AI 视频 App 下载高但订阅低，常见原因是模板等待、生成失败、首日结果不稳定和订阅墙出现太早。",
    keywords: ["AI 视频 App", "订阅转化", "模板等待", "生成失败", "首日体验"],
    coverImage: "/insights/ai-image-to-video-app-download-high-subscription-low.png",
    coverAlt: "AI 视频 App 模板等待时间和订阅转化排查示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "AI 应用出海服务",
    servicePath: "/developer",
    problem: "广告和商店页吸引用户下载，但用户第一次生成等待太久或结果不稳定，订阅意愿快速下降",
    audience: "做 AI 图生视频、模板视频、头像视频和订阅工具的应用团队",
    answer: "AI 视频 App 下载高但订阅低时，要先查首日生成成功率、等待时间和免费样例质量，再决定订阅墙位置和素材承诺。",
    signals: ["首次生成成功率和平均等待时间", "失败用户是否再次尝试", "素材展示结果是否超过真实模板能力"],
    actions: ["优化首个免费模板和生成排队提示", "把订阅墙后移到用户看到结果之后", "按模板维度复盘退款和留存"],
    evidence: "证据口径来自 ADXJ 对 AI 视频、图生视频和订阅漏斗优化案例的服务经验。",
  },
  {
    title: "AI 换脸广告被拒，用户同意和举报入口要放在哪里？",
    slug: "ai-face-swap-consent-reporting-ads-review",
    category: "出海企业洞察",
    topic: "ai-apps",
    excerpt: "AI 换脸广告和上架审核容易卡在用户同意、素材来源、举报入口、内容安全和误导性展示。",
    keywords: ["AI 换脸", "广告拒审", "用户同意", "内容安全", "举报入口"],
    coverImage: "/insights/ai-face-swap-ads-rejected-consent-landing-page-fix.png",
    coverAlt: "AI 换脸用户同意、举报入口和广告审核排查示意图",
    markets: ["us", "europe"],
    serviceName: "AI 应用出海服务",
    servicePath: "/developer",
    problem: "广告素材强调强效果，但页面没有说明用户同意、素材来源和违规内容处理方式",
    audience: "AI 换脸、AI 头像、AI 写真和人物生成类应用团队",
    answer: "AI 换脸广告被拒时，要把用户授权、素材来源、生成限制、举报入口和删除路径放在落地页与应用内关键位置，不能只靠隐私政策兜底。",
    signals: ["素材是否暗示未经同意使用他人形象", "落地页是否展示 consent 和举报入口", "应用内是否能删除生成内容和账号数据"],
    actions: ["重写广告素材和落地页合规提示", "在上传前加入用户授权确认", "补齐举报、删除和内容审核机制"],
    evidence: "证据口径来自 ADXJ 对 AI 换脸、人物生成、广告审核和内容安全案例的整理。",
  },
  {
    title: "AI 写作 App 退款率升高，是免费试用还是结果质量问题？",
    slug: "ai-writing-app-free-trial-refund-risk-fix",
    category: "出海企业洞察",
    topic: "ai-apps",
    excerpt: "AI 写作 App 退款率升高，通常要同时查免费试用说明、结果质量、任务模板、订阅页和用户预期。",
    keywords: ["AI 写作 App", "退款率", "免费试用", "订阅转化", "结果质量"],
    coverImage: "/insights/ai-writing-app-refund-rate-subscription-fix.png",
    coverAlt: "AI 写作 App 免费试用和退款风险排查示意图",
    markets: ["us", "europe"],
    serviceName: "AI 应用出海服务",
    servicePath: "/developer",
    problem: "用户被广告吸引试用，但输出质量、模板匹配和订阅说明没有达到预期",
    audience: "AI 写作、AI 邮件、AI 简历和文案生成类订阅应用团队",
    answer: "AI 写作 App 退款升高要按来源素材、任务模板、首次输出质量、试用权益和取消路径拆解，先修预期差再扩大买量。",
    signals: ["退款用户来自哪些素材和关键词", "首次生成是否解决用户真实任务", "订阅页是否清楚说明试用和取消方式"],
    actions: ["按任务场景重做模板和素材承诺", "优化首次输出质量和编辑路径", "重写试用、价格和取消说明"],
    evidence: "证据口径来自 ADXJ 对 AI 写作、订阅退款和素材承诺复盘的服务经验。",
  },
  {
    title: "SLOTS 软启动选市场，CPI 低就一定值得测吗？",
    slug: "slots-soft-launch-market-cpi-payment-risk",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 软启动选市场不能只看 CPI，还要看支付成功率、首充、留存、风控、素材审核和回本周期。",
    keywords: ["SLOTS 软启动", "CPI", "支付风险", "首充", "市场选择"],
    coverImage: "/insights/slots-overseas-ua-cost-market-risk.png",
    coverAlt: "SLOTS 软启动市场 CPI 支付风险和首充转化评估示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "团队看到某个市场 CPI 便宜就加预算，但支付、留存和审核风险没有同步验证",
    audience: "准备做 SLOTS、iGaming 或游戏出海软启动的团队",
    answer: "SLOTS 软启动选市场不能只看 CPI；应同时比较支付成功率、首充率、Day1/Day7 留存、素材审核和回本周期，再决定是否放量。",
    signals: ["CPI 与首充成本的差距", "支付失败和拒付风险", "素材审核和地区政策限制"],
    actions: ["建立市场评分表而不是只排 CPI", "小预算验证首充、留存和支付路径", "按地区准备素材、落地页和支付方案"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 出海、买量市场选择和支付漏斗复盘的服务经验。",
  },
  {
    title: "SLOTS 首充漏斗掉得快，是支付方式还是新手路径问题？",
    slug: "slots-first-deposit-funnel-payment-method-fix",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 首充漏斗掉得快，要同时查支付方式、充值档位、奖励展示、新手任务和地区支付习惯。",
    keywords: ["SLOTS 首充", "支付漏斗", "充值转化", "新手路径", "支付方式"],
    coverImage: "/insights/slots-payment-funnel-dropoff-region-channel-fix.png",
    coverAlt: "SLOTS 首充漏斗支付方式和新手路径排查示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "用户完成注册和新手任务，却在充值页、支付方式或奖励理解环节流失",
    audience: "SLOTS、iGaming 和游戏买量团队",
    answer: "SLOTS 首充漏斗掉得快时，先按地区拆支付方式、充值档位、奖励展示和新手任务；不要只把问题归因于用户质量。",
    signals: ["充值页曝光到支付发起的比例", "不同支付方式的成功率", "奖励说明是否被用户理解"],
    actions: ["按地区排序支付方式和充值档位", "简化首充奖励文案和新手任务", "用渠道维度复盘首充和拒付数据"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 支付漏斗、首充转化和地区支付习惯案例的整理。",
  },
  {
    title: "SLOTS Day7 ROI 起不来，素材和地区预算怎么重新分配？",
    slug: "slots-day7-roi-creative-region-budget-plan",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS Day7 ROI 起不来，可能是素材带来低质量用户、地区预算过散、首充弱或支付渠道影响回收。",
    keywords: ["SLOTS Day7 ROI", "素材预算", "买量回本", "地区投放", "游戏 ROI"],
    coverImage: "/insights/slots-payback-cycle-region-creative-roi.png",
    coverAlt: "SLOTS Day7 ROI 素材地区和预算重分配示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告前端成本看似可控，但 Day7 收入、复充和留存无法支撑继续放量",
    audience: "正在复盘 SLOTS 买量回本、素材质量和地区预算的投放团队",
    answer: "SLOTS Day7 ROI 起不来，要把素材、地区、首充、复充和支付成功率放在同一张表里看，预算应转向回收稳定的组合。",
    signals: ["素材维度的首充和复充表现", "地区维度的支付成功率和 Day7 ROI", "预算调整是否过快导致模型重置"],
    actions: ["按素材和地区交叉计算 ROI", "暂停低首充高消耗组合", "把预算集中到支付稳定且复充更好的地区"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 买量、Day7 ROI 和素材地区预算复盘的服务经验。",
  },
  {
    title: "SLOTS 商店页写 Bonus，落地页写 Jackpot，会影响转化吗？",
    slug: "slots-store-page-landing-bonus-mismatch-audit",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 商店页、落地页和广告素材的 Bonus、Jackpot、免费筹码表达不一致，会影响审核、点击信任和首充转化。",
    keywords: ["SLOTS 商店页", "落地页一致性", "Bonus", "Jackpot", "首充转化"],
    coverImage: "/insights/slots-landing-page-store-page-mismatch-roi-fix.png",
    coverAlt: "SLOTS 商店页和落地页 Bonus Jackpot 表达不一致排查示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告、落地页和商店页分别强调不同奖励，用户进入后不知道真实权益是什么",
    audience: "SLOTS 和 iGaming 应用做广告承接、商店页优化和首充转化的团队",
    answer: "SLOTS 商店页和落地页奖励表达必须一致；Bonus、Jackpot、免费筹码和充值权益要有清楚边界，否则会降低信任和首充转化。",
    signals: ["广告承诺和商店截图是否一致", "奖励规则是否有地区限制和有效期", "首充页是否解释实际可得权益"],
    actions: ["统一素材、落地页和商店页奖励词", "补齐奖励规则、限制和客服入口", "用 A/B 测试验证首充转化而不是只看 CTR"],
    evidence: "证据口径来自 ADXJ 对 SLOTS 商店页一致性、奖励文案和首充漏斗案例的整理。",
  },
  {
    title: "现金贷落地页费用披露不清，广告和商店审核都会卡吗？",
    slug: "cash-loan-fee-disclosure-landing-page-review",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷落地页费用披露不清，会影响广告审核、商店审核、用户投诉和渠道质量，不能只靠小字说明。",
    keywords: ["现金贷落地页", "费用披露", "金融广告审核", "贷款 App", "广告拒审"],
    coverImage: "/insights/cash-loan-landing-page-fee-disclosure-ads-complaint-fix.png",
    coverAlt: "现金贷落地页费用披露和广告审核排查示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "落地页只强调快速放款和高额度，却没有清楚展示费用、期限、APR、资格和风险提示",
    audience: "现金贷、金融 App、贷超和获客团队",
    answer: "现金贷落地页费用披露不清会同时影响广告审核和用户投诉；费用、期限、APR、资格、示例和风险提示应在首屏或关键路径可见。",
    signals: ["广告文案是否夸大额度和速度", "落地页是否展示费用示例和风险提示", "商店页、隐私政策和客服入口是否完整"],
    actions: ["重写首屏费用披露和资格说明", "同步广告素材、落地页和商店页承诺", "按地区政策补齐风险提示和客服路径"],
    evidence: "证据口径来自 ADXJ 对现金贷广告审核、费用披露和用户投诉案例的服务经验。",
  },
  {
    title: "现金贷渠道进件多首还低，是流量问题还是风控问题？",
    slug: "cash-loan-channel-quality-first-repayment-audit",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷渠道进件多但首还低，要拆解来源、授信、放款、首还、逾期和渠道激励，不能只看 CPL。",
    keywords: ["现金贷渠道质量", "首还率", "进件质量", "金融风控", "获客渠道"],
    coverImage: "/insights/cash-loan-channel-high-applications-low-repayment-fix.png",
    coverAlt: "现金贷渠道进件多首还低和流量质量审计示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "渠道带来大量低成本进件，但授信、放款和首还表现不支持继续扩量",
    audience: "现金贷出海、贷超、CPA 渠道和金融广告投放团队",
    answer: "现金贷进件多首还低时，要把渠道来源、授信通过、放款、首还和逾期一起看；低 CPL 不能代表高质量获客。",
    signals: ["渠道维度的授信和放款率", "首还、逾期和拒付分布", "渠道激励是否诱导低质量用户"],
    actions: ["按渠道建立质量分层和黑名单", "把首还和逾期数据回传给投放系统", "调整 CPA 结算和质量门槛"],
    evidence: "证据口径来自 ADXJ 对现金贷渠道质量、首还率和金融获客风控案例的整理。",
  },
  {
    title: "现金贷广告被拒，资质证明和风险提示要怎么准备？",
    slug: "cash-loan-ads-rejected-policy-proof-checklist",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷广告被拒时，平台通常会看地区资质、费用披露、风险提示、落地页一致性和用户数据处理。",
    keywords: ["现金贷广告拒审", "金融广告资质", "风险提示", "贷款 App 审核", "广告合规"],
    coverImage: "/insights/cash-loan-app-ads-rejected-compliance-funnel-fix.png",
    coverAlt: "现金贷广告拒审资质证明和风险提示清单示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "广告素材、落地页和资质材料没有清楚解释业务主体、费用和用户风险",
    audience: "现金贷、金融广告、贷款聚合和出海获客团队",
    answer: "现金贷广告被拒要先准备地区资质、费用示例、风险提示、隐私政策和客服入口，再检查素材是否夸大审批速度或额度。",
    signals: ["目标地区是否需要牌照或主体证明", "素材是否包含误导性额度和放款承诺", "落地页是否可见费用、期限和投诉渠道"],
    actions: ["建立广告审核资质包和落地页版本库", "删除过度承诺并补齐风险提示", "按地区拆分素材和投放账户策略"],
    evidence: "证据口径来自 ADXJ 对现金贷广告审核、金融资质和落地页合规案例的整理。",
  },
  {
    title: "现金贷新市场放量前，牌照、支付和催收风险怎么先评估？",
    slug: "cash-loan-new-market-license-risk-before-scale",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷进入新市场前，要先评估牌照、支付、数据合规、催收边界、获客成本和首还质量，再决定预算。",
    keywords: ["现金贷新市场", "牌照风险", "支付通道", "催收合规", "出海金融"],
    coverImage: "/insights/cash-loan-overseas-growth-compliance.png",
    coverAlt: "现金贷新市场牌照支付和催收风险评估示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "海外投放增长服务",
    servicePath: "/media",
    problem: "团队看到某个地区获客便宜就准备放量，但牌照、支付和贷后风险还没有验证",
    audience: "现金贷出海、金融科技、贷超和新市场增长团队",
    answer: "现金贷新市场放量前，要先做牌照、支付、数据、催收和首还质量评估；获客便宜但回款不可控的市场不适合快速扩量。",
    signals: ["当地牌照和广告政策要求", "支付通道成功率和拒付风险", "首还、逾期和催收合规边界"],
    actions: ["用小预算样本验证完整贷前贷后链路", "建立市场风险评分和退出条件", "把合规、支付和渠道质量纳入放量决策"],
    evidence: "证据口径来自 ADXJ 对现金贷新市场、获客成本和贷后风险评估案例的整理。",
  },
  {
    title: "CPA Offer 放量被 Cap 卡住，Pacing 和质量反馈怎么调？",
    slug: "cpa-offer-cap-pacing-quality-feedback",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "CPA Offer 放量被 Cap 卡住时，要同时看广告主质量反馈、Pacing 节奏、转化时间和流量来源透明度。",
    keywords: ["CPA Offer", "Cap", "Pacing", "质量反馈", "海外网盟"],
    coverImage: "/insights/cpa-offer-scaling-cap-pacing-quality-feedback-fix.png",
    coverAlt: "CPA Offer 放量 Cap Pacing 和质量反馈调整示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外网盟与流量主服务",
    servicePath: "/media",
    problem: "流量主有量但拿不到更多 Cap，广告主担心后端质量、作弊和回收周期",
    audience: "CPA 网盟、流量主、Affiliate 团队和广告主 BD",
    answer: "CPA Offer 放量被 Cap 卡住时，要用质量反馈、转化时间、来源透明度和 Pacing 记录证明流量稳定，而不是只要求提高日限额。",
    signals: ["广告主后端留存或付费反馈", "小时级转化是否异常集中", "流量来源和素材是否透明可追踪"],
    actions: ["按小时和来源拆分转化质量", "与广告主约定质量反馈字段", "用稳定 Pacing 换取逐步加 Cap"],
    evidence: "证据口径来自 ADXJ 对 CPA Offer、Cap、Pacing 和广告主质量反馈案例的整理。",
  },
  {
    title: "Postback 丢转化，流量主结算少了该怎么查？",
    slug: "postback-missing-conversions-affiliate-audit",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Postback 丢转化会直接影响流量主结算，常见原因是 click_id、回传延迟、去重规则和归因窗口不一致。",
    keywords: ["Postback", "丢转化", "流量主结算", "click_id", "CPA 网盟"],
    coverImage: "/insights/publisher-api-integration-lost-conversions-postback-audit.png",
    coverAlt: "Postback 丢转化和流量主结算审计示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外网盟与流量主服务",
    servicePath: "/media",
    problem: "流量主后台看到点击和转化线索，广告主或网盟后台却没有对应结算",
    audience: "CPA 流量主、网盟技术、Affiliate 运营和广告主对接团队",
    answer: "Postback 丢转化要先查 click_id、回传地址、状态码、延迟、去重和归因窗口；只看一边后台无法判断责任。",
    signals: ["点击日志是否完整保存 click_id", "Postback 响应状态码和重试记录", "广告主归因窗口和去重规则是否变更"],
    actions: ["抽样对齐点击、转化和回传日志", "补充失败重试和状态码监控", "与广告主确认归因窗口和扣量口径"],
    evidence: "证据口径来自 ADXJ 对 Postback、API 对接和 CPA 结算争议案例的整理。",
  },
  {
    title: "CPA Day0 结算诱人，但反作弊门槛怎么提前谈清？",
    slug: "cpa-day0-settlement-fraud-threshold-plan",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "CPA Day0 结算能提升现金流，但反作弊、留存、退款、重复线索和扣量门槛必须提前写清楚。",
    keywords: ["CPA Day0", "反作弊", "结算门槛", "扣量", "流量主变现"],
    coverImage: "/insights/publisher-day0-settlement-advertiser-quality-thresholds.png",
    coverAlt: "CPA Day0 结算反作弊门槛和扣量规则示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外网盟与流量主服务",
    servicePath: "/media",
    problem: "流量主看重 Day0 现金流，但广告主后端质量和反作弊规则没有提前约定",
    audience: "做 CPA 结算、流量主变现、网盟发行和 Offer 对接的团队",
    answer: "CPA Day0 结算前要写清反作弊、重复线索、留存、退款、无效转化和扣量申诉口径，否则高结算速度会变成争议来源。",
    signals: ["无效转化定义是否明确", "广告主质量反馈频率和字段", "扣量申诉证据是否可追踪"],
    actions: ["把反作弊和扣量规则写进合作前置文档", "建立 Day0 与后端质量的对账表", "设置异常来源暂停和复核机制"],
    evidence: "证据口径来自 ADXJ 对 CPA Day0 结算、反作弊和广告主质量门槛案例的整理。",
  },
  {
    title: "流量主来源不透明，CPA 广告主为什么不愿意加预算？",
    slug: "publisher-traffic-source-transparency-checklist",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "流量主来源不透明会让广告主无法判断质量，CPA 放量前要说明渠道、素材、地区、设备和转化路径。",
    keywords: ["流量主", "CPA 放量", "来源透明", "广告主预算", "网盟质量"],
    coverImage: "/insights/overseas-cpa-traffic-fraud-detection-checklist.png",
    coverAlt: "CPA 流量主来源透明度和广告主预算信任清单示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "海外网盟与流量主服务",
    servicePath: "/media",
    problem: "广告主只看到转化数量，看不到真实来源、素材和用户路径，因此不敢给更高预算",
    audience: "希望拿到更多预算、更多 Offer 或更高 Cap 的 CPA 流量主",
    answer: "CPA 流量主想拿更多预算，要提高来源透明度：渠道类型、地区、素材、设备、转化路径和异常处理都要能解释。",
    signals: ["来源字段是否能到渠道或素材层级", "转化分布是否过于集中或异常", "广告主是否能收到稳定质量反馈"],
    actions: ["建立来源透明度清单和样例报表", "按渠道提供转化质量和异常说明", "用可解释数据争取更高 Cap 和预算"],
    evidence: "证据口径来自 ADXJ 对 CPA 流量主变现、广告主预算和反作弊沟通案例的复盘。",
  },
  {
    title: "ASO 本地化关键词怎么选？美国、东南亚、拉美不要共用一套词",
    slug: "aso-keyword-localization-us-sea-latam",
    category: "开发者出海",
    topic: "aso",
    excerpt: "ASO 本地化关键词不能直接翻译，美国、东南亚、拉美用户搜索习惯、竞品词和截图卖点都不同。",
    keywords: ["ASO 本地化", "关键词优化", "美国市场", "东南亚 ASO", "拉美 ASO"],
    coverImage: "/insights/aso-localization-keywords-us-sea-latam-case.png",
    coverAlt: "ASO 本地化关键词美国东南亚拉美市场选择示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "团队把中文或英文关键词直接翻译到多个市场，导致曝光弱、点击低和用户意图不匹配",
    audience: "准备做 App Store、Google Play 多市场 ASO 和自然量增长的应用团队",
    answer: "ASO 本地化关键词要按市场重选，不要共用一套翻译词；美国看任务和品牌，东南亚看场景和价格，拉美要看本地表达和竞品词。",
    signals: ["不同地区的搜索词和竞品排名", "标题、副标题和截图是否匹配本地意图", "自然量和付费素材是否传递同一卖点"],
    actions: ["按市场建立关键词池和竞品词表", "重写标题、副标题和前三张截图", "用 GSC、商店后台和投放词复盘自然量变化"],
    evidence: "证据口径来自 ADXJ 对 ASO 本地化、关键词和多市场自然量增长案例的整理。",
  },
  {
    title: "App Store 关键词排名起不来，买量信号能不能帮 ASO？",
    slug: "app-store-keyword-ranking-paid-signal-aso",
    category: "开发者出海",
    topic: "aso",
    excerpt: "App Store 关键词排名起不来时，买量信号、商店页点击率、安装质量和留存会一起影响自然量冷启动。",
    keywords: ["App Store 关键词排名", "ASO", "买量信号", "自然量", "商店页转化"],
    coverImage: "/insights/app-launch-no-organic-traffic-aso.png",
    coverAlt: "App Store 关键词排名和买量信号协同 ASO 示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "应用上线后关键词覆盖少、自然量弱，团队只改关键词却没有同步改善商店页和安装质量",
    audience: "新应用冷启动、订阅工具、AI 应用和效率 App 的增长团队",
    answer: "App Store 关键词排名起不来时，买量可以提供安装和行为信号，但前提是商店页 CTR、安装质量和留存足够稳定。",
    signals: ["关键词曝光到商店页点击率", "买量用户安装后留存和转化", "截图和标题是否覆盖同一搜索意图"],
    actions: ["把买量关键词和 ASO 关键词分层对齐", "优化商店页前三张截图和副标题", "用留存和订阅数据筛掉低质量买量信号"],
    evidence: "证据口径来自 ADXJ 对 App Store ASO、买量信号和自然量冷启动案例的复盘。",
  },
  {
    title: "Google Play 短描述点击低，ASO 要先改关键词还是卖点？",
    slug: "google-play-aso-short-description-conversion",
    category: "开发者出海",
    topic: "aso",
    excerpt: "Google Play 短描述点击低，通常不是关键词一个问题，还要看首屏卖点、评分、截图、地区语言和安装意图。",
    keywords: ["Google Play ASO", "短描述", "商店页转化", "关键词优化", "Android 自然量"],
    coverImage: "/insights/google-ads-utility-app-cost-rising-keyword-value-fix.png",
    coverAlt: "Google Play 短描述点击低和 ASO 转化优化示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "短描述堆关键词但没有说清用户为什么现在要安装，导致曝光有了也难转化",
    audience: "Google Play 自然量弱、商店页转化低和 Android 工具应用团队",
    answer: "Google Play 短描述点击低时，要先确认用户核心任务和首屏卖点，再把关键词自然嵌入；只堆词会降低点击和安装意图。",
    signals: ["短描述是否回答用户核心任务", "截图首屏是否展示同一卖点", "不同地区语言和评分是否影响点击"],
    actions: ["重写短描述为任务型卖点", "同步截图首屏和长描述结构", "按地区监控曝光、点击和安装变化"],
    evidence: "证据口径来自 ADXJ 对 Google Play ASO、短描述和商店页转化案例的整理。",
  },
  {
    title: "品牌词被竞品抢量，ASO 和广告要怎么一起防守？",
    slug: "aso-brand-defense-competitor-keyword-plan",
    category: "开发者出海",
    topic: "aso",
    excerpt: "品牌词被竞品抢量时，不能只加广告预算，要用 ASO、品牌内容、商店页转化和搜索广告一起防守。",
    keywords: ["品牌词防守", "ASO", "竞品关键词", "搜索广告", "商店页转化"],
    coverImage: "/insights/brand-keyword-defense-overseas-seo-ads-strategy.png",
    coverAlt: "品牌词被竞品抢量的 ASO 和广告防守策略示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    problem: "用户搜索品牌词后看到竞品广告或相似应用，团队只靠加价防守导致成本持续上升",
    audience: "已有品牌搜索量、竞品投放压力和自然量波动的应用团队",
    answer: "品牌词被竞品抢量时，要同时做 ASO 品牌一致性、搜索广告防守、内容页解释和商店页转化，不能只靠提高出价。",
    signals: ["品牌词展示、点击和安装变化", "竞品广告是否截流核心关键词", "商店页评分、截图和标题是否强化品牌识别"],
    actions: ["建立品牌词和竞品词监控表", "优化商店页品牌识别和第一屏卖点", "用搜索广告防守高价值品牌词并控制成本"],
    evidence: "证据口径来自 ADXJ 对 ASO 品牌词、防守广告和竞品搜索截流案例的整理。",
  },
];

export const dailySeoArticles20260628: InsightArticle[] = seeds.map(dailyGeoArticle);
