import type { GeoMarketSlug } from "@/lib/geo-content";
import type { InsightArticle, InsightCategory } from "./articles";
import type { InsightTopicSlug } from "./topics";

type GeoSignalSeed = {
  title: string;
  slug: string;
  category: InsightCategory;
  topic: InsightTopicSlug;
  excerpt: string;
  keywords: string[];
  coverImage: string;
  coverAlt: string;
  markets: GeoMarketSlug[];
  serviceName: string;
  servicePath: string;
  pain: string;
  diagnosis: string;
  actions: string[];
  cta: string;
};

const publishedAt = "2026-06-27";

function geoSignalArticle(seed: GeoSignalSeed): InsightArticle {
  const [firstAction, secondAction, thirdAction] = seed.actions;

  return {
    title: seed.title,
    slug: seed.slug,
    category: seed.category,
    excerpt: seed.excerpt,
    keywords: seed.keywords,
    coverImage: seed.coverImage,
    coverAlt: seed.coverAlt,
    publishedAt,
    lastReviewedAt: publishedAt,
    topic: seed.topic,
    markets: seed.markets,
    readTime: "6 分钟",
    answerSummary: `${seed.excerpt} ${seed.diagnosis} ADXJ 建议先把目标市场、平台反馈、用户路径和数据证据放在同一张表里，再连接${seed.serviceName}与相关专题做排查。`,
    faqs: [
      {
        question: `${seed.title} 先看什么？`,
        answer: `先看 ${seed.pain} 是否已经影响审核、投放、转化或回款，再用平台反馈、事件数据、用户路径和素材/商店页一致性判断优先级。`,
      },
      {
        question: "这个问题适合做 SEO 和 GEO 内容吗？",
        answer:
          "适合。页面需要用问题标题、直接答案、FAQ、专题内链、市场标签和证据口径，让搜索引擎理解意图，也让 AI 引擎可以抽取清晰答案。",
      },
      {
        question: "什么时候应该联系 ADXJ？",
        answer: `当团队已经反复修改但无法定位原因，或问题影响上线、跑量、结算和咨询转化时，可以把截图、地区、预算阶段和当前数据发给 ADXJ，进入${seed.serviceName}诊断。`,
      },
    ],
    evidenceNotes: [
      "本文为 ADXJ 出海服务经验、内部案例复盘和公开平台政策理解的综合整理，不构成平台审核或投放结果承诺。",
      `内容最近一次 GEO 复核日期为 ${publishedAt}，用于补充高意图问题、专题内链和市场页信号。`,
    ],
    content: [
      {
        heading: "为什么这个问题值得优先处理",
        paragraphs: [
          `${seed.pain} 看起来可能只是单点故障，但在出海项目里，它往往会同时影响平台信任、用户承接和后续放量。团队如果只看一个指标，很容易把真正的阻塞点误判成素材、预算或审核偶发问题。`,
          `${seed.diagnosis} 这也是 GEO 内容要写清楚的部分：用户搜索的是一个具体问题，AI 引擎需要看到明确判断、适用场景和下一步动作，而不是泛泛的行业描述。`,
        ],
      },
      {
        heading: "ADXJ 建议的三步排查",
        paragraphs: [
          `第一步，${firstAction}。这一步决定文章和业务诊断能否把问题说清楚，也决定后续页面能否被搜索引擎识别为高意图答案。`,
          `第二步，${secondAction}。如果这一步缺失，用户即使点击进站，也很难继续阅读或进入咨询，AI 摘要也会缺少可引用的行动路径。`,
          `第三步，${thirdAction}。最终要把问题导向可执行的${seed.serviceName}动作，而不是停留在“可能原因很多”的模糊判断。`,
        ],
      },
      {
        heading: "如何把内容转成咨询线索",
        paragraphs: [
          `${seed.cta} 页面上应保留直接答案、FAQ、相关文章、专题入口和服务入口，让用户从问题进入，再自然延伸到诊断、上架、投放或资源对接。`,
          `如果你的项目也遇到类似情况，可以准备目标地区、应用品类、当前截图、账户或商店反馈、预算阶段和转化数据，通过 Telegram @M7HHHH、微信 M7HHHH 或 business@adxj.com 联系 ADXJ。`,
        ],
      },
    ],
  };
}

const geoSignalSeeds: GeoSignalSeed[] = [
  {
    title: "App Store 审核卡在订阅页？价格、试用和取消路径这样补齐",
    slug: "app-store-subscription-page-review-geo-signal",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "App Store 订阅页审核卡住，常见原因是价格、周期、试用权益、自动续订和取消路径没有被审核员快速理解。",
    keywords: ["App Store 订阅审核", "iOS 订阅页", "自动续订", "试用价格", "苹果审核"],
    coverImage: "/insights/app-store-subscription-review-price-trial-cancel-fix.png",
    coverAlt: "App Store 订阅页价格、试用和取消路径审核示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "订阅页信息不清、审核员看不到取消路径或试用权益表达不一致",
    diagnosis: "判断重点不是订阅功能是否存在，而是审核员能否在最短路径里确认价格、周期、权益和取消方式。",
    actions: ["把订阅价格、周期、试用和自动续订写在同一条用户路径里", "检查商店截图、应用内订阅页和隐私/条款页面是否一致", "补充审核说明和测试账号，让审核员可复现完整订阅链路"],
    cta: "这类文章标题要直接命中“订阅审核卡住”这个痛点，正文则把截图、审核路径和服务入口串起来。",
  },
  {
    title: "iOS 审核账号总是不可用？登录、验证码和地区权限一次排查",
    slug: "ios-review-account-login-region-code-fix",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "iOS 审核账号不可用会让核心功能被判定无法体验，登录方式、验证码、地区权限和测试数据都要提前准备。",
    keywords: ["iOS 审核账号", "App Store 登录失败", "验证码", "地区权限", "审核被拒"],
    coverImage: "/insights/app-store-review-account-login-failure-fix.png",
    coverAlt: "iOS 审核账号登录、验证码和地区权限排查示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "审核账号登录失败、验证码过期、地区限制或测试数据不足",
    diagnosis: "审核账号不是提交材料的小附属，而是审核员理解产品功能和合规边界的入口。",
    actions: ["准备无需人工介入即可登录的审核账号和固定测试数据", "关闭会阻断审核路径的地区、设备或验证码限制", "在审核备注中写清测试步骤、账号权限和异常处理方式"],
    cta: "内容要把“账号不可用”从小问题升级为上架风险，让用户愿意点进来核对自己的提交路径。",
  },
  {
    title: "AI、金融、SLOTS 上架前 72 小时，iOS 团队要检查什么？",
    slug: "ios-sensitive-app-72-hour-review-checklist",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "AI、金融和 SLOTS 等敏感品类上架前 72 小时，应集中检查元数据、权限、订阅、内容安全、地区限制和审核账号。",
    keywords: ["iOS 上架清单", "敏感品类上架", "AI 应用审核", "金融 App 审核", "SLOTS 上架"],
    coverImage: "/insights/app-store-review-72-hour-checklist.png",
    coverAlt: "敏感品类 iOS 上架前 72 小时检查清单示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "敏感品类临上线才发现描述、权限、内容安全或地区策略不一致",
    diagnosis: "上架前 72 小时要解决的是一致性和可解释性，而不是临时隐藏风险功能。",
    actions: ["把应用描述、截图、包体功能和投放素材做一致性复核", "确认权限、隐私政策、举报入口和年龄分级能够解释风险边界", "按目标地区准备灰度、审核账号和上线后监控方案"],
    cta: "这类内容适合做收藏型清单，标题要突出时间压力和敏感品类，让用户产生立即检查的动机。",
  },
  {
    title: "App Store 隐私披露怎么写才不空？相机、相册和 AI 生成要对齐",
    slug: "app-store-privacy-disclosure-camera-photo-ai-geo",
    category: "开发者出海",
    topic: "app-store",
    excerpt: "App Store 隐私披露不能只写模板，相机、相册、AI 生成、第三方 SDK 和删除路径要和真实功能一一对应。",
    keywords: ["App Store 隐私披露", "相机权限", "相册权限", "AI 生成", "第三方 SDK"],
    coverImage: "/insights/ios-privacy-disclosure-camera-photo-ai-sdk-fix.png",
    coverAlt: "App Store 隐私披露、相机相册和 AI SDK 对齐示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "隐私政策、权限弹窗和数据安全说明写得泛化，无法解释真实使用场景",
    diagnosis: "隐私披露的关键是让用户和审核员理解每类数据为什么被收集、如何处理、多久保存以及如何删除。",
    actions: ["按权限和数据类型重写用途说明", "把第三方 SDK、云端处理和删除入口写进同一套披露材料", "检查商店隐私表单、应用内弹窗和官网隐私政策是否一致"],
    cta: "标题要把隐私披露从抽象合规变成具体权限问题，方便用户快速判断自己是否中招。",
  },
  {
    title: "Google Play 数据安全表单填错了？下架前先核对这 6 类数据",
    slug: "google-play-data-safety-form-six-data-types",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 数据安全表单填错，常见问题在权限、SDK、广告标识、账号数据、支付信息和删除机制没有同步核对。",
    keywords: ["Google Play 数据安全表单", "Android 隐私", "SDK 合规", "数据删除", "Google Play 下架"],
    coverImage: "/insights/google-play-data-safety-form-app-removal-fix.png",
    coverAlt: "Google Play 数据安全表单六类数据核对示意图",
    markets: ["southeast-asia", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "数据安全表单、隐私政策和 SDK 实际行为不一致",
    diagnosis: "表单不是一次性填写材料，而是 Android 应用数据行为的公开承诺。",
    actions: ["列出应用和 SDK 实际采集的数据类型", "逐项核对加密、共享、删除和用户控制方式", "更新隐私政策、商店表单和应用内说明"],
    cta: "这类问题标题要直接出现“填错”和“下架”，让已有风险的团队愿意点击排查。",
  },
  {
    title: "Android 权限被 Google Play 问询？相机、定位、通知要这样解释",
    slug: "android-permission-review-camera-location-notification-geo",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Android 权限审核不过，多数不是权限本身有问题，而是权限触发场景、用户价值和隐私说明没有对齐。",
    keywords: ["Android 权限审核", "相机权限", "定位权限", "通知权限", "Google Play 审核"],
    coverImage: "/insights/android-app-permission-review-camera-location-notification-fix.png",
    coverAlt: "Android 相机定位通知权限审核解释示意图",
    markets: ["southeast-asia", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "权限弹窗、商店说明和实际功能路径无法互相解释",
    diagnosis: "Google Play 更关心权限是否必要、是否在正确时机触发、用户是否知道数据用途。",
    actions: ["删除历史遗留但不再使用的权限", "把权限触发放到用户明确操作之后", "用截图、功能说明和隐私政策解释每个敏感权限"],
    cta: "文章要把“权限审核”拆成具体权限和具体场景，方便 AI 摘要和搜索结果精确匹配。",
  },
  {
    title: "Google Play 新账号生产访问没过？封闭测试不是凑人数",
    slug: "google-play-production-access-closed-testing-quality",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 新账号生产访问卡住，封闭测试要证明真实体验、稳定反馈和应用质量，而不是只凑测试人数。",
    keywords: ["Google Play 生产访问", "封闭测试", "新账号上架", "Android 上架", "测试反馈"],
    coverImage: "/insights/google-play-closed-testing-production-access-fix.png",
    coverAlt: "Google Play 封闭测试和生产访问质量排查示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "封闭测试记录薄弱、用户反馈无效、应用质量信号不足",
    diagnosis: "生产访问审核要看测试是否真实证明产品可用，而不只是账号完成了表面流程。",
    actions: ["设计真实测试任务和反馈问题", "保留崩溃、留存、核心路径和用户建议记录", "在申请材料中解释测试结果和修复动作"],
    cta: "标题要点出“不是凑人数”，吸引正在做新账号上架的团队重新审视测试质量。",
  },
  {
    title: "Google Play 账号关联风险怎么查？包名、域名、SDK 和团队权限别混用",
    slug: "google-play-account-association-assets-audit",
    category: "开发者出海",
    topic: "google-play",
    excerpt: "Google Play 账号关联通常来自资产混用，包名、签名、隐私政策域名、SDK、设备环境和团队权限都要一起审计。",
    keywords: ["Google Play 账号关联", "开发者账号风控", "包名签名", "隐私政策域名", "团队权限"],
    coverImage: "/insights/google-play-association-risk-checklist.png",
    coverAlt: "Google Play 账号关联资产审计清单示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "多个账号、应用和团队成员共享资产，导致风险互相传导",
    diagnosis: "账号关联排查要同时看身份、设备、网络、应用资产、后台域名和操作记录。",
    actions: ["建立账号、包体、域名和 SDK 的资产映射表", "清理团队权限和登录环境", "在申诉或迁移前先判断风险是否可隔离"],
    cta: "内容要让用户意识到关联不是单点封号，而是资产纪律问题，从而进入账号诊断服务。",
  },
  {
    title: "Meta Advantage+ 忽然跑不动？先别加预算，先查事件和素材池",
    slug: "meta-advantage-plus-stops-scaling-event-creative",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta Advantage+ 跑量突然下滑时，优先检查事件回传、素材池疲劳、学习期变化和落地页承接，而不是立刻加预算。",
    keywords: ["Meta Advantage+", "Meta Ads 跑量", "事件回传", "素材池", "学习期"],
    coverImage: "/insights/meta-advantage-plus-performance-drop-event-creative-fix.png",
    coverAlt: "Meta Advantage+ 事件回传和素材池排查示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "预算增加后没有恢复跑量，反而带来更差 CPA 和 ROAS",
    diagnosis: "系统自动化越强，越需要稳定事件、足够素材和清晰转化目标支撑学习。",
    actions: ["核对 Pixel/CAPI 事件是否重复、丢失或延迟", "按角度和生命周期更新素材池", "检查落地页和商店页是否承接广告承诺"],
    cta: "标题要用“先别加预算”制造点击动机，正文再引导用户进入投放诊断。",
  },
  {
    title: "Meta Pixel 和 CAPI 数据打架？ROAS 虚高时这样校准",
    slug: "meta-pixel-capi-roas-overreporting-calibration",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta Pixel 和 CAPI 配置不一致会造成事件重复、归因混乱和 ROAS 虚高，投放团队要先校准数据再优化预算。",
    keywords: ["Meta Pixel", "CAPI", "ROAS 虚高", "广告归因", "事件去重"],
    coverImage: "/insights/meta-pixel-capi-event-tracking-roas-fix.png",
    coverAlt: "Meta Pixel CAPI 事件去重和 ROAS 校准示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "后台 ROAS 看起来很好，但实际收入、退款和订阅续费对不上",
    diagnosis: "投放优化不能建立在错误归因上，事件去重和价值回传是预算决策的地基。",
    actions: ["核对 event_id、事件时间和去重逻辑", "把广告后台收入和后端真实收入对账", "按订阅、首购和续费价值重建优化目标"],
    cta: "这类内容用“数据打架”和“ROAS 虚高”吸引投放负责人点击，后续自然引到数据诊断。",
  },
  {
    title: "Meta 广告账户受限不是单条素材问题，BM、主页和域名都要查",
    slug: "meta-account-restricted-bm-page-domain-audit",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "Meta 广告账户受限往往不是单条素材导致，BM、主页、支付、域名、落地页和广告承诺会共同影响账户稳定。",
    keywords: ["Meta Ads 账户受限", "BM 风控", "主页质量", "落地页审核", "广告账户申诉"],
    coverImage: "/insights/meta-ads-account-restricted-bm-landing-page-fix.png",
    coverAlt: "Meta BM、主页、域名和落地页账户受限排查示意图",
    markets: ["us", "europe", "latam"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "换素材、换广告组后账户仍然频繁受限",
    diagnosis: "账户风控看的是资产整体可信度，不是只看最后提交的一条广告。",
    actions: ["审计 BM、主页、支付、域名和历史违规记录", "统一广告承诺、落地页和商店页表达", "准备申诉材料和后续预防动作"],
    cta: "标题要打破用户“只改素材”的误区，让用户愿意进入完整账户风控排查。",
  },
  {
    title: "AI 伴侣在 Meta 上怎么投才不擦边？情绪价值要翻译成产品能力",
    slug: "meta-ai-companion-safe-creative-product-value",
    category: "海外投放增长",
    topic: "meta-ads",
    excerpt: "AI 伴侣在 Meta 上投放，素材不能只靠暧昧刺激，应把情绪价值翻译成角色设定、长期记忆、语音互动和陪伴场景。",
    keywords: ["Meta Ads", "AI 伴侣投放", "广告素材审核", "情绪价值", "订阅转化"],
    coverImage: "/insights/meta-ads-ai-companion-creative-risk.png",
    coverAlt: "AI 伴侣 Meta Ads 安全素材和产品能力表达示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "素材点击率不错，但审核不稳、退款高、用户预期和真实体验不一致",
    diagnosis: "稳定跑量的素材要让用户知道产品能做什么，而不是用模糊暗示制造短期点击。",
    actions: ["把角色、记忆、语音和场景陪伴做成素材角度", "避免暗示性过强或无法兑现的承诺", "用订阅、留存和退款数据反向筛选素材"],
    cta: "标题要抓住 AI 伴侣团队最关心的审核边界，同时提供可执行的素材替代方向。",
  },
  {
    title: "TikTok SPC 跑偏人群？AI 工具别只回传安装事件",
    slug: "tiktok-spc-ai-tool-event-feedback",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok Smart Performance Campaign 跑偏时，AI 工具不能只优化安装，应回传首次生成、保存、试用和订阅价值事件。",
    keywords: ["TikTok SPC", "TikTok 自动投放", "AI 工具投放", "事件回传", "订阅转化"],
    coverImage: "/insights/tiktok-smart-performance-campaign-ai-tool-event-fix.png",
    coverAlt: "TikTok SPC AI 工具事件回传优化示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "安装成本下降但高价值用户和订阅收入没有增长",
    diagnosis: "自动投放需要高质量事件喂给系统，单一安装事件会把模型带向低价值用户。",
    actions: ["定义首次成功生成、保存、试用和订阅事件", "按地区和素材角度观察事件质量", "把高 LTV 事件逐步设为优化目标"],
    cta: "文章标题要让投放团队意识到“安装便宜”不是成功，从而继续阅读事件回传方案。",
  },
  {
    title: "TikTok 达人素材授权没管好？UGC 爆量前先补合同和白名单",
    slug: "tiktok-ugc-creator-authorization-whitelist",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 达人素材跑量前，授权范围、二剪权限、投放白名单、地区和使用周期都要明确，否则放量后容易出现投诉和下架风险。",
    keywords: ["TikTok 达人素材", "UGC 授权", "素材授权", "白名单投放", "TikTok Ads"],
    coverImage: "/insights/tiktok-creator-creative-authorization-ugc-ads-fix.png",
    coverAlt: "TikTok UGC 达人素材授权和白名单投放示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "达人素材表现好但授权不清，二剪、跨地区投放和白名单使用存在争议",
    diagnosis: "UGC 素材不是拿到视频就能长期投，授权边界决定账户稳定和品牌风险。",
    actions: ["明确素材使用周期、地区、平台和二剪范围", "保留达人授权、沟通和付款记录", "把白名单账户、广告主和素材命名做归档"],
    cta: "标题要用“爆量前”制造行动感，吸引准备放量的团队补齐授权。",
  },
  {
    title: "TikTok 素材疲劳怎么判断？CTR 下滑不一定要马上换方向",
    slug: "tiktok-creative-fatigue-ctr-retention-signals",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 素材疲劳不能只看 CTR，下滑背后可能是频次、受众池、转化质量、落地页承接或订阅事件变化。",
    keywords: ["TikTok 素材疲劳", "CTR 下滑", "短视频素材", "转化质量", "订阅事件"],
    coverImage: "/insights/tiktok-creative-fatigue-ai-video-signals.png",
    coverAlt: "TikTok 素材疲劳 CTR 和转化信号判断示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "团队看到 CTR 下降就频繁换素材，导致学习期和转化模型反复重启",
    diagnosis: "素材疲劳要结合曝光频次、转化事件、用户质量和落地页承接一起判断。",
    actions: ["按素材角度、受众和地区拆分 CTR 与转化数据", "保留有效钩子，只替换表现疲劳的镜头和证明点", "观察订阅、退款和留存，而不是只看点击"],
    cta: "这个标题适合吸引正在焦虑换素材的投放团队，让他们进入更完整的素材诊断。",
  },
  {
    title: "TikTok 点击很多却没人付费？AI 工具落地页和商店页要接住承诺",
    slug: "tiktok-clicks-no-payment-landing-store-match",
    category: "海外投放增长",
    topic: "tiktok-ads",
    excerpt: "TikTok 点击多但无人付费，常见断点在素材承诺、落地页、商店页和首日体验不一致，用户进来后看不到广告里的结果。",
    keywords: ["TikTok Ads", "点击不付费", "AI 工具转化", "落地页承接", "商店页转化"],
    coverImage: "/insights/tiktok-ads-clicks-no-payment-ai-tool-funnel.png",
    coverAlt: "TikTok 点击多但付费少的落地页和商店页承接示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "素材带来大量点击，但安装、试用、订阅和退款数据都不理想",
    diagnosis: "用户点击的是一个承诺，落地页和产品首日体验必须快速兑现这个承诺。",
    actions: ["把广告结果、落地页标题和商店页截图统一", "缩短从点击到核心功能体验的路径", "用首日成功率、试用开始率和订阅率评估素材真实价值"],
    cta: "标题要保留“点击很多却没人付费”的强痛点，正文再引导到漏斗复盘服务。",
  },
  {
    title: "Telegram Bot 怎么筛高意向线索？别让客服被低质量咨询淹没",
    slug: "telegram-bot-high-intent-lead-filter",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram Bot 承接私域流量时，应先筛选地区、预算、品类和当前问题，再把高意向线索分配给人工跟进。",
    keywords: ["Telegram Bot", "线索筛选", "私域转化", "海外社群运营", "咨询转化"],
    coverImage: "/insights/telegram-bot-lead-qualification-dropoff-fix.png",
    coverAlt: "Telegram Bot 高意向线索筛选和人工跟进示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群服务",
    servicePath: "/community",
    pain: "广告和社群带来很多私聊，但客服分不清谁值得优先处理",
    diagnosis: "Bot 的价值不是替代客服，而是让人工团队更快识别高意向用户。",
    actions: ["设置地区、预算、品类、当前卡点和时间节点问题", "把线索按高、中、低意向分层", "给高意向用户配置人工响应 SLA 和案例内容"],
    cta: "标题要击中客服压力和线索质量问题，让用户愿意查看 Bot 承接设计。",
  },
  {
    title: "Telegram 群有人进没人问？欢迎语、服务菜单和案例要先铺好",
    slug: "telegram-group-no-inquiry-welcome-menu-case",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram 群有新增用户但没人咨询，通常是欢迎语、服务菜单、案例内容、FAQ 和人工响应没有形成连续承接。",
    keywords: ["Telegram 社群转化", "欢迎语", "服务菜单", "案例内容", "私域客服"],
    coverImage: "/insights/telegram-community-customer-response-conversion-fix.png",
    coverAlt: "Telegram 社群欢迎语、服务菜单和案例承接示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群服务",
    servicePath: "/community",
    pain: "用户进群后只观察不咨询，群内容无法回答用户真正关心的问题",
    diagnosis: "私域转化要让用户在开口前就知道你能解决什么、怎么合作、有没有相近案例。",
    actions: ["设置欢迎语和固定服务菜单", "按 App 上架、投放、网盟和社群资源展示案例", "安排人工在关键时段响应高意向问题"],
    cta: "标题要让社群运营者意识到问题不在拉新，而在承接内容缺位。",
  },
  {
    title: "Telegram Ads 点进来就流失？落地页、Bot 和群组该选哪个承接",
    slug: "telegram-ads-landing-bot-group-routing",
    category: "海外投放增长",
    topic: "telegram",
    excerpt: "Telegram Ads 点击后流失，通常是承接入口选错；落地页适合解释服务，Bot 适合筛选，群组适合长期教育和资源转化。",
    keywords: ["Telegram Ads", "落地页", "Telegram Bot", "群组承接", "私域转化"],
    coverImage: "/insights/telegram-ads-overseas-conversion-path.png",
    coverAlt: "Telegram Ads 落地页、Bot 和群组承接路径示意图",
    markets: ["southeast-asia", "latam", "europe"],
    serviceName: "行业社群服务",
    servicePath: "/community",
    pain: "用户点击广告后不知道下一步做什么，10 秒内没有形成转化路径",
    diagnosis: "承接入口要和用户意图匹配，链路越复杂越容易丢失高意向用户。",
    actions: ["按广告目标选择落地页、Bot 或群组", "在首屏说明服务、案例和联系方式", "把 Bot 问答和人工响应接到同一个线索表"],
    cta: "标题要提出明确选择题，吸引正在做 Telegram Ads 的团队点进来对照。",
  },
  {
    title: "出海社群怎么避免变广告群？规则、审核和内容节奏要一起做",
    slug: "telegram-community-quality-rules-content-rhythm",
    category: "出海企业洞察",
    topic: "telegram",
    excerpt: "出海社群如果缺少准入规则、广告审核和内容节奏，很快会变成低质量广告群，影响资源撮合和咨询转化。",
    keywords: ["出海社群", "社群规则", "广告审核", "内容节奏", "资源撮合"],
    coverImage: "/insights/telegram-private-traffic-community-conversion.png",
    coverAlt: "出海社群规则、审核和内容节奏运营示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "行业社群服务",
    servicePath: "/community",
    pain: "社群被刷屏广告占据，真正的项目方、开发者和资源方不愿交流",
    diagnosis: "社群质量来自准入、内容、规则和人工维护，不是只靠人数规模。",
    actions: ["设置入群问题和身份审核", "限制刷屏广告和高风险信息", "固定输出案例、政策变化和合作机会"],
    cta: "这篇文章适合吸引想做私域但怕群质量失控的团队，进而进入社群资源合作。",
  },
  {
    title: "AI 换脸 App 被广告拒审？授权、同意和落地页要先讲清楚",
    slug: "ai-face-swap-ads-consent-landing-geo",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 换脸 App 广告被拒，常见原因是用户授权、同意提示、生成边界、举报机制和落地页说明不够清晰。",
    keywords: ["AI 换脸广告", "用户授权", "广告拒审", "落地页合规", "AI 应用出海"],
    coverImage: "/insights/ai-face-swap-ads-rejected-consent-landing-page-fix.png",
    coverAlt: "AI 换脸广告授权、同意和落地页合规示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "素材展示效果很吸引人，但广告平台认为授权和滥用风险没有解释清楚",
    diagnosis: "AI 换脸的审核重点不是技术酷不酷，而是用户是否知道自己上传了什么、生成内容如何被限制。",
    actions: ["在上传和生成路径加入授权提示", "在落地页说明合法用途、举报和删除方式", "避免使用名人、未授权人物或误导性场景素材"],
    cta: "标题要结合广告拒审和授权痛点，让用户快速判断自己是否需要合规诊断。",
  },
  {
    title: "AI 图片生成被投诉？内容安全、举报和模板审核不能后补",
    slug: "ai-image-generation-complaint-safety-reporting",
    category: "开发者出海",
    topic: "ai-apps",
    excerpt: "AI 图片生成产品被投诉，多数问题来自敏感模板、生成结果不可控、举报入口弱和内容安全策略没有前置。",
    keywords: ["AI 图片生成", "内容安全", "用户举报", "模板审核", "AI 应用合规"],
    coverImage: "/insights/ai-image-generation-content-safety-reporting-fix.png",
    coverAlt: "AI 图片生成内容安全、举报和模板审核示意图",
    markets: ["us", "europe"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "产品上线后才发现生成内容、模板推荐和用户投诉影响商店与广告稳定",
    diagnosis: "AI 内容安全要在产品路径里可见，而不是只写在隐私政策或服务条款里。",
    actions: ["给高风险模板设置审核和限制", "提供用户举报、删除和申诉入口", "让广告素材、商店截图和默认模板保持同一风险边界"],
    cta: "标题用“被投诉”承接真实焦虑，正文用清单让用户愿意继续阅读。",
  },
  {
    title: "AI 伴侣次留掉得快？角色记忆、首聊体验和通知节奏要重做",
    slug: "ai-companion-day2-retention-role-memory-notification",
    category: "海外投放增长",
    topic: "ai-apps",
    excerpt: "AI 伴侣次日留存低，常见断点在角色设定不鲜明、首次对话无记忆感、付费墙过早和通知节奏没有情绪价值。",
    keywords: ["AI 伴侣留存", "角色记忆", "次日留存", "通知节奏", "订阅转化"],
    coverImage: "/insights/ai-companion-day2-retention-role-memory-notification-fix.png",
    coverAlt: "AI 伴侣角色记忆、首聊体验和通知节奏优化示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "下载和注册还可以，但用户第二天不回来，订阅转化也起不来",
    diagnosis: "AI 伴侣增长不是只靠角色卡，而是要让用户在第一次对话里感受到关系感和持续价值。",
    actions: ["强化角色性格、记忆点和开场引导", "把付费墙放在用户感知价值之后", "用通知承接未完成对话和用户偏好"],
    cta: "标题要把留存问题说具体，吸引产品和投放团队一起看首日体验。",
  },
  {
    title: "AI 视频 App 下载高订阅低？模板价值和等待时间是关键断点",
    slug: "ai-video-download-high-subscription-low-template-waiting",
    category: "海外投放增长",
    topic: "ai-apps",
    excerpt: "AI 视频 App 下载高但订阅低，常见原因是模板价值不清、生成等待时间长、结果不稳定和订阅墙出现时机错误。",
    keywords: ["AI 视频 App", "订阅转化", "模板价值", "生成等待", "AI 图生视频"],
    coverImage: "/insights/ai-image-to-video-app-download-high-subscription-low.png",
    coverAlt: "AI 视频 App 下载高订阅低和模板价值断点示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "素材吸引用户下载，但第一次生成体验不足以支撑订阅",
    diagnosis: "AI 视频订阅要让用户先看到足够稳定和有价值的结果，再提出付费升级。",
    actions: ["把高价值模板放到首日路径前段", "优化生成等待提示和失败兜底", "按素材角度回看订阅率、退款率和续费率"],
    cta: "标题要同时点出下载和订阅落差，让用户愿意进入完整漏斗复盘。",
  },
  {
    title: "SLOTS 商店页和落地页不一致？ROI 差可能不是买量问题",
    slug: "slots-store-landing-mismatch-roi-geo-signal",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 商店页和落地页表达不一致，会导致点击、安装、首充和广告审核信号断层，ROI 变差不一定是买量问题。",
    keywords: ["SLOTS 落地页", "商店页转化", "游戏投放", "买量 ROI", "广告审核"],
    coverImage: "/insights/slots-landing-page-store-page-mismatch-roi-fix.png",
    coverAlt: "SLOTS 商店页和落地页一致性与 ROI 排查示意图",
    markets: ["latam", "us"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "广告点击高但安装和首充掉得快，商店页无法承接素材承诺",
    diagnosis: "SLOTS 增长要看从素材、落地页、商店页到首充活动的连续性。",
    actions: ["统一素材、落地页和商店页的玩法表达", "检查奖励、虚拟体验和地区限制说明", "按地区复盘点击、安装、注册和首充漏斗"],
    cta: "标题要挑战用户“买量不行”的默认判断，把注意力引到承接链路。",
  },
  {
    title: "SLOTS 支付漏斗掉得厉害？地区、通道和首充活动要一起看",
    slug: "slots-payment-funnel-region-channel-first-deposit",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 支付漏斗掉得厉害，不能只看支付通道，还要结合地区价格、首充活动、用户质量和素材承诺一起复盘。",
    keywords: ["SLOTS 支付漏斗", "首充转化", "地区支付", "游戏买量", "ROI 回收"],
    coverImage: "/insights/slots-payment-funnel-dropoff-region-channel-fix.png",
    coverAlt: "SLOTS 支付漏斗、地区通道和首充活动排查示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "注册不少但首充少，团队不确定是支付、活动还是用户质量问题",
    diagnosis: "支付漏斗是增长、产品、风控和本地化共同作用的结果。",
    actions: ["按国家、通道和设备拆分支付成功率", "检查首充活动与素材承诺是否一致", "用用户质量和回本周期判断渠道是否继续放量"],
    cta: "标题要抓住首充掉点这个最直接的商业问题，吸引团队进入支付和买量复盘。",
  },
  {
    title: "SLOTS 回本周期拉长怎么办？Day7 ROI 要拆到地区和素材",
    slug: "slots-payback-cycle-day7-roi-region-creative",
    category: "海外投放增长",
    topic: "slots",
    excerpt: "SLOTS 回本周期拉长时，Day7 ROI 需要拆到地区、素材、渠道、支付和用户留存，不能只看整体平均值。",
    keywords: ["SLOTS 回本周期", "Day7 ROI", "地区选择", "素材测试", "游戏投放"],
    coverImage: "/insights/slots-overseas-payback-slow-day7-roi-review.png",
    coverAlt: "SLOTS 回本周期、Day7 ROI 和地区素材拆分示意图",
    markets: ["latam", "us"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "整体 ROI 变差，但团队不知道应该停地区、换素材还是调活动",
    diagnosis: "回本慢通常不是单一成本问题，而是地区支付、用户质量和运营节奏共同变化。",
    actions: ["按地区和素材拆 Day0/Day1/Day7 数据", "观察首充、复充、留存和支付失败率", "把预算转向回本更稳定的组合"],
    cta: "标题把 Day7 ROI 写出来，能吸引真正负责投放回收的用户点击。",
  },
  {
    title: "SLOTS 新市场先开哪里？别只看 CPI，要看支付和风控边界",
    slug: "slots-new-market-cpi-payment-risk-selection",
    category: "出海企业洞察",
    topic: "slots",
    excerpt: "SLOTS 新市场选择不能只看 CPI，支付成功率、政策边界、素材审核、用户 LTV 和客服能力都会影响最终回收。",
    keywords: ["SLOTS 新市场", "CPI", "支付成功率", "风控边界", "LTV"],
    coverImage: "/insights/slots-overseas-ua-cost-market-risk.png",
    coverAlt: "SLOTS 新市场 CPI、支付和风控边界选择示意图",
    markets: ["latam", "southeast-asia", "us"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "团队看到某地区 CPI 低就放量，却忽略支付、政策和客服承接成本",
    diagnosis: "市场选择要用回收模型判断，而不是用单一获客成本做决定。",
    actions: ["建立地区政策、支付、素材审核和 LTV 表", "小预算验证注册、首充和留存", "在放量前准备客服、支付和风控预案"],
    cta: "标题要反直觉地提醒用户“CPI 低不等于值得投”，适合做市场决策内容。",
  },
  {
    title: "现金贷落地页费用没讲清？广告拒审和用户投诉会一起发生",
    slug: "cash-loan-fee-disclosure-landing-complaint-geo",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷落地页如果费用、周期、还款、逾期和用户权益披露不清，广告拒审、投诉和后端风险会同时放大。",
    keywords: ["现金贷落地页", "费用披露", "金融广告拒审", "用户投诉", "现金贷出海"],
    coverImage: "/insights/cash-loan-landing-page-fee-disclosure-ads-complaint-fix.png",
    coverAlt: "现金贷落地页费用披露和广告投诉排查示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "落地页强调快速申请，却没有让用户清楚理解费用和还款责任",
    diagnosis: "金融广告合规和转化不是对立关系，清楚披露能减少错误用户和后端投诉。",
    actions: ["把费用、周期、还款和逾期信息放到用户决策前", "统一广告、落地页和应用内合同表达", "用投诉、退款和首还数据反向优化素材"],
    cta: "标题要把拒审和投诉连起来，吸引现金贷团队从前端页面开始排查。",
  },
  {
    title: "现金贷申请多首还差？渠道质量不能只看 CPA",
    slug: "cash-loan-many-applications-low-first-repayment",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷申请量高但首还差，说明渠道质量、用户意图、审批模型和还款提醒可能不匹配，不能只按 CPA 判断预算。",
    keywords: ["现金贷渠道质量", "首还逾期", "金融 App 投放", "获客风控", "CPA 优化"],
    coverImage: "/insights/cash-loan-channel-high-applications-low-repayment-fix.png",
    coverAlt: "现金贷申请高首还差和渠道质量复盘示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "前端申请成本好看，但审批、放款和首还表现拖累整体回收",
    diagnosis: "现金贷投放必须把获客和风控放在一起看，低 CPA 可能只是低质量用户变多。",
    actions: ["按渠道、素材、地区和设备拆申请到首还漏斗", "把审批率、放款率和逾期率回传给投放团队", "暂停只带来低质量申请的素材和渠道"],
    cta: "标题要直接打中老板关心的“首还差”，推动用户继续看完整漏斗。",
  },
  {
    title: "现金贷广告素材怎么写才稳？快放款不是唯一卖点",
    slug: "cash-loan-ad-creative-compliance-value",
    category: "海外投放增长",
    topic: "cash-loan",
    excerpt: "现金贷广告素材不能只强调快放款，额度、费用、资格、还款责任和用户权益要更平衡，才能兼顾审核和用户质量。",
    keywords: ["现金贷广告素材", "金融广告合规", "快放款", "获客质量", "素材审核"],
    coverImage: "/insights/cash-loan-ad-risk-funnel-repayment.png",
    coverAlt: "现金贷广告素材合规和还款漏斗示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "素材刺激点击但带来低意向用户、投诉和审核风险",
    diagnosis: "稳定素材要同时筛选正确用户和降低误解，而不是最大化冲动点击。",
    actions: ["用资格、用途、费用透明和还款提醒替代夸张承诺", "让素材、落地页和合同信息保持一致", "按审批率、首还和投诉率评估素材质量"],
    cta: "标题要挑战“快放款万能”的素材习惯，引导团队进入合规素材复盘。",
  },
  {
    title: "现金贷新地区怎么冷启动？先跑风控样本，再谈大预算",
    slug: "cash-loan-new-market-risk-sample-before-scale",
    category: "出海企业洞察",
    topic: "cash-loan",
    excerpt: "现金贷新地区冷启动应先跑小规模风控样本，验证申请、审批、放款、首还和投诉，再决定是否扩大预算。",
    keywords: ["现金贷新地区", "冷启动", "风控样本", "首还", "预算放量"],
    coverImage: "/insights/cash-loan-overseas-growth-compliance.png",
    coverAlt: "现金贷新地区冷启动和风控样本验证示意图",
    markets: ["southeast-asia", "latam"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "新地区没跑出完整还款周期就急着加预算",
    diagnosis: "现金贷增长要先证明风险可控，再证明预算可放大。",
    actions: ["设定小预算样本和最小观察周期", "把申请、审批、放款、首还和投诉串成一张表", "用真实回收数据决定地区和渠道优先级"],
    cta: "标题用“先跑风控样本”吸引决策者，避免只看获客成本做市场选择。",
  },
  {
    title: "CPA Offer 放量掉质量？Cap、Pacing 和回传要一起调",
    slug: "cpa-offer-scaling-quality-cap-pacing-geo",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "CPA Offer 放量后质量下降，通常是 Cap、Pacing、渠道结构和质量回传没有同步调整，不能只提高预算。",
    keywords: ["CPA Offer", "Cap 设置", "Pacing", "质量回传", "海外网盟"],
    coverImage: "/insights/cpa-offer-scaling-cap-pacing-quality-feedback-fix.png",
    coverAlt: "CPA Offer 放量、Cap、Pacing 和质量回传示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "Offer 一放量就出现低质量转化、扣量争议和广告主投诉",
    diagnosis: "CPA 放量要让广告主、网盟和流量主共享质量信号，而不是只看转化数。",
    actions: ["按渠道设置 Cap 和 Pacing", "把留存、付费、首还或有效行为回传给流量侧", "用质量阈值决定继续放量还是降速"],
    cta: "标题要抓住“放量掉质量”这个网盟痛点，引导用户查看完整放量框架。",
  },
  {
    title: "Postback 丢量怎么办？流量主 API 接入要先查这几个点",
    slug: "publisher-postback-lost-conversions-api-audit",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "Postback 丢量会直接影响 CPA 对账和流量主信任，API 接入、参数映射、去重、延迟和回调日志都要一起查。",
    keywords: ["Postback 回传", "流量主 API", "CPA 对账", "转化丢量", "海外网盟"],
    coverImage: "/insights/publisher-api-integration-lost-conversions-postback-audit.png",
    coverAlt: "流量主 API 接入和 Postback 转化丢量审计示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "流量主后台和广告主后台转化数对不上，双方很难判断责任",
    diagnosis: "Postback 问题要用日志和参数定位，不能只靠人工对账争论。",
    actions: ["核对 click_id、offer_id、时间戳和签名参数", "检查去重规则、延迟回调和失败重试", "保留双方日志用于每日对账"],
    cta: "标题要让流量主看到“丢量”和“对账”关键词，快速进入技术接入咨询。",
  },
  {
    title: "Day0 结算真的适合所有流量主吗？质量阈值要先说清",
    slug: "publisher-day0-settlement-quality-thresholds-geo",
    category: "出海企业洞察",
    topic: "cpa-network",
    excerpt: "Day0 结算能改善流量主现金流，但必须配合质量阈值、反作弊、扣量规则和广告主反馈，否则会放大结算风险。",
    keywords: ["Day0 结算", "流量主变现", "质量阈值", "CPA Offer", "网盟结算"],
    coverImage: "/insights/publisher-day0-settlement-advertiser-quality-thresholds.png",
    coverAlt: "Day0 结算、质量阈值和广告主反馈示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "流量主希望更快回款，但广告主担心低质量和反作弊风险",
    diagnosis: "快速结算不是无条件提前付款，而是建立在质量数据和合作纪律上。",
    actions: ["明确有效转化、留存、付费或风控质量阈值", "设置异常流量暂停和复核机制", "把广告主反馈周期写进结算规则"],
    cta: "标题要用“真的适合所有流量主吗”制造判断感，吸引双方阅读规则。",
  },
  {
    title: "CPA 流量作弊怎么早发现？别等扣量后再追责",
    slug: "cpa-traffic-fraud-early-detection-signals",
    category: "海外投放增长",
    topic: "cpa-network",
    excerpt: "CPA 流量作弊要尽早识别，异常点击、设备集中、转化时间过短、留存差和质量回传异常都是预警信号。",
    keywords: ["CPA 流量作弊", "海外网盟反作弊", "渠道质量", "扣量争议", "广告主投放"],
    coverImage: "/insights/overseas-cpa-traffic-fraud-detection-checklist.png",
    coverAlt: "CPA 流量作弊早期识别和反作弊信号示意图",
    markets: ["latam", "southeast-asia"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "广告主等到账单期才发现质量差，流量主也无法及时调整",
    diagnosis: "反作弊要把异常信号前置到日常监控，而不是结算后才处理。",
    actions: ["设置点击、设备、IP、转化时间和留存异常阈值", "把低质量渠道及时降速或暂停", "保留证据用于对账、复盘和后续合作规则"],
    cta: "标题要用“别等扣量后”触发紧迫感，适合广告主和网盟双方点击。",
  },
  {
    title: "ASO 本地化只翻译标题够吗？关键词、截图和评论也要本地化",
    slug: "aso-localization-title-screenshot-review-geo",
    category: "开发者出海",
    topic: "aso",
    excerpt: "ASO 本地化不能只翻译标题，关键词、截图、短描述、评论信号、价格和首日体验都要贴合目标市场。",
    keywords: ["ASO 本地化", "App Store 排名", "Google Play 关键词", "截图本地化", "自然量增长"],
    coverImage: "/insights/aso-localization-keywords-us-sea-latam-case.png",
    coverAlt: "ASO 本地化标题、关键词、截图和评论信号示意图",
    markets: ["us", "southeast-asia", "latam"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "团队只翻译标题，导致关键词覆盖、点击率和转化都没有明显提升",
    diagnosis: "本地化的目标是让用户和商店算法都理解产品价值，而不是完成语言替换。",
    actions: ["按地区重做核心关键词和长尾需求词", "让截图展示当地用户关心的结果和场景", "结合评论、评分和买量信号观察自然量变化"],
    cta: "标题要用“只翻译标题够吗”引发自查，适合 ASO 和产品团队点击。",
  },
  {
    title: "新 App 没有自然量？ASO 和买量信号要一起启动",
    slug: "new-app-no-organic-aso-paid-signal-launch",
    category: "开发者出海",
    topic: "aso",
    excerpt: "新 App 没有自然量，常见原因是关键词、截图、描述、评分和外部买量信号没有形成冷启动合力。",
    keywords: ["新 App 自然量", "ASO 冷启动", "App Store 排名", "Google Play 关键词", "买量信号"],
    coverImage: "/insights/new-app-no-organic-traffic-aso-paid-signal-case.png",
    coverAlt: "新 App ASO 冷启动和买量信号联动示意图",
    markets: ["us", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "应用上线后没有搜索曝光，团队不知道该先改关键词还是先买量",
    diagnosis: "冷启动阶段要同时建立商店理解、用户点击和外部行为信号。",
    actions: ["确定 5-10 个核心需求词和场景词", "用截图和描述承接买量素材里的承诺", "观察展示、点击、安装和留存共同变化"],
    cta: "标题直接命中“没有自然量”的焦虑，正文要给出 ASO 和投放联动路径。",
  },
  {
    title: "品牌词被别人截流怎么办？SEO、广告和官网内容要一起防守",
    slug: "brand-keyword-defense-seo-ads-content",
    category: "出海企业洞察",
    topic: "aso",
    excerpt: "品牌词被竞品、代理或灰色页面截流时，官网 SEO、品牌词广告、服务页和案例内容要一起建立搜索防守。",
    keywords: ["品牌词 SEO", "出海官网 SEO", "品牌词广告", "搜索防守", "海外品牌增长"],
    coverImage: "/insights/brand-keyword-defense-overseas-seo-ads-strategy.png",
    coverAlt: "品牌词 SEO、广告和官网内容防守策略示意图",
    markets: ["us", "europe", "southeast-asia"],
    serviceName: "开发者服务",
    servicePath: "/developer",
    pain: "用户搜索品牌或服务词时，被竞品广告、代理页或低质量内容分流",
    diagnosis: "品牌词防守不是只买广告，而是让官网、专题、案例和联系方式占据可信结果。",
    actions: ["完善首页、服务页和品牌关系说明", "围绕品牌词和服务词建立文章集群", "用广告、GSC 和线索数据监控截流变化"],
    cta: "标题要让用户意识到搜索防守会影响询盘，适合企业负责人和市场团队阅读。",
  },
  {
    title: "工具 App 关键词成本上涨？免费词、高意图词和订阅词要分层",
    slug: "utility-app-keyword-cost-free-intent-subscription",
    category: "海外投放增长",
    topic: "aso",
    excerpt: "工具 App 关键词成本上涨时，要区分免费需求词、高意图功能词和订阅价值词，否则买量和 ASO 都会被低价值流量拖累。",
    keywords: ["工具 App 关键词", "ASO 优化", "Google Ads", "订阅转化", "关键词分层"],
    coverImage: "/insights/google-ads-utility-app-cost-rising-keyword-value-fix.png",
    coverAlt: "工具 App 关键词成本上涨和订阅价值分层示意图",
    markets: ["us", "europe"],
    serviceName: "媒体买量服务",
    servicePath: "/media",
    pain: "关键词带来流量但订阅少，团队无法判断哪些词值得继续投",
    diagnosis: "关键词价值要用订阅、续费和 LTV 判断，而不是只看点击或安装成本。",
    actions: ["把免费需求词、功能词和付费意图词分开观察", "让商店页截图承接高价值关键词", "把订阅事件回传给广告和 ASO 复盘"],
    cta: "标题要把成本上涨和关键词分层连起来，吸引工具 App 团队进入优化方案。",
  },
];

export const geoSignalArticles: InsightArticle[] = geoSignalSeeds.map(geoSignalArticle);
